# extras/wezterm/oasis_luna_light_4.toml
## name: Oasis Luna Light 4
## author: uhs-robert

[colors]
foreground = "#342b55"
background= "#bcb9ee"
cursor_bg = "#453e11"
cursor_border = "#453e11"
cursor_fg= "#bcb9ee"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#411f68"
compose_cursor= "#472b11"
scrollbar_thumb= "#9994e5"
visual_bell= "#b0adeb"

ansi = [
  '#313131',
  '#7e0d0d',
  '#274525',
  '#433e16',
  '#0e3f6f',
  '#531997',
  '#23433f',
  '#3a300c',
]

brights = [
  '#37302b',
  '#7e0c0c',
  '#244520',
  '#5c340e',
  '#184253',
  '#521998',
  '#22433e',
  '#36311d',
]

[colors.indexed]
16 = '#472b11'
17 = '#7e0e12'

[colors.tab_bar]
background = '#b0adeb'
inactive_tab_edge = '#a5a1e8'

[colors.tab_bar.active_tab]
bg_color = '#796e11'
fg_color = '#bcb9ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#9994e5'
fg_color = '#796e11'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#9994e5'
fg_color = '#450192'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#450192'
fg_color = '#bcb9ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#136881'
fg_color = '#bcb9ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 4'