# extras/wezterm/oasis_midnight_light_4.toml
## name: Oasis Midnight Light 4
## author: uhs-robert

[colors]
foreground = "#171412"
background= "#f4cbc2"
cursor_bg = "#625918"
cursor_border = "#625918"
cursor_fg= "#f4cbc2"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#7a1e1e"
compose_cursor= "#845020"
scrollbar_thumb= "#edaa9b"
visual_bell= "#f2c0b5"

ansi = [
  '#404040',
  '#9a1010',
  '#30542d',
  '#524d1c',
  '#114d89',
  '#651eb8',
  '#2b534e',
  '#4b3f10',
]

brights = [
  '#473e38',
  '#9a0f0f',
  '#2d5527',
  '#714011',
  '#1d5267',
  '#651eba',
  '#2a534d',
  '#474026',
]

[colors.indexed]
16 = '#845020'
17 = '#991116'

[colors.tab_bar]
background = '#f2c0b5'
inactive_tab_edge = '#f0b5a8'

[colors.tab_bar.active_tab]
bg_color = '#534e1b'
fg_color = '#f4cbc2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#edaa9b'
fg_color = '#534e1b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#edaa9b'
fg_color = '#6d0101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#6d0101'
fg_color = '#f4cbc2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2d6c27'
fg_color = '#f4cbc2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Light 4'