# extras/wezterm/oasis_twilight_light_4.toml
## name: Oasis Twilight Light 4
## author: uhs-robert

[colors]
foreground = "#161217"
background= "#f5d2c7"
cursor_bg = "#894c16"
cursor_border = "#894c16"
cursor_fg= "#f5d2c7"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#6d3221"
compose_cursor= "#895321"
scrollbar_thumb= "#eeb3a0"
visual_bell= "#f3c8ba"

ansi = [
  '#434343',
  '#a01010',
  '#32582f',
  '#56501d',
  '#11508f',
  '#6a20c0',
  '#2d5652',
  '#4f4311',
]

brights = [
  '#4b423b',
  '#a00f0f',
  '#2f5929',
  '#754311',
  '#1e556b',
  '#691fc2',
  '#2c5650',
  '#4a4328',
]

[colors.indexed]
16 = '#895321'
17 = '#9f1117'

[colors.tab_bar]
background = '#f3c8ba'
inactive_tab_edge = '#f0bdad'

[colors.tab_bar.active_tab]
bg_color = '#661d07'
fg_color = '#f5d2c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eeb3a0'
fg_color = '#661d07'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eeb3a0'
fg_color = '#32016d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#32016d'
fg_color = '#f5d2c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#827712'
fg_color = '#f5d2c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight Light 4'