# extras/wezterm/oasis_canyon_light_4.toml
## name: Oasis Canyon Light 4
## author: uhs-robert

[colors]
foreground = "#574630"
background= "#f5dfc7"
cursor_bg = "#7f4714"
cursor_border = "#7f4714"
cursor_fg= "#f5dfc7"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#683f19"
compose_cursor= "#58471e"
scrollbar_thumb= "#eec9a0"
visual_bell= "#f3d8ba"

ansi = [
  '#494949',
  '#aa1111',
  '#355e32',
  '#5c561f',
  '#135698',
  '#7122cd',
  '#305c57',
  '#564812',
]

brights = [
  '#514740',
  '#aa1010',
  '#325f2c',
  '#7d4813',
  '#205b73',
  '#7021cf',
  '#2f5d56',
  '#50482b',
]

[colors.indexed]
16 = '#58471e'
17 = '#aa1218'

[colors.tab_bar]
background = '#f3d8ba'
inactive_tab_edge = '#f0d0ad'

[colors.tab_bar.active_tab]
bg_color = '#884501'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eec9a0'
fg_color = '#884501'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eec9a0'
fg_color = '#920101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#920101'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#16607e'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 4'