# extras/wezterm/oasis_sol_light_4.toml
## name: Oasis Sol Light 4
## author: uhs-robert

[colors]
foreground = "#1d0f0c"
background= "#efb7b7"
cursor_bg = "#962024"
cursor_border = "#962024"
cursor_fg= "#efb7b7"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#603e1b"
compose_cursor= "#76471d"
scrollbar_thumb= "#e48585"
visual_bell= "#eba4a4"

ansi = [
  '#2b2b2b',
  '#870e0e',
  '#2a4a27',
  '#484318',
  '#0f4377',
  '#591ba1',
  '#254844',
  '#322a0b',
]

brights = [
  '#302a25',
  '#870d0d',
  '#274a22',
  '#62380f',
  '#19475a',
  '#581aa3',
  '#254843',
  '#2f2b19',
]

[colors.indexed]
16 = '#76471d'
17 = '#583d0a'

[colors.tab_bar]
background = '#eba4a4'
inactive_tab_edge = '#ecaaaa'

[colors.tab_bar.active_tab]
bg_color = '#6d0101'
fg_color = '#efb7b7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e48585'
fg_color = '#6d0101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e48585'
fg_color = '#683606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#683606'
fg_color = '#efb7b7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2d6c27'
fg_color = '#efb7b7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 4'