# extras/wezterm/oasis_sol_light_4.toml
## name: Oasis Sol Light 4
## author: uhs-robert

[colors]
foreground = "#1d0f0c"
background= "#ecb0b0"
cursor_bg = "#8f1f22"
cursor_border = "#8f1f22"
cursor_fg= "#ecb0b0"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#601717"
compose_cursor= "#70441b"
scrollbar_thumb= "#e38b8b"
visual_bell= "#e69797"

ansi = [
  '#262626',
  '#7f0d0d',
  '#274525',
  '#443f17',
  '#0e3f70',
  '#541998',
  '#234440',
  '#2d2609',
]

brights = [
  '#2b2521',
  '#7f0c0c',
  '#254620',
  '#5c350e',
  '#184354',
  '#53199a',
  '#23443f',
  '#2a2617',
]

[colors.indexed]
16 = '#70441b'
17 = '#533909'

[colors.tab_bar]
background = '#e69797'
inactive_tab_edge = '#e9a4a4'

[colors.tab_bar.active_tab]
bg_color = '#6d0101'
fg_color = '#ecb0b0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e38b8b'
fg_color = '#6d0101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e38b8b'
fg_color = '#683606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#683606'
fg_color = '#ecb0b0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2d6c27'
fg_color = '#ecb0b0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 4'