# extras/wezterm/oasis_cactus_light_4.toml
## name: Oasis Cactus Light 4
## author: uhs-robert

[colors]
foreground = "#121714"
background= "#d2eadb"
cursor_bg = "#406c42"
cursor_border = "#406c42"
cursor_fg= "#d2eadb"
selection_bg= "#a4dac0"
selection_fg= "#15472f"
split= "#3a4f3c"
compose_cursor= "#925923"
scrollbar_thumb= "#b3dbc2"
visual_bell= "#bde0ca"

ansi = [
  '#404040',
  '#ac1111',
  '#365f33',
  '#5d571f',
  '#13579a',
  '#7222cf',
  '#305d58',
  '#4b3f10',
]

brights = [
  '#473e38',
  '#ac1111',
  '#33602c',
  '#7f4813',
  '#215c74',
  '#7122d1',
  '#305e57',
  '#464025',
]

[colors.indexed]
16 = '#925923'
17 = '#ac1318'

[colors.tab_bar]
background = '#bde0ca'
inactive_tab_edge = '#c8e5d3'

[colors.tab_bar.active_tab]
bg_color = '#264728'
fg_color = '#d2eadb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#b3dbc2'
fg_color = '#264728'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#b3dbc2'
fg_color = '#6d0101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#6d0101'
fg_color = '#d2eadb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#430192'
fg_color = '#d2eadb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 4'