# extras/wezterm/oasis_abyss_light_4.toml
## name: Oasis Abyss Light 4
## author: uhs-robert

[colors]
foreground = "#4c453e"
background= "#eaddbe"
cursor_bg = "#5b5216"
cursor_border = "#5b5216"
cursor_fg= "#eaddbe"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#852020"
compose_cursor= "#653d18"
scrollbar_thumb= "#decb9b"
visual_bell= "#e6d7b2"

ansi = [
  '#464646',
  '#a51111',
  '#335b30',
  '#59531e',
  '#125393',
  '#6d21c6',
  '#2e5955',
  '#524511',
]

brights = [
  '#4e443d',
  '#a51010',
  '#305c2a',
  '#794512',
  '#1f586f',
  '#6c20c8',
  '#2e5a53',
  '#4d4629',
]

[colors.indexed]
16 = '#653d18'
17 = '#a41217'

[colors.tab_bar]
background = '#e6d7b2'
inactive_tab_edge = '#e2d1a7'

[colors.tab_bar.active_tab]
bg_color = '#686222'
fg_color = '#eaddbe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#decb9b'
fg_color = '#686222'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#decb9b'
fg_color = '#920101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#920101'
fg_color = '#eaddbe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2d6c27'
fg_color = '#eaddbe'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 4'