# extras/wezterm/oasis_luna_light_4.toml
## name: Oasis Luna Light 4
## author: uhs-robert

[colors]
foreground = "#110e1b"
background= "#d0cef3"
cursor_bg = "#605717"
cursor_border = "#605717"
cursor_fg= "#d0cef3"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#36367c"
compose_cursor= "#814e1f"
scrollbar_thumb= "#ada9ea"
visual_bell= "#c4c2f0"

ansi = [
  '#3e3e3e',
  '#960f0f',
  '#2f532c',
  '#514b1b',
  '#104b86',
  '#631eb4',
  '#2a514d',
  '#493d0f',
]

brights = [
  '#463d36',
  '#970f0f',
  '#2c5326',
  '#6e3f10',
  '#1c5064',
  '#631db6',
  '#2a514b',
  '#453e25',
]

[colors.indexed]
16 = '#814e1f'
17 = '#961015'

[colors.tab_bar]
background = '#c4c2f0'
inactive_tab_edge = '#b8b5ed'

[colors.tab_bar.active_tab]
bg_color = '#60580d'
fg_color = '#d0cef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ada9ea'
fg_color = '#60580d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ada9ea'
fg_color = '#14145a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#14145a'
fg_color = '#d0cef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#136881'
fg_color = '#d0cef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 4'