# extras/wezterm/oasis_canyon_light_4.toml
## name: Oasis Canyon Light 4
## author: uhs-robert

[colors]
foreground = "#1a150e"
background= "#ebcbb1"
cursor_bg = "#814814"
cursor_border = "#814814"
cursor_fg= "#ebcbb1"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#6f431b"
compose_cursor= "#6d5725"
scrollbar_thumb= "#dfab80"
visual_bell= "#e6bf9f"

ansi = [
  '#333333',
  '#960f0f',
  '#2e522c',
  '#504b1b',
  '#104b85',
  '#631eb3',
  '#2a504c',
  '#3c330d',
]

brights = [
  '#39322d',
  '#960f0f',
  '#2c5326',
  '#6e3f10',
  '#1c4f64',
  '#621db5',
  '#29514b',
  '#39331e',
]

[colors.indexed]
16 = '#6d5725'
17 = '#951015'

[colors.tab_bar]
background = '#e6bf9f'
inactive_tab_edge = '#e8c3a5'

[colors.tab_bar.active_tab]
bg_color = '#683606'
fg_color = '#ebcbb1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#dfab80'
fg_color = '#683606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#dfab80'
fg_color = '#023e6c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#023e6c'
fg_color = '#ebcbb1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#920101'
fg_color = '#ebcbb1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 4'