# vim:set ft=tmux:
## name: Oasis Sol Light 1
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#9a3535"
set -ogq @thm_primary "#870606"
set -ogq @thm_light_primary "#7d0505"
set -ogq @thm_secondary "#81460c"
set -ogq @thm_prefix "#388032"
set -ogq @thm_fg "#271410"

# Surfaces and overlays
set -ogq @thm_core "#f7f3f3"
set -ogq @thm_mantle "#f1eaea"
set -ogq @thm_surface "#e4d7d7"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#be1313"
set -ogq @thm_orange "#8c5015"
set -ogq @thm_yellow "#676022"
set -ogq @thm_green "#7d4514"
set -ogq @thm_teal "#346860"
set -ogq @thm_blue "#1560ab"
set -ogq @thm_indigo "#7d2cdd"
