# extras/kitty/oasis_cactus_light_1.conf
## name: Oasis Cactus Light 1
## author: uhs-robert

# Palette
color0                   #4b4b4b
color8                   #534940

color1                   #c11313
color9                   #c11313

color2                   #3d6c39
color10                  #396c32

color3                   #696223
color11                  #8f5215

color4                   #1661ae
color12                  #266883

color5                   #7f30de
color13                  #7f31de

color6                   #366964
color14                  #356a62

color7                   #574a13
color15                  #534a2c

# Core
foreground               #161d19
background               #f1f9f4

# Selection
selection_background     #a4dac0
selection_foreground     #15472f

# Cursor
cursor                   #467949
cursor_text_color        #f1f9f4

# Borders (panes)
active_border_color      #435b44
inactive_border_color    #dcf0e3

# Tabs
active_tab_foreground    #f1f9f4
active_tab_background    #325a34
inactive_tab_foreground  #325a34
inactive_tab_background  #dcf0e3
