# extras/kitty/oasis_desert_light_1.conf
## name: Oasis Desert Light 1
## author: uhs-robert

# Palette
color0                   #565656
color8                   #61544b

color1                   #c51414
color9                   #c51414

color2                   #3e6d3a
color10                  #3a6e33

color3                   #6b6424
color11                  #915316

color4                   #1663b2
color12                  #266a86

color5                   #8233de
color13                  #8134de

color6                   #376b66
color14                  #366c63

color7                   #655516
color15                  #605633

# Core
foreground               #65543e
background               #fbfaf9

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #6e631a
cursor_text_color        #fbfaf9

# Borders (panes)
active_border_color      #a32626
inactive_border_color    #f5f2f0

# Tabs
active_tab_foreground    #fbfaf9
active_tab_background    #908419
inactive_tab_foreground  #908419
inactive_tab_background  #f5f2f0
