# extras/kitty/oasis_night_light_1.conf
## name: Oasis Night Light 1
## author: uhs-robert

# Palette
color0                   #5e3c33
color8                   #593f30

color1                   #a21010
color9                   #a21010

color2                   #33592f
color10                  #2f5a2a

color3                   #57511d
color11                  #764412

color4                   #125191
color12                  #1f566d

color5                   #6b1fc4
color13                  #6a20c4

color6                   #2d5753
color14                  #2c5851

color7                   #504311
color15                  #4c4428

# Core
foreground               #52422d
background               #e0dbcc

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #784313
cursor_text_color        #e0dbcc

# Borders (panes)
active_border_color      #354658
inactive_border_color    #dbd5c2

# Tabs
active_tab_foreground    #e0dbcc
active_tab_background    #355374
inactive_tab_foreground  #355374
inactive_tab_background  #dbd5c2
