# extras/kitty/oasis_canyon_light_1.conf
## name: Oasis Canyon Light 1
## author: uhs-robert

# Palette
color0                   #414141
color8                   #493f38

color1                   #ae1111
color9                   #ae1111

color2                   #376033
color10                  #33612d

color3                   #5e581f
color11                  #804913

color4                   #13589d
color12                  #225d76

color5                   #7322d3
color13                  #7222d4

color6                   #305f5a
color14                  #305f57

color7                   #4c4010
color15                  #484026

# Core
foreground               #1a150e
background               #f4e3d5

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #945317
cursor_text_color        #f4e3d5

# Borders (panes)
active_border_color      #6b4119
inactive_border_color    #eed3bd

# Tabs
active_tab_foreground    #f4e3d5
active_tab_background    #81460c
inactive_tab_foreground  #81460c
inactive_tab_background  #eed3bd
