# extras/kitty/oasis_midnight_light_1.conf
## name: Oasis Midnight Light 1
## author: uhs-robert

# Palette
color0                   #464646
color8                   #4e443c

color1                   #b81212
color9                   #b81212

color2                   #3a6636
color10                  #366730

color3                   #645d21
color11                  #884e14

color4                   #155da6
color12                  #24637d

color5                   #7a26dc
color13                  #7927dc

color6                   #33645f
color14                  #33655d

color7                   #484822
color15                  #48480f

# Core
foreground               #181811
background               #eceff4

# Selection
selection_background     #c5cede
selection_foreground     #424221

# Cursor
cursor                   #75691b
cursor_text_color        #eceff4

# Borders (panes)
active_border_color      #65613c
inactive_border_color    #dde3ec

# Tabs
active_tab_foreground    #eceff4
active_tab_background    #696224
inactive_tab_foreground  #696224
inactive_tab_background  #dde3ec
