# extras/kitty/oasis_twilight_light_1.conf
## name: Oasis Twilight Light 1
## author: uhs-robert

# Palette
color0                   #4a4a4a
color8                   #524840

color1                   #c01313
color9                   #c01313

color2                   #3c6a38
color10                  #386b32

color3                   #686123
color11                  #8d5115

color4                   #1561ad
color12                  #256782

color5                   #7e2edd
color13                  #7e2fdd

color6                   #356863
color14                  #356960

color7                   #564912
color15                  #52492c

# Core
foreground               #1e181f
background               #f8f4fb

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #a25b1a
cursor_text_color        #f8f4fb

# Borders (panes)
active_border_color      #794bb6
inactive_border_color    #ede3f5

# Tabs
active_tab_foreground    #f8f4fb
active_tab_background    #7f270d
inactive_tab_foreground  #7f270d
inactive_tab_background  #ede3f5
