# extras/kitty/oasis_mirage_light_1.conf
## name: Oasis Mirage Light 1
## author: uhs-robert

# Palette
color0                   #4b4b4b
color8                   #544941

color1                   #c21313
color9                   #c21414

color2                   #3d6c39
color10                  #396d33

color3                   #696323
color11                  #8f5215

color4                   #1662af
color12                  #266884

color5                   #8030de
color13                  #7f31de

color6                   #366a64
color14                  #356a62

color7                   #584a13
color15                  #534b2c

# Core
foreground               #161d1d
background               #effaf8

# Selection
selection_background     #9fe0d7
selection_foreground     #0f4c44

# Cursor
cursor                   #3b786f
cursor_text_color        #effaf8

# Borders (panes)
active_border_color      #426c68
inactive_border_color    #def5f0

# Tabs
active_tab_foreground    #effaf8
active_tab_background    #2c615a
inactive_tab_foreground  #2c615a
inactive_tab_background  #def5f0
