# extras/kitty/oasis_dune_light_1.conf
## name: Oasis Dune Light 1
## author: uhs-robert

# Palette
color0                   #4a4a4a
color8                   #534940

color1                   #c11313
color9                   #c11313

color2                   #3d6b39
color10                  #396c32

color3                   #696223
color11                  #8e5215

color4                   #1661ae
color12                  #266883

color5                   #7f30de
color13                  #7e30dd

color6                   #366964
color14                  #356961

color7                   #574a13
color15                  #534a2c

# Core
foreground               #1c1b18
background               #fcf6ee

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #7a6e1d
cursor_text_color        #fcf6ee

# Borders (panes)
active_border_color      #58563c
inactive_border_color    #f7e8d4

# Tabs
active_tab_foreground    #fcf6ee
active_tab_background    #686224
inactive_tab_foreground  #686224
inactive_tab_background  #f7e8d4
