# extras/kitty/oasis_rose_light_1.conf
## name: Oasis Rose Light 1
## author: uhs-robert

# Palette
color0                   #474747
color8                   #50453d

color1                   #bb1313
color9                   #bb1313

color2                   #3b6837
color10                  #376831

color3                   #655f22
color11                  #8a4f14

color4                   #155ea9
color12                  #24647f

color5                   #7b29dd
color13                  #7b2adc

color6                   #39665a
color14                  #376659

color7                   #494922
color15                  #4a4a10

# Core
foreground               #181811
background               #faeef5

# Selection
selection_background     #ecbfd9
selection_foreground     #434322

# Cursor
cursor                   #b3406e
cursor_text_color        #faeef5

# Borders (panes)
active_border_color      #8b4e66
inactive_border_color    #f5dceb

# Tabs
active_tab_foreground    #faeef5
active_tab_background    #6b213e
inactive_tab_foreground  #6b213e
inactive_tab_background  #f5dceb
