# extras/kitty/oasis_luna_light_1.conf
## name: Oasis Luna Light 1
## author: uhs-robert

# Palette
color0                   #494949
color8                   #51473f

color1                   #be1313
color9                   #be1313

color2                   #3c6938
color10                  #386a31

color3                   #676022
color11                  #8c5015

color4                   #1560ab
color12                  #256681

color5                   #7d2cdd
color13                  #7d2ddd

color6                   #3a675b
color14                  #38685b

color7                   #4b4b23
color15                  #4b4b10

# Core
foreground               #191911
background               #f3f3fc

# Selection
selection_background     #c2c2f0
selection_foreground     #454523

# Cursor
cursor                   #766c2f
cursor_text_color        #f3f3fc

# Borders (panes)
active_border_color      #5858b5
inactive_border_color    #e1e1f7

# Tabs
active_tab_foreground    #f3f3fc
active_tab_background    #786e14
inactive_tab_foreground  #786e14
inactive_tab_background  #e1e1f7
