# extras/alacritty/themes/light/4/oasis_starlight_light_4.toml
## name: Oasis Starlight Light 4
## author: uhs-robert

[colors.primary]
background = '#f0ece0'
foreground = '#181611'

[colors.selection]
background = '#e1d9c1'
text = '#181611'

[colors.cursor]
cursor = '#1569b2'
text = '#f0ece0'

[colors.vi_mode_cursor]
cursor = '#864c14'
text = '#f0ece0'

[colors.normal]
black   = '#444444'
red     = '#b51212'
green   = '#396435'
yellow  = '#625c21'
blue    = '#145ba2'
magenta = '#7824da'
cyan    = '#33635d'
white   = '#504311'

[colors.bright]
black   = '#4c423c'
red     = '#b51212'
green   = '#35652f'
yellow  = '#864c14'
blue    = '#23617a'
magenta = '#7724dc'
cyan    = '#32635b'
white   = '#4c4428'