# extras/alacritty/themes/light/4/oasis_midnight_light_4.toml
## name: Oasis Midnight Light 4
## author: uhs-robert

[colors.primary]
background = '#f2d9b5'
foreground = '#4c443e'

[colors.selection]
background = '#ebc58e'
text = '#4c443e'

[colors.cursor]
cursor = '#5a5216'
text = '#f2d9b5'

[colors.vi_mode_cursor]
cursor = '#784512'
text = '#f2d9b5'

[colors.normal]
black   = '#454545'
red     = '#a31111'
green   = '#335a30'
yellow  = '#58521e'
blue    = '#125292'
magenta = '#6c20c5'
cyan    = '#2e5854'
white   = '#514411'

[colors.bright]
black   = '#4d433c'
red     = '#a31010'
green   = '#305b2a'
yellow  = '#784512'
blue    = '#1f576d'
magenta = '#6b20c6'
cyan    = '#2d5952'
white   = '#4c4529'