# extras/alacritty/themes/light/4/oasis_lagoon_light_4.toml
## name: Oasis Lagoon Light 4
## author: uhs-robert

[colors.primary]
background = '#cfe2f8'
foreground = '#0e131b'

[colors.selection]
background = '#a7caf2'
text = '#0e131b'

[colors.cursor]
cursor = '#1462a5'
text = '#cfe2f8'

[colors.vi_mode_cursor]
cursor = '#7b4612'
text = '#cfe2f8'

[colors.normal]
black   = '#3d3d3d'
red     = '#a81111'
green   = '#345c31'
yellow  = '#5a541e'
blue    = '#125496'
magenta = '#6f21c9'
cyan    = '#2f5b56'
white   = '#483c0f'

[colors.bright]
black   = '#443c35'
red     = '#a71010'
green   = '#315d2b'
yellow  = '#7b4612'
blue    = '#205970'
magenta = '#6e21cb'
cyan    = '#2e5b54'
white   = '#443d24'