# extras/alacritty/themes/light/4/oasis_scorpion_light_4.toml
## name: Oasis Scorpion Light 4
## author: uhs-robert

[colors.primary]
background = '#f2c5b5'
foreground = '#4b3831'

[colors.selection]
background = '#eba78e'
text = '#4b3831'

[colors.cursor]
cursor = '#514914'
text = '#f2c5b5'

[colors.vi_mode_cursor]
cursor = '#6c3d10'
text = '#f2c5b5'

[colors.normal]
black   = '#3d3d3d'
red     = '#930f0f'
green   = '#2e512b'
yellow  = '#4f491a'
blue    = '#104a83'
magenta = '#611db1'
cyan    = '#294f4b'
white   = '#473c0f'

[colors.bright]
black   = '#443b35'
red     = '#930e0e'
green   = '#2b5125'
yellow  = '#6c3d10'
blue    = '#1c4e62'
magenta = '#601db2'
cyan    = '#284f49'
white   = '#433c24'