# extras/alacritty/themes/light/4/oasis_sol_light_4.toml
## name: Oasis Sol Light 4
## author: uhs-robert

[colors.primary]
background = '#efb7b7'
foreground = '#181811'

[colors.selection]
background = '#e48585'
text = '#181811'

[colors.cursor]
cursor = '#962024'
text = '#efb7b7'

[colors.vi_mode_cursor]
cursor = '#62380f'
text = '#efb7b7'

[colors.normal]
black   = '#2b2b2b'
red     = '#870e0e'
green   = '#2a4a27'
yellow  = '#484318'
blue    = '#0f4377'
magenta = '#591ba1'
cyan    = '#29483f'
white   = '#2c2c15'

[colors.bright]
black   = '#302a25'
red     = '#870d0d'
green   = '#274a22'
yellow  = '#62380f'
blue    = '#19475a'
magenta = '#581aa3'
cyan    = '#27483f'
white   = '#2c2c09'