# extras/alacritty/themes/light/4/oasis_abyss_light_4.toml
## name: Oasis Abyss Light 4
## author: uhs-robert

[colors.primary]
background = '#d0d0d0'
foreground = '#171412'

[colors.selection]
background = '#b1b1b1'
text = '#171412'

[colors.cursor]
cursor = '#605617'
text = '#d0d0d0'

[colors.vi_mode_cursor]
cursor = '#6d3e10'
text = '#d0d0d0'

[colors.normal]
black   = '#333333'
red     = '#950f0f'
green   = '#2e522b'
yellow  = '#504a1b'
blue    = '#104a84'
magenta = '#621db2'
cyan    = '#29504c'
white   = '#3c320d'

[colors.bright]
black   = '#39322c'
red     = '#950e0e'
green   = '#2b5226'
yellow  = '#6d3e10'
blue    = '#1c4f63'
magenta = '#611db4'
cyan    = '#29504a'
white   = '#38331e'