# extras/alacritty/themes/light/4/oasis_moonlight_light_4.toml
## name: Oasis Moonlight Light 4
## author: uhs-robert

[colors.primary]
background = '#ede5c9'
foreground = '#171412'

[colors.selection]
background = '#e2d5a7'
text = '#171412'

[colors.cursor]
cursor = '#6e631b'
text = '#ede5c9'

[colors.vi_mode_cursor]
cursor = '#804913'
text = '#ede5c9'

[colors.normal]
black   = '#334b6e'
red     = '#ad1212'
green   = '#366033'
yellow  = '#5e571f'
blue    = '#13579b'
magenta = '#7322d0'
cyan    = '#315e59'
white   = '#574912'

[colors.bright]
black   = '#3f4c57'
red     = '#ad1111'
green   = '#33612c'
yellow  = '#804913'
blue    = '#215d75'
magenta = '#7222d2'
cyan    = '#305e57'
white   = '#524a2c'