# extras/alacritty/themes/light/4/oasis_cactus_light_4.toml
## name: Oasis Cactus Light 4
## author: uhs-robert

[colors.primary]
background = '#d2eadb'
foreground = '#121714'

[colors.selection]
background = '#a8d7ba'
text = '#121714'

[colors.cursor]
cursor = '#406c42'
text = '#d2eadb'

[colors.vi_mode_cursor]
cursor = '#7f4813'
text = '#d2eadb'

[colors.normal]
black   = '#404040'
red     = '#ac1111'
green   = '#365f33'
yellow  = '#5d571f'
blue    = '#13579a'
magenta = '#7222cf'
cyan    = '#305d58'
white   = '#4b3f10'

[colors.bright]
black   = '#473e38'
red     = '#ac1111'
green   = '#33602c'
yellow  = '#7f4813'
blue    = '#215c74'
magenta = '#7122d1'
cyan    = '#305e57'
white   = '#464025'