# extras/alacritty/themes/light/4/oasis_scorpion_light_4.toml
## name: Oasis Scorpion Light 4
## author: uhs-robert

[colors.primary]
background = '#f2c5b6'
foreground = '#191210'

[colors.selection]
background = '#e99c82'
text = '#191210'

[colors.cursor]
cursor = '#5e5517'
text = '#f2c5b6'

[colors.vi_mode_cursor]
cursor = '#6c3e10'
text = '#f2c5b6'

[colors.normal]
black   = '#323232'
red     = '#930f0f'
green   = '#2e512b'
yellow  = '#4f4a1a'
blue    = '#104a83'
magenta = '#611db0'
cyan    = '#294f4b'
white   = '#3b320c'

[colors.bright]
black   = '#38312c'
red     = '#930e0e'
green   = '#2b5125'
yellow  = '#6c3e10'
blue    = '#1c4e62'
magenta = '#601db2'
cyan    = '#284f49'
white   = '#37321d'