# extras/alacritty/themes/light/4/oasis_luna_light_4.toml
## name: Oasis Luna Light 4
## author: uhs-robert

[colors.primary]
background = '#d5cef3'
foreground = '#42376c'

[colors.selection]
background = '#b5a9ea'
text = '#42376c'

[colors.cursor]
cursor = '#524c22'
text = '#d5cef3'

[colors.vi_mode_cursor]
cursor = '#6f3f10'
text = '#d5cef3'

[colors.normal]
black   = '#3f3f3f'
red     = '#970f0f'
green   = '#2f532c'
yellow  = '#514c1b'
blue    = '#104c87'
magenta = '#641eb6'
cyan    = '#2a524d'
white   = '#4a3e10'

[colors.bright]
black   = '#463d37'
red     = '#980f0f'
green   = '#2c5427'
yellow  = '#6f3f10'
blue    = '#1d5165'
magenta = '#631eb8'
cyan    = '#2a524c'
white   = '#463f25'