# extras/alacritty/themes/light/4/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors.primary]
background = '#c1daf6'
foreground = '#0c131c'

[colors.selection]
background = '#99c2f0'
text = '#0c131c'

[colors.cursor]
cursor = '#645b18'
text = '#c1daf6'

[colors.vi_mode_cursor]
cursor = '#734211'
text = '#c1daf6'

[colors.normal]
black   = '#383838'
red     = '#9d1010'
green   = '#31572e'
yellow  = '#554f1c'
blue    = '#114f8c'
magenta = '#681fbd'
cyan    = '#2c5550'
white   = '#42370e'

[colors.bright]
black   = '#3e3631'
red     = '#9d0f0f'
green   = '#2e5728'
yellow  = '#734211'
blue    = '#1e5469'
magenta = '#671fbf'
cyan    = '#2b554f'
white   = '#3e3821'