# extras/alacritty/themes/light/4/oasis_midnight_light_4.toml
## name: Oasis Midnight Light 4
## author: uhs-robert

[colors.primary]
background = '#cfd6e2'
foreground = '#171412'

[colors.selection]
background = '#a9b5cb'
text = '#171412'

[colors.cursor]
cursor = '#635918'
text = '#cfd6e2'

[colors.vi_mode_cursor]
cursor = '#724111'
text = '#cfd6e2'

[colors.normal]
black   = '#373737'
red     = '#9b1010'
green   = '#30552d'
yellow  = '#534e1c'
blue    = '#114e8a'
magenta = '#661fba'
cyan    = '#2b544f'
white   = '#40360e'

[colors.bright]
black   = '#3d3530'
red     = '#9b0f0f'
green   = '#2d5628'
yellow  = '#724111'
blue    = '#1d5368'
magenta = '#661ebc'
cyan    = '#2b544e'
white   = '#3c3620'