# extras/alacritty/themes/light/4/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors.primary]
background = '#c4dcf2'
foreground = '#0c131c'

[colors.selection]
background = '#9fc5ea'
text = '#0c131c'

[colors.cursor]
cursor = '#665c19'
text = '#c4dcf2'

[colors.vi_mode_cursor]
cursor = '#754311'
text = '#c4dcf2'

[colors.normal]
black   = '#1f4180'
red     = '#9f1010'
green   = '#32582f'
yellow  = '#56501d'
blue    = '#11508e'
magenta = '#6920c0'
cyan    = '#2d5652'
white   = '#4f4211'

[colors.bright]
black   = '#394450'
red     = '#9f0f0f'
green   = '#2f5929'
yellow  = '#754311'
blue    = '#1e556b'
magenta = '#681fc1'
cyan    = '#2c5650'
white   = '#4a4327'