# extras/alacritty/themes/light/4/oasis_desert_light_4.toml
## name: Oasis Desert Light 4
## author: uhs-robert

[colors.primary]
background = '#f0e8c3'
foreground = '#19150f'

[colors.selection]
background = '#e7da9e'
text = '#19150f'

[colors.cursor]
cursor = '#70651b'
text = '#f0e8c3'

[colors.vi_mode_cursor]
cursor = '#824a13'
text = '#f0e8c3'

[colors.normal]
black   = '#424242'
red     = '#b01212'
green   = '#376134'
yellow  = '#5f5920'
blue    = '#13599d'
magenta = '#7523d4'
cyan    = '#31605b'
white   = '#4d4110'

[colors.bright]
black   = '#494039'
red     = '#b01111'
green   = '#34622d'
yellow  = '#824a13'
blue    = '#225e77'
magenta = '#7322d6'
cyan    = '#316059'
white   = '#494227'