# Oasis Lagoon Light 1 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_lagoon_light_1"

[palettes.oasis_lagoon_light_1]
# Accent
primary       = '#075085'
strong_primary = '#1e75b1'

# ANSI colors (0-7)
black         = '#565656'
red           = '#c41414'
green         = '#3e6d3a'
blue          = '#1663b2'
purple        = '#8233de'
cyan          = '#376b65'
white         = '#655516'

# Bright ANSI colors (8-15)
bright_black  = '#61544a'
bright_red    = '#c41414'
bright_green  = '#3a6e33'
bright_yellow = '#915316'
bright_blue   = '#266a86'
bright_purple = '#8134de'
bright_cyan   = '#366c63'
bright_white  = '#5f5633'
