# Oasis Abyss Light 1 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_abyss_light_1"

[palettes.oasis_abyss_light_1]
# Accent
primary       = '#686224'
strong_primary = '#8c8643'

# ANSI colors (0-7)
black         = '#414141'
red           = '#b01212'
green         = '#376133'
blue          = '#14589e'
purple        = '#7422d5'
cyan          = '#315f5a'
white         = '#4d4110'

# Bright ANSI colors (8-15)
bright_black  = '#494038'
bright_red    = '#b01212'
bright_green  = '#34622e'
bright_yellow = '#814a13'
bright_blue   = '#225e77'
bright_purple = '#7323d5'
bright_cyan   = '#306058'
bright_white  = '#494127'
