# Oasis Midnight Light 1 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_1"

[palettes.oasis_midnight_light_1]
# Accent
primary       = '#686224'
strong_primary = '#8c8643'

# ANSI colors (0-7)
black         = '#464646'
red           = '#b81212'
green         = '#3a6636'
blue          = '#155da6'
purple        = '#7a26dc'
cyan          = '#33645f'
white         = '#524512'

# Bright ANSI colors (8-15)
bright_black  = '#4e443c'
bright_red    = '#b81212'
bright_green  = '#366730'
bright_yellow = '#884e14'
bright_blue   = '#24637d'
bright_purple = '#7927dc'
bright_cyan   = '#33655d'
bright_white  = '#4d4629'
