# extras/termux/oasis_sol_light_1.properties
# name: Oasis Sol Light 1
# author: uhs-robert

background: #f5d5d5
foreground: #1d0f0c

# Normal colors
color0:  #3b3b3b
color1:  #a31010
color2:  #335a30
color3:  #58521d
color4:  #125293
color5:  #6c20c5
color6:  #2d5954
color7:  #453a0f

# Bright colors
color8: #423933
color9: #a31010
color10: #305b2a
color11: #784512
color12: #20576e
color13: #6b20c6
color14: #2d5952
color15: #413b23

# Extended colors
color16: #8c5421
color17: #6b4b0c