# extras/termux/oasis_sol_light_1.properties
# name: Oasis Sol Light 1
# author: uhs-robert

background: #f7f3f3
foreground: #271410

# Normal colors
color0:  #535353
color1:  #be1313
color2:  #3c6a38
color3:  #676022
color4:  #1560ab
color5:  #7d2cdd
color6:  #356862
color7:  #615215

# Bright colors
color8: #5d5148
color9: #be1313
color10: #386a31
color11: #8c5015
color12: #256681
color13: #7d2ddd
color14: #346860
color15: #5c5231

# Extended colors
color16: #a06125
color17: #7d580e