# extras/termux/oasis_mirage_light_1.properties
# name: Oasis Mirage Light 1
# author: uhs-robert

background: #effaf8
foreground: #161d1d

# Normal colors
color0:  #4b4b4b
color1:  #c21313
color2:  #3d6c39
color3:  #696323
color4:  #1662af
color5:  #8030de
color6:  #366a64
color7:  #584a13

# Bright colors
color8: #544941
color9: #c21414
color10: #396d33
color11: #8f5215
color12: #266884
color13: #7f31de
color14: #356a62
color15: #534b2c

# Extended colors
color16: #a36326
color17: #c1151c