# extras/termux/oasis_sol_light_1.properties
# name: Oasis Sol Light 1
# author: uhs-robert

background: #fbf9f9
foreground: #844437

# Normal colors
color0:  #565656
color1:  #c41414
color2:  #3e6d3a
color3:  #6a6423
color4:  #1663b1
color5:  #8132de
color6:  #376b65
color7:  #655516

# Bright colors
color8: #60544a
color9: #c41414
color10: #3a6e33
color11: #915315
color12: #266985
color13: #8033de
color14: #366b63
color15: #5f5633

# Extended colors
color16: #7b4a1d
color17: #815b0e