# extras/termux/oasis_luna_light_1.properties
# name: Oasis Luna Light 1
# author: uhs-robert

background: #f3f3fc
foreground: #191911

# Normal colors
color0:  #494949
color1:  #be1313
color2:  #3c6938
color3:  #676022
color4:  #1560ab
color5:  #7d2cdd
color6:  #3a675b
color7:  #4b4b23

# Bright colors
color8: #51473f
color9: #be1313
color10: #386a31
color11: #8c5015
color12: #256681
color13: #7d2ddd
color14: #38685b
color15: #4b4b10

# Extended colors
color16: #a06125
color17: #bd151b