# extras/termux/oasis_rose_light_1.properties
# name: Oasis Rose Light 1
# author: uhs-robert

background: #eaf1ea
foreground: #714251

# Normal colors
color0:  #505050
color1:  #b91212
color2:  #3a6636
color3:  #645d21
color4:  #155da6
color5:  #7a27dc
color6:  #33655f
color7:  #5e4f14

# Bright colors
color8: #5a4e45
color9: #b91313
color10: #366730
color11: #884e14
color12: #24637d
color13: #7928dc
color14: #33655d
color15: #595030

# Extended colors
color16: #73461b
color17: #79560d