# extras/termux/oasis_rose_light_1.properties
# name: Oasis Rose Light 1
# author: uhs-robert

background: #faeef5
foreground: #201317

# Normal colors
color0:  #474747
color1:  #bb1313
color2:  #3b6837
color3:  #655f22
color4:  #155ea9
color5:  #7b29dd
color6:  #346660
color7:  #534612

# Bright colors
color8: #50453d
color9: #bb1313
color10: #376831
color11: #8a4f14
color12: #24647f
color13: #7b2adc
color14: #33665e
color15: #4f472a

# Extended colors
color16: #9e6025
color17: #ba141b