# extras/termux/oasis_starlight_light_1.properties
# name: Oasis Starlight Light 1
# author: uhs-robert

background: #ffffff
foreground: #24211a

# Normal colors
color0:  #4f4f4f
color1:  #ca1414
color2:  #40703b
color3:  #6e6725
color4:  #1766b7
color5:  #8538df
color6:  #386e68
color7:  #5c4e14

# Bright colors
color8: #584d44
color9: #ca1414
color10: #3c7135
color11: #955616
color12: #276c89
color13: #8439df
color14: #386f66
color15: #574f2f

# Extended colors
color16: #aa6728
color17: #c9161d