# vim:set ft=tmux:
## name: Oasis Canyon Light 2
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#a36021"
set -ogq @thm_primary "#78410a"
set -ogq @thm_light_primary "#6f4808"
set -ogq @thm_secondary "#7e0404"
set -ogq @thm_prefix "#1c6c8d"
set -ogq @thm_fg "#1b150e"

# Surfaces and overlays
set -ogq @thm_core "#f8f0e7"
set -ogq @thm_mantle "#f5e9db"
set -ogq @thm_surface "#eedac3"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#bb1313"
set -ogq @thm_orange "#8a4f14"
set -ogq @thm_yellow "#655f22"
set -ogq @thm_green "#a31218"
set -ogq @thm_teal "#34665f"
set -ogq @thm_blue "#155ea9"
set -ogq @thm_indigo "#7c29dc"
