# Oasis Desert Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_desert_light_5"

[palettes.oasis_desert_light_5]
# Accent
primary       = '#8a0000'
strong_primary = '#6a662f'

# ANSI colors (0-7)
black         = '#444444'
red           = '#a11010'
green         = '#32592f'
blue          = '#11518f'
purple        = '#6b1fc2'
cyan          = '#2d5752'
white         = '#4f4311'

# Bright ANSI colors (8-15)
bright_black  = '#4b423a'
bright_red    = '#a11010'
bright_green  = '#2f5929'
bright_yellow = '#764311'
bright_blue   = '#1f566c'
bright_purple = '#6a20c2'
bright_cyan   = '#2c5750'
bright_white  = '#4b4428'
