# Oasis Desert Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_desert_light_5"

[palettes.oasis_desert_light_5]
# Accent
primary       = '#630000'
strong_primary = '#736e33'

# ANSI colors (0-7)
black         = '#4a4a4a'
red           = '#ae1111'
green         = '#366033'
blue          = '#13579b'
purple        = '#7322d1'
cyan          = '#305e59'
white         = '#574a12'

# Bright ANSI colors (8-15)
bright_black  = '#534940'
bright_red    = '#ae1111'
bright_green  = '#33612d'
bright_yellow = '#804913'
bright_blue   = '#225d75'
bright_purple = '#7222d2'
bright_cyan   = '#305f57'
bright_white  = '#524a2c'
