# Oasis Sol Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_sol_light_5"

[palettes.oasis_sol_light_5]
# Accent
primary       = '#800000'
strong_primary = '#7f1a1a'

# ANSI colors (0-7)
black         = '#3a3a3a'
red           = '#8f0e0e'
green         = '#2c4e29'
blue          = '#0f477f'
purple        = '#5e1cab'
cyan          = '#274d48'
white         = '#443a0e'

# Bright ANSI colors (8-15)
bright_black  = '#413932'
bright_red    = '#8f0e0e'
bright_green  = '#2a4f25'
bright_yellow = '#683b0f'
bright_blue   = '#1b4b5f'
bright_purple = '#5d1cac'
bright_cyan   = '#274d47'
bright_white  = '#413a22'
