# Oasis Rose Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_rose_light_5"

[palettes.oasis_rose_light_5]
# Accent
primary       = '#782107'
strong_primary = '#753924'

# ANSI colors (0-7)
black         = '#454545'
red           = '#a41010'
green         = '#335b30'
blue          = '#125393'
purple        = '#6d20c6'
cyan          = '#2e5954'
white         = '#524511'

# Bright ANSI colors (8-15)
bright_black  = '#4d443c'
bright_red    = '#a41010'
bright_green  = '#305b2b'
bright_yellow = '#794512'
bright_blue   = '#20576e'
bright_purple = '#6c21c6'
bright_cyan   = '#2d5952'
bright_white  = '#4d4529'
