# Oasis Rose Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_rose_light_5"

[palettes.oasis_rose_light_5]
# Accent
primary       = '#491a2a'
strong_primary = '#772f47'

# ANSI colors (0-7)
black         = '#303030'
red           = '#8f0e0e'
green         = '#2c4e29'
blue          = '#0f477f'
purple        = '#5e1cab'
cyan          = '#274d48'
white         = '#382f0c'

# Bright ANSI colors (8-15)
bright_black  = '#352e29'
bright_red    = '#8f0e0e'
bright_green  = '#2a4f25'
bright_yellow = '#683b0f'
bright_blue   = '#1b4b5f'
bright_purple = '#5d1cac'
bright_cyan   = '#274d47'
bright_white  = '#352f1c'
