# Oasis Dune Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_dune_light_5"

[palettes.oasis_dune_light_5]
# Accent
primary       = '#4c4718'
strong_primary = '#736533'

# ANSI colors (0-7)
black         = '#454545'
red           = '#a31010'
green         = '#335a2f'
blue          = '#125292'
purple        = '#6c20c4'
cyan          = '#2d5853'
white         = '#514411'

# Bright ANSI colors (8-15)
bright_black  = '#4d433b'
bright_red    = '#a31010'
bright_green  = '#305b2a'
bright_yellow = '#784512'
bright_blue   = '#20576e'
bright_purple = '#6b20c5'
bright_cyan   = '#2d5852'
bright_white  = '#4d4529'
