# Oasis Abyss Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_abyss_light_5"

[palettes.oasis_abyss_light_5]
# Accent
primary       = '#4c4718'
strong_primary = '#736e33'

# ANSI colors (0-7)
black         = '#414141'
red           = '#9c0f0f'
green         = '#31562d'
blue          = '#114e8b'
purple        = '#671ebb'
cyan          = '#2b544f'
white         = '#4c4010'

# Bright ANSI colors (8-15)
bright_black  = '#484038'
bright_red    = '#9c0f0f'
bright_green  = '#2e5628'
bright_yellow = '#724111'
bright_blue   = '#1e5369'
bright_purple = '#661fbc'
bright_cyan   = '#2b544e'
bright_white  = '#484127'
