# Oasis Midnight Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_5"

[palettes.oasis_midnight_light_5]
# Accent
primary       = '#71670f'
strong_primary = '#6a662f'

# ANSI colors (0-7)
black         = '#404040'
red           = '#9a0f0f'
green         = '#30552d'
blue          = '#114d89'
purple        = '#661eb9'
cyan          = '#2b534e'
white         = '#4b4010'

# Bright ANSI colors (8-15)
bright_black  = '#473f37'
bright_red    = '#9a0f0f'
bright_green  = '#2d5528'
bright_yellow = '#714011'
bright_blue   = '#1e5267'
bright_purple = '#651fba'
bright_cyan   = '#2a534d'
bright_white  = '#474026'
