# Oasis Lagoon Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_lagoon_light_5"

[palettes.oasis_lagoon_light_5]
# Accent
primary       = '#024a7e'
strong_primary = '#015a98'

# ANSI colors (0-7)
black         = '#404040'
red           = '#990f0f'
green         = '#2f542c'
blue          = '#104d88'
purple        = '#651eb8'
cyan          = '#2a524e'
white         = '#4b3f10'

# Bright ANSI colors (8-15)
bright_black  = '#463e37'
bright_red    = '#990f0f'
bright_green  = '#2d5527'
bright_yellow = '#704010'
bright_blue   = '#1d5166'
bright_purple = '#641eb8'
bright_cyan   = '#2a534c'
bright_white  = '#463f26'
