# Oasis Night Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_night_light_5"

[palettes.oasis_night_light_5]
# Accent
primary       = '#1e3146'
strong_primary = '#315275'

# ANSI colors (0-7)
black         = '#1e3d78'
red           = '#980f0f'
green         = '#2f542c'
blue          = '#104c87'
purple        = '#651eb7'
cyan          = '#2a524d'
white         = '#4a3e0f'

# Bright ANSI colors (8-15)
bright_black  = '#35404c'
bright_red    = '#980f0f'
bright_green  = '#2c5427'
bright_yellow = '#6f3f10'
bright_blue   = '#1d5166'
bright_purple = '#641eb7'
bright_cyan   = '#2a524c'
bright_white  = '#463f25'
