# Oasis Midnight Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_5"

[palettes.oasis_midnight_light_5]
# Accent
primary       = '#4c4718'
strong_primary = '#736e33'

# ANSI colors (0-7)
black         = '#393939'
red           = '#8d0e0e'
green         = '#2b4d29'
blue          = '#0f467d'
purple        = '#5d1ba9'
cyan          = '#274b47'
white         = '#43380e'

# Bright ANSI colors (8-15)
bright_black  = '#3f3831'
bright_red    = '#8d0e0e'
bright_green  = '#294e24'
bright_yellow = '#663a0f'
bright_blue   = '#1b4a5e'
bright_purple = '#5c1ca9'
bright_cyan   = '#264c46'
bright_white  = '#3f3922'
