# Oasis Cactus Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_cactus_light_5"

[palettes.oasis_cactus_light_5]
# Accent
primary       = '#234124'
strong_primary = '#3a6c3c'

# ANSI colors (0-7)
black         = '#494949'
red           = '#ab1111'
green         = '#365f32'
blue          = '#135699'
purple        = '#7122ce'
cyan          = '#305d58'
white         = '#564812'

# Bright ANSI colors (8-15)
bright_black  = '#51483f'
bright_red    = '#ab1111'
bright_green  = '#325f2c'
bright_yellow = '#7e4812'
bright_blue   = '#215c73'
bright_purple = '#7122cf'
bright_cyan   = '#2f5d56'
bright_white  = '#51492b'
