# Oasis Midnight Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_5"

[palettes.oasis_midnight_light_5]
# Accent
primary       = '#4c4718'
strong_primary = '#736e33'

# ANSI colors (0-7)
black         = '#313131'
red           = '#910e0e'
green         = '#2d4f2a'
blue          = '#104880'
purple        = '#601cae'
cyan          = '#284e49'
white         = '#39300c'

# Bright ANSI colors (8-15)
bright_black  = '#362f2a'
bright_red    = '#910e0e'
bright_green  = '#2a5025'
bright_yellow = '#6a3c0f'
bright_blue   = '#1c4d61'
bright_purple = '#5f1dae'
bright_cyan   = '#284e48'
bright_white  = '#36301d'
