# Oasis Abyss Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_abyss_light_5"

[palettes.oasis_abyss_light_5]
# Accent
primary       = '#71670f'
strong_primary = '#6a662f'

# ANSI colors (0-7)
black         = '#424242'
red           = '#9f0f0f'
green         = '#31572e'
blue          = '#11508d'
purple        = '#691fbe'
cyan          = '#2c5651'
white         = '#4e4210'

# Bright ANSI colors (8-15)
bright_black  = '#4a4139'
bright_red    = '#9e0f0f'
bright_green  = '#2e5829'
bright_yellow = '#744211'
bright_blue   = '#1e546a'
bright_purple = '#681fbf'
bright_cyan   = '#2b564f'
bright_white  = '#4a4227'
