# Oasis Scorpion Light 5 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_scorpion_light_5"

[palettes.oasis_scorpion_light_5]
# Accent
primary       = '#58500b'
strong_primary = '#7a742c'

# ANSI colors (0-7)
black         = '#2c2c2c'
red           = '#880d0d'
green         = '#2a4a27'
blue          = '#0f4478'
purple        = '#5a1ba3'
cyan          = '#254945'
white         = '#332b0b'

# Bright ANSI colors (8-15)
bright_black  = '#302b25'
bright_red    = '#880d0d'
bright_green  = '#284b23'
bright_yellow = '#63390f'
bright_blue   = '#1a485b'
bright_purple = '#591ba4'
bright_cyan   = '#254943'
bright_white  = '#302b1a'
