# extras/foot/oasis_sol_light_3.ini
# name: Oasis Sol Light 3
# author: uhs-robert

[colors]
cursor=efbcbc 9a2125
foreground=1d0f0c
background=efbcbc

selection-foreground=1d0f0c
selection-background=e69797

search-box-no-match=4e0e0e e19d9d
search-box-match=0d311f 7ad1a7

urls=152932
jump-labels=0d311f 7ad1a7

regular0=2d2d2d
regular1=8b0e0e
regular2=2b4c28
regular3=4a4519
regular4=0f457b
regular5=5c1ba7
regular6=264b47
regular7=362d0b

bright0=332c28
bright1=8b0e0e
bright2=294d23
bright3=653a0f
bright4=1a4a5c
bright5=5b1ca8
bright6=264b45
bright7=322d1b
16=79491d
17=5b400a