# extras/foot/oasis_desert_dark.ini
# name: Oasis Desert Dark
# author: uhs-robert

[colors]
cursor=262626 F0E68C
foreground=F7EDE1
background=262626

selection-foreground=F7EDE1
selection-background=433F38

search-box-no-match=F7EDE1 666666
search-box-match=262626 A1C254

urls=87CEEB
jump-labels=262626 A1C254

regular0=262626
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=68C0B6
regular7=FFF7D7

bright0=77725F
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8FD1C7
bright7=F7F4E9
16=FFA34D
17=FF7979