# extras/foot/oasis_luna_dark.ini
# name: Oasis Luna Dark
# author: uhs-robert

[colors]
cursor=171345 F0E68C
foreground=EEEAFE
background=171345

selection-foreground=EEEAFE
selection-background=433F38

search-box-no-match=EEEAFE 666666
search-box-match=171345 A1C254

urls=87CEEB
jump-labels=171345 A1C254

regular0=171345
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=68C0B6
regular7=FFF7D7

bright0=8A82B3
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8FD1C7
bright7=F7F4E9
16=FF9633
17=FF7979