# extras/foot/oasis_night_dark.ini
# name: Oasis Night Dark
# author: uhs-robert

[colors]
cursor=050F23 F0E68C
foreground=E8F1FF
background=050F23

selection-foreground=E8F1FF
selection-background=24364D

search-box-no-match=E8F1FF 666666
search-box-match=050F23 CDC673

urls=87CEEB
jump-labels=050F23 CDC673

regular0=050F23
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=68C0B6
regular7=FFF7D7

bright0=536B83
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8FD1C7
bright7=F7F4E9
16=FF9633
17=FF7979