# extras/wezterm/oasis_starlight_light_1.toml
## name: Oasis Starlight Light 1
## author: uhs-robert

[colors]
foreground = "#1e1e14"
background= "#faf9f5"
cursor_bg = "#796f31"
cursor_border = "#796f31"
cursor_fg= "#faf9f5"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#416891"
compose_cursor= "#a46326"
scrollbar_thumb= "#e6e1cc"
visual_bell= "#f2f0e6"

ansi = [
  '#4c4c4c',
  '#c31414',
  '#3e6d39',
  '#6a6323',
  '#1663b1',
  '#8132de',
  '#3c6a5e',
  '#4e4e24',
]

brights = [
  '#554a41',
  '#c31414',
  '#3a6e33',
  '#905315',
  '#266985',
  '#8033de',
  '#3a6b5e',
  '#4e4e11',
]

[colors.indexed]
16 = '#a46326'
17 = '#c3151c'

[colors.tab_bar]
background = '#f2f0e6'
inactive_tab_edge = '#f5f3eb'

[colors.tab_bar.active_tab]
bg_color = '#064687'
fg_color = '#faf9f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e6e1cc'
fg_color = '#064687'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e6e1cc'
fg_color = '#786e14'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#786e14'
fg_color = '#faf9f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ab0707'
fg_color = '#faf9f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 1'