# extras/wezterm/oasis_moonlight_light_1.toml
## name: Oasis Moonlight Light 1
## author: uhs-robert

[colors]
foreground = "#52422d"
background= "#e0dbcc"
cursor_bg = "#784313"
cursor_border = "#784313"
cursor_fg= "#e0dbcc"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#354658"
compose_cursor= "#623b17"
scrollbar_thumb= "#cfc7af"
visual_bell= "#dbd5c2"

ansi = [
  '#5e3c33',
  '#a21010',
  '#33592f',
  '#57511d',
  '#125191',
  '#6b1fc4',
  '#2d5753',
  '#504311',
]

brights = [
  '#593f30',
  '#a21010',
  '#2f5a2a',
  '#764412',
  '#1f566d',
  '#6a20c4',
  '#2c5851',
  '#4c4428',
]

[colors.indexed]
16 = '#623b17'
17 = '#a11217'

[colors.tab_bar]
background = '#dbd5c2'
inactive_tab_edge = '#d5ceb9'

[colors.tab_bar.active_tab]
bg_color = '#355374'
fg_color = '#e0dbcc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#cfc7af'
fg_color = '#355374'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#cfc7af'
fg_color = '#988c1a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#988c1a'
fg_color = '#e0dbcc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ab0707'
fg_color = '#e0dbcc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Moonlight Light 1'