# extras/wezterm/oasis_lagoon_light_1.toml
## name: Oasis Lagoon Light 1
## author: uhs-robert

[colors]
foreground = "#161e2a"
background= "#f9fafb"
cursor_bg = "#1872c0"
cursor_border = "#1872c0"
cursor_fg= "#f9fafb"
selection_bg= "#9fcae0"
selection_fg= "#0f384c"
split= "#245a81"
compose_cursor= "#a66427"
scrollbar_thumb= "#dde3e9"
visual_bell= "#f0f2f5"

ansi = [
  '#565656',
  '#c41414',
  '#3e6d3a',
  '#6b6424',
  '#1663b2',
  '#8233de',
  '#376b65',
  '#655516',
]

brights = [
  '#61544a',
  '#c41414',
  '#3a6e33',
  '#915316',
  '#266a86',
  '#8134de',
  '#366c63',
  '#5f5633',
]

[colors.indexed]
16 = '#a66427'
17 = '#c4151c'

[colors.tab_bar]
background = '#f0f2f5'
inactive_tab_edge = '#e7ebef'

[colors.tab_bar.active_tab]
bg_color = '#075085'
fg_color = '#f9fafb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#dde3e9'
fg_color = '#075085'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#dde3e9'
fg_color = '#81460c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#81460c'
fg_color = '#f9fafb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ab0707'
fg_color = '#f9fafb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Lagoon Light 1'