# extras/wezterm/oasis_sol_light_1.toml
## name: Oasis Sol Light 1
## author: uhs-robert

[colors]
foreground = "#271410"
background= "#f7f3f3"
cursor_bg = "#cc2d31"
cursor_border = "#cc2d31"
cursor_fg= "#f7f3f3"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#9d2525"
compose_cursor= "#a06125"
scrollbar_thumb= "#e4d7d7"
visual_bell= "#f1eaea"

ansi = [
  '#535353',
  '#be1313',
  '#3c6a38',
  '#676022',
  '#1560ab',
  '#7d2cdd',
  '#356862',
  '#615215',
]

brights = [
  '#5d5148',
  '#be1313',
  '#386a31',
  '#8c5015',
  '#256681',
  '#7d2ddd',
  '#346860',
  '#5c5231',
]

[colors.indexed]
16 = '#a06125'
17 = '#7d580e'

[colors.tab_bar]
background = '#f1eaea'
inactive_tab_edge = '#ebe0e0'

[colors.tab_bar.active_tab]
bg_color = '#870606'
fg_color = '#f7f3f3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e4d7d7'
fg_color = '#870606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e4d7d7'
fg_color = '#81460c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#81460c'
fg_color = '#f7f3f3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#388032'
fg_color = '#f7f3f3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 1'