# extras/wezterm/oasis_midnight_light_1.toml
## name: Oasis Midnight Light 1
## author: uhs-robert

[colors]
foreground = "#161412"
background= "#eceff4"
cursor_bg = "#75691b"
cursor_border = "#75691b"
cursor_fg= "#eceff4"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#64613b"
compose_cursor= "#9c5e24"
scrollbar_thumb= "#c5cede"
visual_bell= "#dde3ec"

ansi = [
  '#464646',
  '#b81212',
  '#3a6636',
  '#645d21',
  '#155da6',
  '#7a26dc',
  '#33645f',
  '#524512',
]

brights = [
  '#4e443c',
  '#b81212',
  '#366730',
  '#884e14',
  '#24637d',
  '#7927dc',
  '#33655d',
  '#4d4629',
]

[colors.indexed]
16 = '#9c5e24'
17 = '#b7141a'

[colors.tab_bar]
background = '#dde3ec'
inactive_tab_edge = '#e2e7ee'

[colors.tab_bar.active_tab]
bg_color = '#686224'
fg_color = '#eceff4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c5cede'
fg_color = '#686224'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c5cede'
fg_color = '#870606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#870606'
fg_color = '#eceff4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#388032'
fg_color = '#eceff4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Light 1'