# extras/wezterm/oasis_sol_light_1.toml
## name: Oasis Sol Light 1
## author: uhs-robert

[colors]
foreground = "#1d0f0c"
background= "#f8dddd"
cursor_bg = "#b9292c"
cursor_border = "#b9292c"
cursor_fg= "#f8dddd"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#7b4f23"
compose_cursor= "#925822"
scrollbar_thumb= "#eeaaaa"
visual_bell= "#f4caca"

ansi = [
  '#3f3f3f',
  '#ab1111',
  '#365f32',
  '#5c561f',
  '#13569a',
  '#7121cf',
  '#2f5d58',
  '#4a3e10',
]

brights = [
  '#473d36',
  '#ab1111',
  '#325f2c',
  '#7e4813',
  '#215b74',
  '#7022d0',
  '#2f5d56',
  '#463f25',
]

[colors.indexed]
16 = '#925822'
17 = '#704f0c'

[colors.tab_bar]
background = '#f4caca'
inactive_tab_edge = '#f5d0d0'

[colors.tab_bar.active_tab]
bg_color = '#870606'
fg_color = '#f8dddd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eeaaaa'
fg_color = '#870606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eeaaaa'
fg_color = '#81460c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#81460c'
fg_color = '#f8dddd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#388032'
fg_color = '#f8dddd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 1'