# extras/wezterm/oasis_canyon_light_1.toml
## name: Oasis Canyon Light 1
## author: uhs-robert

[colors]
foreground = "#1a150e"
background= "#f4e3d5"
cursor_bg = "#945317"
cursor_border = "#945317"
cursor_fg= "#f4e3d5"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#6b4119"
compose_cursor= "#7d642b"
scrollbar_thumb= "#eacbb1"
visual_bell= "#eed3bd"

ansi = [
  '#414141',
  '#ae1111',
  '#376033',
  '#5e581f',
  '#13589d',
  '#7322d3',
  '#305f5a',
  '#4c4010',
]

brights = [
  '#493f38',
  '#ae1111',
  '#33612d',
  '#804913',
  '#225d76',
  '#7222d4',
  '#305f57',
  '#484026',
]

[colors.indexed]
16 = '#7d642b'
17 = '#ad1319'

[colors.tab_bar]
background = '#eed3bd'
inactive_tab_edge = '#f1dbc9'

[colors.tab_bar.active_tab]
bg_color = '#81460c'
fg_color = '#f4e3d5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eacbb1'
fg_color = '#81460c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eacbb1'
fg_color = '#870606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#870606'
fg_color = '#f4e3d5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1f7294'
fg_color = '#f4e3d5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 1'