# extras/wezterm/oasis_luna_light_1.toml
## name: Oasis Luna Light 1
## author: uhs-robert

[colors]
foreground = "#1f1a33"
background= "#f9f9fb"
cursor_bg = "#7c6f1d"
cursor_border = "#7c6f1d"
cursor_fg= "#f9f9fb"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#4a4aa8"
compose_cursor= "#a56427"
scrollbar_thumb= "#dddde9"
visual_bell= "#f0f0f5"

ansi = [
  '#565656',
  '#c41414',
  '#3e6d39',
  '#6a6323',
  '#1663b1',
  '#8132de',
  '#376b65',
  '#655516',
]

brights = [
  '#60534a',
  '#c41414',
  '#3a6e33',
  '#915315',
  '#266985',
  '#8033de',
  '#366b63',
  '#5f5633',
]

[colors.indexed]
16 = '#a56427'
17 = '#c3151c'

[colors.tab_bar]
background = '#f0f0f5'
inactive_tab_edge = '#e7e7ef'

[colors.tab_bar.active_tab]
bg_color = '#786e14'
fg_color = '#f9f9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#dddde9'
fg_color = '#786e14'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#dddde9'
fg_color = '#1c1c70'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1c1c70'
fg_color = '#f9f9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1b7b98'
fg_color = '#f9f9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 1'