# extras/wezterm/oasis_dune_light_1.toml
## name: Oasis Dune Light 1
## author: uhs-robert

[colors]
foreground = "#1c1c19"
background= "#f9f7f5"
cursor_bg = "#7b6e1d"
cursor_border = "#7b6e1d"
cursor_fg= "#f9f7f5"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#58563c"
compose_cursor= "#a36326"
scrollbar_thumb= "#e8e0d8"
visual_bell= "#f3efeb"

ansi = [
  '#555555',
  '#c21313',
  '#3d6c39',
  '#696323',
  '#1662af',
  '#8030de',
  '#366a64',
  '#635415',
]

brights = [
  '#5f5349',
  '#c21313',
  '#396d33',
  '#8f5215',
  '#266884',
  '#7f31de',
  '#356a62',
  '#5e5532',
]

[colors.indexed]
16 = '#a36326'
17 = '#c1151c'

[colors.tab_bar]
background = '#f3efeb'
inactive_tab_edge = '#eee8e2'

[colors.tab_bar.active_tab]
bg_color = '#686224'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8e0d8'
fg_color = '#686224'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8e0d8'
fg_color = '#2b6159'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2b6159'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#5107ab'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 1'