# extras/wezterm/oasis_canyon_light_1.toml
## name: Oasis Canyon Light 1
## author: uhs-robert

[colors]
foreground = "#211b12"
background= "#f9f7f5"
cursor_bg = "#a35c1a"
cursor_border = "#a35c1a"
cursor_fg= "#f9f7f5"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#7a491c"
compose_cursor= "#8a6e2f"
scrollbar_thumb= "#e8e0d8"
visual_bell= "#f3efeb"

ansi = [
  '#555555',
  '#c21313',
  '#3d6c39',
  '#696323',
  '#1662af',
  '#8030de',
  '#366a64',
  '#635415',
]

brights = [
  '#5f5349',
  '#c21313',
  '#396d33',
  '#8f5215',
  '#266884',
  '#7f31de',
  '#356a62',
  '#5e5532',
]

[colors.indexed]
16 = '#8a6e2f'
17 = '#c1151c'

[colors.tab_bar]
background = '#f3efeb'
inactive_tab_edge = '#eee8e2'

[colors.tab_bar.active_tab]
bg_color = '#81460c'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8e0d8'
fg_color = '#81460c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8e0d8'
fg_color = '#870606'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#870606'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1f7294'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 1'