# extras/wezterm/oasis_luna_light_1.toml
## name: Oasis Luna Light 1
## author: uhs-robert

[colors]
foreground = "#1a162b"
background= "#f3f3fc"
cursor_bg = "#786c1c"
cursor_border = "#786c1c"
cursor_fg= "#f3f3fc"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#5858b5"
compose_cursor= "#a06125"
scrollbar_thumb= "#c2c2f0"
visual_bell= "#e1e1f7"

ansi = [
  '#494949',
  '#be1313',
  '#3c6938',
  '#676022',
  '#1560ab',
  '#7d2cdd',
  '#356762',
  '#554812',
]

brights = [
  '#51473f',
  '#be1313',
  '#386a31',
  '#8c5015',
  '#256681',
  '#7d2ddd',
  '#346860',
  '#51482b',
]

[colors.indexed]
16 = '#a06125'
17 = '#bd151b'

[colors.tab_bar]
background = '#e1e1f7'
inactive_tab_edge = '#e7e7f9'

[colors.tab_bar.active_tab]
bg_color = '#786e14'
fg_color = '#f3f3fc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c2c2f0'
fg_color = '#786e14'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c2c2f0'
fg_color = '#1c1c70'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1c1c70'
fg_color = '#f3f3fc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1b7b98'
fg_color = '#f3f3fc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 1'