# extras/wezterm/oasis_luna_light_1.toml
## name: Oasis Luna Light 1
## author: uhs-robert

[colors]
foreground = "#514486"
background= "#eaeaf1"
cursor_bg = "#645a17"
cursor_border = "#645a17"
cursor_fg= "#eaeaf1"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#6630a2"
compose_cursor= "#6f431a"
scrollbar_thumb= "#cecede"
visual_bell= "#e0e0eb"

ansi = [
  '#4d4d4d',
  '#b31212',
  '#386335',
  '#615b20',
  '#145aa2',
  '#7723d9',
  '#32625c',
  '#5b4d14',
]

brights = [
  '#574c43',
  '#b41212',
  '#35642f',
  '#844c14',
  '#23607a',
  '#7623da',
  '#31625a',
  '#564d2e',
]

[colors.indexed]
16 = '#6f431a'
17 = '#b3141a'

[colors.tab_bar]
background = '#e0e0eb'
inactive_tab_edge = '#d7d7e4'

[colors.tab_bar.active_tab]
bg_color = '#908419'
fg_color = '#eaeaf1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#cecede'
fg_color = '#908419'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#cecede'
fg_color = '#5307ab'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5307ab'
fg_color = '#eaeaf1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1b7b98'
fg_color = '#eaeaf1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 1'