# extras/wezterm/oasis_desert_light_1.toml
## name: Oasis Desert Light 1
## author: uhs-robert

[colors]
foreground = "#65543e"
background= "#fbfaf9"
cursor_bg = "#6e631a"
cursor_border = "#6e631a"
cursor_fg= "#fbfaf9"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#a32626"
compose_cursor= "#7c4b1d"
scrollbar_thumb= "#e9e3dd"
visual_bell= "#f5f2f0"

ansi = [
  '#565656',
  '#c51414',
  '#3e6d3a',
  '#6b6424',
  '#1663b2',
  '#8233de',
  '#376b66',
  '#655516',
]

brights = [
  '#61544b',
  '#c51414',
  '#3a6e33',
  '#915316',
  '#266a86',
  '#8134de',
  '#366c63',
  '#605633',
]

[colors.indexed]
16 = '#7c4b1d'
17 = '#c4151c'

[colors.tab_bar]
background = '#f5f2f0'
inactive_tab_edge = '#efebe7'

[colors.tab_bar.active_tab]
bg_color = '#908419'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9e3dd'
fg_color = '#908419'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9e3dd'
fg_color = '#ab0707'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ab0707'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#388032'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 1'