# Oasis Midnight Light 2 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_2"

[palettes.oasis_midnight_light_2]
# Accent
primary       = '#766f28'
strong_primary = '#7d783b'

# ANSI colors (0-7)
black         = '#4c4c4c'
red           = '#b01212'
green         = '#376134'
blue          = '#13589e'
purple        = '#7523d4'
cyan          = '#31605a'
white         = '#594b13'

# Bright ANSI colors (8-15)
bright_black  = '#554a42'
bright_red    = '#b01212'
bright_green  = '#34622d'
bright_yellow = '#814a13'
bright_blue   = '#225e76'
bright_purple = '#7323d5'
bright_cyan   = '#316059'
bright_white  = '#544c2d'
