# Oasis Starlight Light 2 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_starlight_light_2"

[palettes.oasis_starlight_light_2]
# Accent
primary       = '#075b98'
strong_primary = '#076ab0'

# ANSI colors (0-7)
black         = '#545454'
red           = '#bf1313'
green         = '#3c6a39'
blue          = '#1561ad'
purple        = '#7f2edd'
cyan          = '#366862'
white         = '#625315'

# Bright ANSI colors (8-15)
bright_black  = '#5e5149'
bright_red    = '#bf1313'
bright_green  = '#396b32'
bright_yellow = '#8d5115'
bright_blue   = '#256781'
bright_purple = '#7d2fdd'
bright_cyan   = '#356961'
bright_white  = '#5c5331'
