# Oasis Scorpion Light 2 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_scorpion_light_2"

[palettes.oasis_scorpion_light_2]
# Accent
primary       = '#706712'
strong_primary = '#8e8736'

# ANSI colors (0-7)
black         = '#3d3d3d'
red           = '#a61111'
green         = '#345c31'
blue          = '#125496'
purple        = '#6e21c8'
cyan          = '#2e5a55'
white         = '#473c0f'

# Bright ANSI colors (8-15)
bright_black  = '#443b35'
bright_red    = '#a61111'
bright_green  = '#315d2b'
bright_yellow = '#7a4612'
bright_blue   = '#205970'
bright_purple = '#6d21c9'
bright_cyan   = '#2e5a54'
bright_white  = '#433c24'
