# Oasis Mirage Light 2 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_mirage_light_2"

[palettes.oasis_mirage_light_2]
# Accent
primary       = '#316e67'
strong_primary = '#387f77'

# ANSI colors (0-7)
black         = '#545454'
red           = '#c01313'
green         = '#3d6b39'
blue          = '#1561ae'
purple        = '#7f2fdd'
cyan          = '#366963'
white         = '#625315'

# Bright ANSI colors (8-15)
bright_black  = '#5e5249'
bright_red    = '#c01313'
bright_green  = '#396c32'
bright_yellow = '#8e5115'
bright_blue   = '#256782'
bright_purple = '#7e30dd'
bright_cyan   = '#356961'
bright_white  = '#5d5432'
