# Oasis Cactus Light 2 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_cactus_light_2"

[palettes.oasis_cactus_light_2]
# Accent
primary       = '#38663b'
strong_primary = '#417644'

# ANSI colors (0-7)
black         = '#535353'
red           = '#bf1313'
green         = '#3c6a38'
blue          = '#1560ad'
purple        = '#7e2ddc'
cyan          = '#356862'
white         = '#625214'

# Bright ANSI colors (8-15)
bright_black  = '#5e5149'
bright_red    = '#bf1313'
bright_green  = '#396b32'
bright_yellow = '#8d5115'
bright_blue   = '#256681'
bright_purple = '#7d2fdd'
bright_cyan   = '#356861'
bright_white  = '#5c5331'
