# Oasis Canyon Light 2 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_canyon_light_2"

[palettes.oasis_canyon_light_2]
# Accent
primary       = '#994f05'
strong_primary = '#b25906'

# ANSI colors (0-7)
black         = '#515151'
red           = '#bb1313'
green         = '#3b6837'
blue          = '#155ea9'
purple        = '#7c2adc'
cyan          = '#346660'
white         = '#5f5014'

# Bright ANSI colors (8-15)
bright_black  = '#5b4f47'
bright_red    = '#bb1313'
bright_green  = '#376830'
bright_yellow = '#8a4f14'
bright_blue   = '#24647e'
bright_purple = '#7a2bdc'
bright_cyan   = '#34665f'
bright_white  = '#5a5130'
