# extras/kitty/oasis_night_light_5.conf
## name: Oasis Night Light 5
## author: uhs-robert

# Palette
color0                   #50332c
color8                   #4c3529

color1                   #8f0e0e
color9                   #8f0e0e

color2                   #2c4e29
color10                  #2a4f25

color3                   #4c4719
color11                  #683b0f

color4                   #0f477f
color12                  #1b4b5f

color5                   #5e1cab
color13                  #5d1cac

color6                   #274d48
color14                  #274d47

color7                   #443a0e
color15                  #413a22

# Core
foreground               #473726
background               #aad0ee

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #683b11
cursor_text_color        #aad0ee

# Borders (panes)
active_border_color      #2d3c4b
inactive_border_color    #9ec9eb

# Tabs
active_tab_foreground    #aad0ee
active_tab_background    #263f5a
inactive_tab_foreground  #263f5a
inactive_tab_background  #9ec9eb
