# extras/kitty/oasis_moonlight_light_5.conf
## name: Oasis Moonlight Light 5
## author: uhs-robert

# Palette
color0                   #304768
color8                   #3b4851

color1                   #a51010
color9                   #a51010

color2                   #335b30
color10                  #305c2b

color3                   #59531d
color11                  #794512

color4                   #125393
color12                  #20586f

color5                   #6d20c6
color13                  #6c21c7

color6                   #2e5954
color14                  #2d5952

color7                   #524511
color15                  #4d4629

# Core
foreground               #161412
background               #e9ddbe

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #695f19
cursor_text_color        #e9ddbe

# Borders (panes)
active_border_color      #36485a
inactive_border_color    #e6d7b3

# Tabs
active_tab_foreground    #e9ddbe
active_tab_background    #1e3146
inactive_tab_foreground  #1e3146
inactive_tab_background  #e6d7b3
