# extras/kitty/oasis_dune_light_5.conf
## name: Oasis Dune Light 5
## author: uhs-robert

# Palette
color0                   #3d3d3d
color8                   #433b34

color1                   #a61010
color9                   #a61010

color2                   #345c30
color10                  #315c2b

color3                   #5a541e
color11                  #7a4612

color4                   #125495
color12                  #205970

color5                   #6e21c8
color13                  #6d21c9

color6                   #2e5a55
color14                  #2e5a53

color7                   #473c0f
color15                  #433c24

# Core
foreground               #161513
background               #f2dcba

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #695f1a
cursor_text_color        #f2dcba

# Borders (panes)
active_border_color      #5a573e
inactive_border_color    #eed2a7

# Tabs
active_tab_foreground    #f2dcba
active_tab_background    #4c4718
inactive_tab_foreground  #4c4718
inactive_tab_background  #eed2a7
