# extras/kitty/oasis_luna_light_5.conf
## name: Oasis Luna Light 5
## author: uhs-robert

# Palette
color0                   #373737
color8                   #3d362f

color1                   #880d0d
color9                   #890d0d

color2                   #2a4a27
color10                  #284b23

color3                   #484418
color11                  #63390f

color4                   #0f4479
color12                  #1a485b

color5                   #5a1ba3
color13                  #591ba4

color6                   #254945
color14                  #254944

color7                   #40360d
color15                  #3d3720

# Core
foreground               #100e1b
background               #c3c2f0

# Selection
selection_background     #c3a1dd
selection_foreground     #31124a

# Cursor
cursor                   #585015
cursor_text_color        #c3c2f0

# Borders (panes)
active_border_color      #30306d
inactive_border_color    #b7b6ed

# Tabs
active_tab_foreground    #c3c2f0
active_tab_background    #58500b
inactive_tab_foreground  #58500b
inactive_tab_background  #b7b6ed
