# extras/kitty/oasis_sol_light_5.conf
## name: Oasis Sol Light 5
## author: uhs-robert

# Palette
color0                   #1d1d1d
color8                   #201d19

color1                   #720b0b
color9                   #720b0b

color2                   #233d20
color10                  #213e1d

color3                   #3c3814
color11                  #522f0c

color4                   #0c3864
color12                  #153b4b

color5                   #4a1687
color13                  #4a1688

color6                   #1f3c39
color14                  #1f3c38

color7                   #221d07
color15                  #201d11

# Core
foreground               #1d0f0c
background               #e9a3a3

# Selection
selection_background     #e19d9d
selection_foreground     #4e0e0e

# Cursor
cursor                   #811d1f
cursor_text_color        #e9a3a3

# Borders (panes)
active_border_color      #521414
inactive_border_color    #e38a8a

# Tabs
active_tab_foreground    #e9a3a3
active_tab_background    #630000
inactive_tab_foreground  #630000
inactive_tab_background  #e38a8a
