# extras/kitty/oasis_starlight_light_5.conf
## name: Oasis Starlight Light 5
## author: uhs-robert

# Palette
color0                   #404040
color8                   #473f37

color1                   #ae1111
color9                   #ae1111

color2                   #366033
color10                  #33612d

color3                   #5e581f
color11                  #804913

color4                   #13579b
color12                  #225d75

color5                   #7322d1
color13                  #7222d2

color6                   #305e59
color14                  #305f57

color7                   #4b4010
color15                  #474026

# Core
foreground               #181611
background               #ebe5d5

# Selection
selection_background     #dacfa4
selection_foreground     #473c15

# Cursor
cursor                   #1565ac
cursor_text_color        #ebe5d5

# Borders (panes)
active_border_color      #255e86
inactive_border_color    #e4dbc5

# Tabs
active_tab_foreground    #ebe5d5
active_tab_background    #013a62
inactive_tab_foreground  #013a62
inactive_tab_background  #e4dbc5
