# extras/kitty/oasis_mirage_light_5.conf
## name: Oasis Mirage Light 5
## author: uhs-robert

# Palette
color0                   #3e3e3e
color8                   #453d36

color1                   #aa1010
color9                   #aa1111

color2                   #355e31
color10                  #325f2c

color3                   #5c561e
color11                  #7d4712

color4                   #125598
color12                  #215a72

color5                   #7021cc
color13                  #6f22cd

color6                   #2f5c57
color14                  #2f5c55

color7                   #493e0f
color15                  #453e25

# Core
foreground               #121717
background               #c1eae6

# Selection
selection_background     #9fe0d7
selection_foreground     #0f4c44

# Cursor
cursor                   #366a63
cursor_text_color        #c1eae6

# Borders (panes)
active_border_color      #3a5e5a
inactive_border_color    #b0e4df

# Tabs
active_tab_foreground    #c1eae6
active_tab_background    #1d4641
inactive_tab_foreground  #1d4641
inactive_tab_background  #b0e4df
