# extras/kitty/oasis_sol_light_5.conf
## name: Oasis Sol Light 5
## author: uhs-robert

# Palette
color0                   #383838
color8                   #3e3730

color1                   #8b0d0d
color9                   #8b0e0e

color2                   #2b4c28
color10                  #284c24

color3                   #4a4519
color11                  #653a0f

color4                   #0f457b
color12                  #1b495c

color5                   #5c1ba7
color13                  #5b1ba7

color6                   #264a46
color14                  #264b45

color7                   #42380e
color15                  #3e3821

# Core
foreground               #572c25
background               #f3babd

# Selection
selection_background     #e19d9d
selection_foreground     #4e0e0e

# Cursor
cursor                   #831e1f
cursor_text_color        #f3babd

# Borders (panes)
active_border_color      #6b1a1a
inactive_border_color    #f1adb1

# Tabs
active_tab_foreground    #f3babd
active_tab_background    #782107
inactive_tab_foreground  #782107
inactive_tab_background  #f1adb1
