# extras/kitty/oasis_twilight_light_5.conf
## name: Oasis Twilight Light 5
## author: uhs-robert

# Palette
color0                   #323232
color8                   #38312b

color1                   #940e0e
color9                   #940e0e

color2                   #2e512b
color10                  #2b5126

color3                   #4f4a1a
color11                  #6c3e10

color4                   #104a83
color12                  #1c4e63

color5                   #621db1
color13                  #611db2

color6                   #294f4b
color14                  #28504a

color7                   #3b320c
color15                  #38321e

# Core
foreground               #161217
background               #dbc8ec

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #7e4815
cursor_text_color        #dbc8ec

# Borders (panes)
active_border_color      #5d3a8d
inactive_border_color    #d0b7e6

# Tabs
active_tab_foreground    #dbc8ec
active_tab_background    #5e1a06
inactive_tab_foreground  #5e1a06
inactive_tab_background  #d0b7e6
