# extras/kitty/oasis_luna_light_5.conf
## name: Oasis Luna Light 5
## author: uhs-robert

# Palette
color0                   #303030
color8                   #352f29

color1                   #8f0e0e
color9                   #8f0e0e

color2                   #2c4e29
color10                  #2a4f25

color3                   #4c4819
color11                  #683c0f

color4                   #0f487f
color12                  #1b4c5f

color5                   #5e1cac
color13                  #5e1cac

color6                   #274d48
color14                  #274d47

color7                   #382f0c
color15                  #35301c

# Core
foreground               #100e1b
background               #cbc7f2

# Selection
selection_background     #c3a1dd
selection_foreground     #31124a

# Cursor
cursor                   #5c5316
cursor_text_color        #cbc7f2

# Borders (panes)
active_border_color      #333374
inactive_border_color    #b4aeec

# Tabs
active_tab_foreground    #cbc7f2
active_tab_background    #58500b
inactive_tab_foreground  #58500b
inactive_tab_background  #b4aeec
