# extras/kitty/oasis_twilight_light_5.conf
## name: Oasis Twilight Light 5
## author: uhs-robert

# Palette
color0                   #323232
color8                   #38312b

color1                   #940e0e
color9                   #940e0e

color2                   #2e512b
color10                  #2b5126

color3                   #4f4a1a
color11                  #6c3e10

color4                   #104a83
color12                  #1c4e63

color5                   #621db1
color13                  #611db2

color6                   #2d4f45
color14                  #2c5045

color7                   #343418
color15                  #34340b

# Core
foreground               #181811
background               #dbc8ec

# Selection
selection_background     #bd9bdc
selection_foreground     #2d2d17

# Cursor
cursor                   #953519
cursor_text_color        #dbc8ec

# Borders (panes)
active_border_color      #5d3a8d
inactive_border_color    #d0b7e6

# Tabs
active_tab_foreground    #dbc8ec
active_tab_background    #5e1a06
inactive_tab_foreground  #5e1a06
inactive_tab_background  #d0b7e6
