# extras/kitty/oasis_midnight_light_5.conf
## name: Oasis Midnight Light 5
## author: uhs-robert

# Palette
color0                   #313131
color8                   #362f2a

color1                   #910e0e
color9                   #910e0e

color2                   #2d4f2a
color10                  #2a5025

color3                   #4d481a
color11                  #6a3c0f

color4                   #104880
color12                  #1c4d61

color5                   #601cae
color13                  #5f1dae

color6                   #2c4e44
color14                  #2b4e44

color7                   #323218
color15                  #32320b

# Core
foreground               #181811
background               #c6cddc

# Selection
selection_background     #a0acc5
selection_foreground     #2b2b16

# Cursor
cursor                   #5d5417
cursor_text_color        #c6cddc

# Borders (panes)
active_border_color      #4f4b2f
inactive_border_color    #b8c1d3

# Tabs
active_tab_foreground    #c6cddc
active_tab_background    #4c4717
inactive_tab_foreground  #4c4717
inactive_tab_background  #b8c1d3
