# extras/kitty/oasis_scorpion_light_5.conf
## name: Oasis Scorpion Light 5
## author: uhs-robert

# Palette
color0                   #353535
color8                   #3b342e

color1                   #860d0d
color9                   #860d0d

color2                   #294926
color10                  #274922

color3                   #474318
color11                  #61380e

color4                   #0e4376
color12                  #1a4759

color5                   #581aa0
color13                  #571aa1

color6                   #254743
color14                  #244842

color7                   #3f350d
color15                  #3b3520

# Core
foreground               #43322b
background               #f0b7a8

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #494212
cursor_text_color        #f0b7a8

# Borders (panes)
active_border_color      #4a2f26
inactive_border_color    #eeac9b

# Tabs
active_tab_foreground    #f0b7a8
active_tab_background    #71670f
inactive_tab_foreground  #71670f
inactive_tab_background  #eeac9b
