# extras/foot/themes/5/oasis_luna.ini
# name: Oasis Luna Light 5
# author: uhs-robert

[colors-dark]
cursor=0D0D2B F0E68C
foreground=F5F5DC
background=0D0D2B

selection-foreground=F5F5DC
selection-background=433F38

search-box-no-match=F5F5DC 666666
search-box-match=0D0D2B ADC76B

urls=87CEEB
jump-labels=0D0D2B ADC76B

regular0=0D0D2B
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=69C3AA
regular7=F5F5DC

bright0=8A82B3
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8AD3BE
bright7=FFFFF0
16=FF9633
17=FF7979

[colors-light]
cursor=cbc7f2 5a5324
foreground=181811
background=cbc7f2

selection-foreground=181811
selection-background=9d95e6

search-box-no-match=31124a c3a1dd
search-box-match=31290d d1be7a

urls=224352
jump-labels=31290d d1be7a

regular0=303030
regular1=8f0e0e
regular2=2c4e29
regular3=4c4819
regular4=0f487f
regular5=5e1cac
regular6=2b4d43
regular7=313117

bright0=352f29
bright1=8f0e0e
bright2=2a4f25
bright3=683c0f
bright4=1b4c5f
bright5=5e1cac
bright6=2a4d43
bright7=31310a
16=7c4b1e
17=8e0f15
