# extras/foot/themes/5/oasis_midnight.ini
# name: Oasis Midnight Light 5
# author: uhs-robert

[colors-dark]
cursor=0C0E13 F0E68C
foreground=F7F4F2
background=0C0E13

selection-foreground=F7F4F2
selection-background=1E2A38

search-box-no-match=F7F4F2 666666
search-box-match=0C0E13 A1C254

urls=87CEEB
jump-labels=0C0E13 A1C254

regular0=0C0E13
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=68C0B6
regular7=FFF7D7

bright0=4E6578
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8FD1C7
bright7=F7F4E9
16=FFA34D
17=FF7979

[colors-light]
cursor=c6cddc 5d5417
foreground=161412
background=c6cddc

selection-foreground=161412
selection-background=a0acc5

search-box-no-match=4e370e e1c99d
search-box-match=26310d b7d17a

urls=224453
jump-labels=26310d b7d17a

regular0=313131
regular1=910e0e
regular2=2d4f2a
regular3=4d481a
regular4=104880
regular5=601cae
regular6=284e49
regular7=39300c

bright0=362f2a
bright1=910e0e
bright2=2a5025
bright3=6a3c0f
bright4=1c4d61
bright5=5f1dae
bright6=284e48
bright7=36301d
16=7d4c1e
17=901015
