# Oasis Rose Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_rose_light_3"

[palettes.oasis_rose_light_3]
# Accent
primary       = '#572133'
strong_primary = '#843650'

# ANSI colors (0-7)
black         = '#494949'
red           = '#ab1111'
green         = '#365f32'
blue          = '#135699'
purple        = '#7121ce'
cyan          = '#2f5d58'
white         = '#564812'

# Bright ANSI colors (8-15)
bright_black  = '#52473f'
bright_red    = '#ab1111'
bright_green  = '#335f2c'
bright_yellow = '#7e4813'
bright_blue   = '#215c73'
bright_purple = '#7022d0'
bright_cyan   = '#2f5d56'
bright_white  = '#51492c'
