# Oasis Canyon Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_canyon_light_3"

[palettes.oasis_canyon_light_3]
# Accent
primary       = '#703c08'
strong_primary = '#9c5b1e'

# ANSI colors (0-7)
black         = '#383838'
red           = '#9e1010'
green         = '#31572e'
blue          = '#114f8d'
purple        = '#681fbe'
cyan          = '#2b5551'
white         = '#42370e'

# Bright ANSI colors (8-15)
bright_black  = '#3e3731'
bright_red    = '#9e1010'
bright_green  = '#2f5828'
bright_yellow = '#744211'
bright_blue   = '#1e5469'
bright_purple = '#671fbf'
bright_cyan   = '#2b554f'
bright_white  = '#3e3821'
