# Oasis Scorpion Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_scorpion_light_3"

[palettes.oasis_scorpion_light_3]
# Accent
primary       = '#685f10'
strong_primary = '#878133'

# ANSI colors (0-7)
black         = '#373737'
red           = '#9d1010'
green         = '#31562d'
blue          = '#114f8b'
purple        = '#681fbd'
cyan          = '#2b5550'
white         = '#41370e'

# Bright ANSI colors (8-15)
bright_black  = '#3e3630'
bright_red    = '#9d1010'
bright_green  = '#2e5728'
bright_yellow = '#734211'
bright_blue   = '#1e5469'
bright_purple = '#661fbe'
bright_cyan   = '#2b554f'
bright_white  = '#3d3721'
