# Oasis Mirage Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_mirage_light_3"

[palettes.oasis_mirage_light_3]
# Accent
primary       = '#2d6760'
strong_primary = '#347971'

# ANSI colors (0-7)
black         = '#505050'
red           = '#b91313'
green         = '#3a6736'
blue          = '#145ea6'
purple        = '#7b27dc'
cyan          = '#33655f'
white         = '#5e4f14'

# Bright ANSI colors (8-15)
bright_black  = '#5a4e46'
bright_red    = '#b91313'
bright_green  = '#376830'
bright_yellow = '#894e15'
bright_blue   = '#24647d'
bright_purple = '#7929dc'
bright_cyan   = '#33655e'
bright_white  = '#595030'
