# Oasis Sol Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_sol_light_3"

[palettes.oasis_sol_light_3]
# Accent
primary       = '#910303'
strong_primary = '#8e1f1f'

# ANSI colors (0-7)
black         = '#474747'
red           = '#a71111'
green         = '#345c30'
blue          = '#125495'
purple        = '#6f21c9'
cyan          = '#2e5a55'
white         = '#534612'

# Bright ANSI colors (8-15)
bright_black  = '#4f453e'
bright_red    = '#a71111'
bright_green  = '#315d2b'
bright_yellow = '#7b4612'
bright_blue   = '#205970'
bright_purple = '#6d21ca'
bright_cyan   = '#2e5b54'
bright_white  = '#4f472a'
