# Oasis Scorpion Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_scorpion_light_3"

[palettes.oasis_scorpion_light_3]
# Accent
primary       = '#817613'
strong_primary = '#7e782f'

# ANSI colors (0-7)
black         = '#424242'
red           = '#9e1010'
green         = '#31572e'
blue          = '#11508d'
purple        = '#691fbf'
cyan          = '#2c5551'
white         = '#4e4211'

# Bright ANSI colors (8-15)
bright_black  = '#4a413a'
bright_red    = '#9e1010'
bright_green  = '#2f5829'
bright_yellow = '#744211'
bright_blue   = '#1e546a'
bright_purple = '#671fc0'
bright_cyan   = '#2c5650'
bright_white  = '#4a4228'
