# Oasis Luna Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_luna_light_3"

[palettes.oasis_luna_light_3]
# Accent
primary       = '#685f10'
strong_primary = '#3c2f8b'

# ANSI colors (0-7)
black         = '#474747'
red           = '#a61111'
green         = '#345c30'
blue          = '#125494'
purple        = '#6e21c8'
cyan          = '#2e5a55'
white         = '#534612'

# Bright ANSI colors (8-15)
bright_black  = '#4f453d'
bright_red    = '#a61111'
bright_green  = '#315c2b'
bright_yellow = '#7a4612'
bright_blue   = '#20596f'
bright_purple = '#6d21ca'
bright_cyan   = '#2e5a54'
bright_white  = '#4e472a'
