# Oasis Starlight Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_starlight_light_3"

[palettes.oasis_starlight_light_3]
# Accent
primary       = '#044574'
strong_primary = '#186aa2'

# ANSI colors (0-7)
black         = '#4f4f4f'
red           = '#b71212'
green         = '#3a6535'
blue          = '#145ca4'
purple        = '#7924dc'
cyan          = '#33635e'
white         = '#5d4e14'

# Bright ANSI colors (8-15)
bright_black  = '#584d45'
bright_red    = '#b71212'
bright_green  = '#36662f'
bright_yellow = '#874d14'
bright_blue   = '#23627b'
bright_purple = '#7826dc'
bright_cyan   = '#33645d'
bright_white  = '#584f2f'
