# Oasis Lagoon Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_lagoon_light_3"

[palettes.oasis_lagoon_light_3]
# Accent
primary       = '#044574'
strong_primary = '#186aa2'

# ANSI colors (0-7)
black         = '#4a4a4a'
red           = '#ac1111'
green         = '#365f32'
blue          = '#13579a'
purple        = '#7222cf'
cyan          = '#2f5d58'
white         = '#564912'

# Bright ANSI colors (8-15)
bright_black  = '#524840'
bright_red    = '#ac1111'
bright_green  = '#33602c'
bright_yellow = '#7f4813'
bright_blue   = '#215c73'
bright_purple = '#7122d1'
bright_cyan   = '#305e57'
bright_white  = '#52492c'
