# Oasis Twilight Light 3 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_twilight_light_3"

[palettes.oasis_twilight_light_3]
# Accent
primary       = '#89280b'
strong_primary = '#8e3d1f'

# ANSI colors (0-7)
black         = '#444444'
red           = '#a11010'
green         = '#32582e'
blue          = '#11518f'
purple        = '#6a1fc1'
cyan          = '#2c5752'
white         = '#504311'

# Bright ANSI colors (8-15)
bright_black  = '#4b423b'
bright_red    = '#a11010'
bright_green  = '#2f5929'
bright_yellow = '#764312'
bright_blue   = '#1f566b'
bright_purple = '#6920c3'
bright_cyan   = '#2c5751'
bright_white  = '#4b4328'
