# extras/foot/themes/1/oasis_mirage.ini
# name: Oasis Mirage Light 1
# author: uhs-robert

[colors-dark]
cursor=111C22 F0E68C
foreground=F5F5DC
background=111C22

selection-foreground=F5F5DC
selection-background=21333B

search-box-no-match=F5F5DC 666666
search-box-match=111C22 C28EFF

urls=87CEEB
jump-labels=111C22 C28EFF

regular0=111C22
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=69C3AA
regular7=F5F5DC

bright0=587270
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8AD3BE
bright7=FFFFF0
16=FFA34D
17=FF7979

[colors-light]
cursor=effaf8 387968
foreground=1c1c14
background=effaf8

selection-foreground=1c1c14
selection-background=c0ebe4

search-box-no-match=0f4c44 9fe0d7
search-box-match=351908 dd986f

urls=306073
jump-labels=351908 dd986f

regular0=4b4b4b
regular1=c21313
regular2=3d6c39
regular3=696323
regular4=1662af
regular5=8030de
regular6=3c6a5d
regular7=4d4d24

bright0=544941
bright1=c21414
bright2=396d33
bright3=8f5215
bright4=266884
bright5=7f31de
bright6=396a5d
bright7=4d4d10
16=a36326
17=c1151c
