# extras/foot/themes/1/oasis_mirage.ini
# name: Oasis Mirage Light 1
# author: uhs-robert

[colors-dark]
cursor=111C22 F0E68C
foreground=DDEFEF
background=111C22

selection-foreground=DDEFEF
selection-background=21333B

search-box-no-match=DDEFEF 666666
search-box-match=111C22 C28EFF

urls=87CEEB
jump-labels=111C22 C28EFF

regular0=111C22
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=68C0B6
regular7=FFF7D7

bright0=587270
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8FD1C7
bright7=F7F4E9
16=FFA34D
17=FF7979

[colors-light]
cursor=effaf8 3b786f
foreground=161d1d
background=effaf8

selection-foreground=161d1d
selection-background=c0ebe4

search-box-no-match=0f4c44 9fe0d7
search-box-match=351908 dd986f

urls=306073
jump-labels=351908 dd986f

regular0=4b4b4b
regular1=c21313
regular2=3d6c39
regular3=696323
regular4=1662af
regular5=8030de
regular6=366a64
regular7=584a13

bright0=544941
bright1=c21414
bright2=396d33
bright3=8f5215
bright4=266884
bright5=7f31de
bright6=356a62
bright7=534b2c
16=a36326
17=c1151c
