# extras/foot/themes/1/oasis_luna.ini
# name: Oasis Luna Light 1
# author: uhs-robert

[colors-dark]
cursor=0D0D2B F0E68C
foreground=F5F5DC
background=0D0D2B

selection-foreground=F5F5DC
selection-background=433F38

search-box-no-match=F5F5DC 666666
search-box-match=0D0D2B ADC76B

urls=87CEEB
jump-labels=0D0D2B ADC76B

regular0=0D0D2B
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=69C3AA
regular7=F5F5DC

bright0=8A82B3
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8AD3BE
bright7=FFFFF0
16=FF9633
17=FF7979

[colors-light]
cursor=f3f3fc 766c2f
foreground=191911
background=f3f3fc

selection-foreground=191911
selection-background=c2c2f0

search-box-no-match=31124a c3a1dd
search-box-match=31290d d1be7a

urls=2f5d70
jump-labels=31290d d1be7a

regular0=494949
regular1=be1313
regular2=3c6938
regular3=676022
regular4=1560ab
regular5=7d2cdd
regular6=3a675b
regular7=4b4b23

bright0=51473f
bright1=be1313
bright2=386a31
bright3=8c5015
bright4=256681
bright5=7d2ddd
bright6=38685b
bright7=4b4b10
16=a06125
17=bd151b
