# extras/alacritty/themes/light/1/oasis_twilight_light_1.toml
## name: Oasis Twilight Light 1
## author: uhs-robert

[colors.primary]
background = '#f8f4fb'
foreground = '#1e181f'

[colors.selection]
background = '#dbc7eb'
text = '#1e181f'

[colors.cursor]
cursor = '#a25b1a'
text = '#f8f4fb'

[colors.vi_mode_cursor]
cursor = '#8d5115'
text = '#f8f4fb'

[colors.normal]
black   = '#4a4a4a'
red     = '#c01313'
green   = '#3c6a38'
yellow  = '#686123'
blue    = '#1561ad'
magenta = '#7e2edd'
cyan    = '#356863'
white   = '#564912'

[colors.bright]
black   = '#524840'
red     = '#c01313'
green   = '#386b32'
yellow  = '#8d5115'
blue    = '#256782'
magenta = '#7e2fdd'
cyan    = '#356960'
white   = '#52492c'