# extras/alacritty/themes/light/1/oasis_cactus_light_1.toml
## name: Oasis Cactus Light 1
## author: uhs-robert

[colors.primary]
background = '#f9fbfa'
foreground = '#19201c'

[colors.selection]
background = '#dde9e3'
text = '#19201c'

[colors.cursor]
cursor = '#487b4b'
text = '#f9fbfa'

[colors.vi_mode_cursor]
cursor = '#915416'
text = '#f9fbfa'

[colors.normal]
black   = '#575757'
red     = '#c51414'
green   = '#3e6e3a'
yellow  = '#6b6424'
blue    = '#1664b2'
magenta = '#8233de'
cyan    = '#376c66'
white   = '#655516'

[colors.bright]
black   = '#61544b'
red     = '#c51414'
green   = '#3a6e33'
yellow  = '#915416'
blue    = '#266a86'
magenta = '#8134de'
cyan    = '#366c63'
white   = '#605633'