# extras/alacritty/themes/light/1/oasis_abyss_light_1.toml
## name: Oasis Abyss Light 1
## author: uhs-robert

[colors.primary]
background = '#f2ede9'
foreground = '#564e47'

[colors.selection]
background = '#e0d6cc'
text = '#564e47'

[colors.cursor]
cursor = '#675c18'
text = '#f2ede9'

[colors.vi_mode_cursor]
cursor = '#874d14'
text = '#f2ede9'

[colors.normal]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#3a6636'
yellow  = '#635d21'
blue    = '#145ca5'
magenta = '#7925dc'
cyan    = '#33645e'
white   = '#5d4e14'

[colors.bright]
black   = '#594d44'
red     = '#b71212'
green   = '#366630'
yellow  = '#874d14'
blue    = '#24627c'
magenta = '#7826dc'
cyan    = '#32645c'
white   = '#584f2f'