# extras/alacritty/themes/light/1/oasis_abyss_light_1.toml
## name: Oasis Abyss Light 1
## author: uhs-robert

[colors.primary]
background = '#e7e7e7'
foreground = '#161412'

[colors.selection]
background = '#d0d0d0'
text = '#161412'

[colors.cursor]
cursor = '#70641a'
text = '#e7e7e7'

[colors.vi_mode_cursor]
cursor = '#814a13'
text = '#e7e7e7'

[colors.normal]
black   = '#414141'
red     = '#b01212'
green   = '#376133'
yellow  = '#5f5920'
blue    = '#14589e'
magenta = '#7422d5'
cyan    = '#315f5a'
white   = '#4d4110'

[colors.bright]
black   = '#494038'
red     = '#b01212'
green   = '#34622e'
yellow  = '#814a13'
blue    = '#225e77'
magenta = '#7323d5'
cyan    = '#306058'
white   = '#494127'