# extras/alacritty/themes/light/1/oasis_lagoon_light_1.toml
## name: Oasis Lagoon Light 1
## author: uhs-robert

[colors.primary]
background = '#f2f7fd'
foreground = '#141b26'

[colors.selection]
background = '#bdd6f5'
text = '#141b26'

[colors.cursor]
cursor = '#186fbc'
text = '#f2f7fd'

[colors.vi_mode_cursor]
cursor = '#8e5215'
text = '#f2f7fd'

[colors.normal]
black   = '#4a4a4a'
red     = '#c01313'
green   = '#3d6b39'
yellow  = '#696223'
blue    = '#1561ae'
magenta = '#7f2fde'
cyan    = '#366963'
white   = '#574913'

[colors.bright]
black   = '#534840'
red     = '#c01313'
green   = '#396c32'
yellow  = '#8e5215'
blue    = '#266783'
magenta = '#7e30dd'
cyan    = '#356961'
white   = '#524a2c'