# extras/alacritty/themes/light/1/oasis_starlight_light_1.toml
## name: Oasis Starlight Light 1
## author: uhs-robert

[colors.primary]
background = '#faf9f5'
foreground = '#1f1d17'

[colors.selection]
background = '#e6e1cc'
text = '#1f1d17'

[colors.cursor]
cursor = '#1871bf'
text = '#faf9f5'

[colors.vi_mode_cursor]
cursor = '#905315'
text = '#faf9f5'

[colors.normal]
black   = '#4c4c4c'
red     = '#c31414'
green   = '#3e6d39'
yellow  = '#6a6323'
blue    = '#1663b1'
magenta = '#8132de'
cyan    = '#376b65'
white   = '#594b13'

[colors.bright]
black   = '#554a41'
red     = '#c31414'
green   = '#3a6e33'
yellow  = '#905315'
blue    = '#266985'
magenta = '#8033de'
cyan    = '#366b63'
white   = '#544b2d'