# extras/alacritty/themes/light/1/oasis_sol_light_1.toml
## name: Oasis Sol Light 1
## author: uhs-robert

[colors.primary]
background = '#fbf9f9'
foreground = '#844437'

[colors.selection]
background = '#e9dddd'
text = '#844437'

[colors.cursor]
cursor = '#bb292c'
text = '#fbf9f9'

[colors.vi_mode_cursor]
cursor = '#915315'
text = '#fbf9f9'

[colors.normal]
black   = '#565656'
red     = '#c41414'
green   = '#3e6d3a'
yellow  = '#6a6423'
blue    = '#1663b1'
magenta = '#8132de'
cyan    = '#376b65'
white   = '#655516'

[colors.bright]
black   = '#60544a'
red     = '#c41414'
green   = '#3a6e33'
yellow  = '#915315'
blue    = '#266985'
magenta = '#8033de'
cyan    = '#366b63'
white   = '#5f5633'