# vim:set ft=tmux:
## name: Oasis Luna Light 3
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#777237"
set -ogq @thm_primary "#817613"
set -ogq @thm_light_primary "#6b6110"
set -ogq @thm_secondary "#4a039b"
set -ogq @thm_prefix "#156e89"
set -ogq @thm_fg "#3e3366"

# Surfaces and overlays
set -ogq @thm_core "#cbc9ee"
set -ogq @thm_mantle "#bfbdea"
set -ogq @thm_surface "#a9a6e2"
set -ogq @thm_visual "#c3a1dd"

# General
set -ogq @thm_red "#900f0f"
set -ogq @thm_orange "#693c10"
set -ogq @thm_yellow "#4d481a"
set -ogq @thm_green "#841316"
set -ogq @thm_teal "#274e48"
set -ogq @thm_blue "#104880"
set -ogq @thm_indigo "#5f1cad"
