# vim:set ft=tmux:
## name: Oasis Dune Light 3
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#777237"
set -ogq @thm_primary "#6f6825"
set -ogq @thm_light_primary "#6c610f"
set -ogq @thm_secondary "#2f6f65"
set -ogq @thm_prefix "#48039b"
set -ogq @thm_fg "#504e45"

# Surfaces and overlays
set -ogq @thm_core "#f7e9d4"
set -ogq @thm_mantle "#f5e2c7"
set -ogq @thm_surface "#f0d5ad"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#b41212"
set -ogq @thm_orange "#844c14"
set -ogq @thm_yellow "#625b20"
set -ogq @thm_green "#a7181c"
set -ogq @thm_teal "#32625b"
set -ogq @thm_blue "#145ba1"
set -ogq @thm_indigo "#7723d9"
