# vim:set ft=tmux:
## name: Oasis Sol Light 3
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#83422a"
set -ogq @thm_primary "#89280b"
set -ogq @thm_light_primary "#732508"
set -ogq @thm_secondary "#944f0a"
set -ogq @thm_prefix "#31732b"
set -ogq @thm_fg "#6a372d"

# Surfaces and overlays
set -ogq @thm_core "#f7d4d4"
set -ogq @thm_mantle "#f5c7c7"
set -ogq @thm_surface "#f0adad"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#a31010"
set -ogq @thm_orange "#784412"
set -ogq @thm_yellow "#58521d"
set -ogq @thm_green "#704016"
set -ogq @thm_teal "#2d5852"
set -ogq @thm_blue "#125291"
set -ogq @thm_indigo "#6c20c4"
