# vim:set ft=tmux:
## name: Oasis Midnight Light 3
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#777237"
set -ogq @thm_primary "#6f6825"
set -ogq @thm_light_primary "#6b6110"
set -ogq @thm_secondary "#9b0303"
set -ogq @thm_prefix "#31732b"
set -ogq @thm_fg "#504741"

# Surfaces and overlays
set -ogq @thm_core "#f4e0c3"
set -ogq @thm_mantle "#f1dab6"
set -ogq @thm_surface "#edcc9c"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#ab1111"
set -ogq @thm_orange "#7e4813"
set -ogq @thm_yellow "#5c561f"
set -ogq @thm_green "#9e171b"
set -ogq @thm_teal "#2f5c56"
set -ogq @thm_blue "#135698"
set -ogq @thm_indigo "#7121ce"
