# extras/kitty/oasis_rose_light_4.conf
## name: Oasis Rose Light 4
## author: uhs-robert

# Palette
color0                   #484848
color8                   #51463f

color1                   #a91111
color9                   #a91010

color2                   #355e32
color10                  #325e2b

color3                   #5b551f
color11                  #7c4712

color4                   #125597
color12                  #205a72

color5                   #7022cb
color13                  #6f21cd

color6                   #305c57
color14                  #2f5c55

color7                   #554712
color15                  #50482b

# Core
foreground               #663c49
background               #c7ebc8

# Selection
selection_background     #dba3c6
selection_foreground     #481335

# Cursor
cursor                   #a91218
cursor_text_color        #c7ebc8

# Borders (panes)
active_border_color      #892121
inactive_border_color    #bce6bd

# Tabs
active_tab_foreground    #c7ebc8
active_tab_background    #812509
inactive_tab_foreground  #812509
inactive_tab_background  #bce6bd
