# extras/kitty/oasis_moonlight_light_4.conf
## name: Oasis Moonlight Light 4
## author: uhs-robert

# Palette
color0                   #5a3a31
color8                   #563c2f

color1                   #9d1010
color9                   #9d0f0f

color2                   #31562e
color10                  #2e5728

color3                   #544f1c
color11                  #734211

color4                   #114f8c
color12                  #1e5369

color5                   #681fbd
color13                  #671fbe

color6                   #2c5550
color14                  #2b554e

color7                   #4d4110
color15                  #494227

# Core
foreground               #4f3f2b
background               #e3d7aa

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #744113
cursor_text_color        #e3d7aa

# Borders (panes)
active_border_color      #334354
inactive_border_color    #e0d19f

# Tabs
active_tab_foreground    #e3d7aa
active_tab_background    #294460
inactive_tab_foreground  #294460
inactive_tab_background  #e0d19f
