# extras/kitty/oasis_scorpion_light_4.conf
## name: Oasis Scorpion Light 4
## author: uhs-robert

# Palette
color0                   #3d3d3d
color8                   #443b35

color1                   #930f0f
color9                   #930e0e

color2                   #2e512b
color10                  #2b5125

color3                   #4f491a
color11                  #6c3d10

color4                   #104a83
color12                  #1c4e62

color5                   #611db1
color13                  #601db2

color6                   #294f4b
color14                  #284f49

color7                   #473c0f
color15                  #433c24

# Core
foreground               #4b3831
background               #f2c5b5

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #514914
cursor_text_color        #f2c5b5

# Borders (panes)
active_border_color      #53352a
inactive_border_color    #f0bba8

# Tabs
active_tab_foreground    #f2c5b5
active_tab_background    #796e11
inactive_tab_foreground  #796e11
inactive_tab_background  #f0bba8
