# extras/kitty/oasis_abyss_light_4.conf
## name: Oasis Abyss Light 4
## author: uhs-robert

# Palette
color0                   #464646
color8                   #4e443d

color1                   #a51111
color9                   #a51010

color2                   #345b31
color10                  #305c2a

color3                   #59531e
color11                  #794512

color4                   #125394
color12                  #1f586f

color5                   #6d21c7
color13                  #6c20c8

color6                   #2e5955
color14                  #2e5a53

color7                   #534511
color15                  #4e4629

# Core
foreground               #171412
background               #dedede

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #695f1a
cursor_text_color        #dedede

# Borders (panes)
active_border_color      #852020
inactive_border_color    #d6d6d6

# Tabs
active_tab_foreground    #dedede
active_tab_background    #534e1b
inactive_tab_foreground  #534e1b
inactive_tab_background  #d6d6d6
