# extras/kitty/oasis_dune_light_4.conf
## name: Oasis Dune Light 4
## author: uhs-robert

# Palette
color0                   #404040
color8                   #473e38

color1                   #ad1212
color9                   #ad1111

color2                   #366033
color10                  #33602c

color3                   #5e571f
color11                  #7f4913

color4                   #13579a
color12                  #215c74

color5                   #7222d0
color13                  #7122d2

color6                   #305e59
color14                  #305e57

color7                   #4b3f10
color15                  #474026

# Core
foreground               #161513
background               #f5e2c7

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #6e631b
cursor_text_color        #f5e2c7

# Borders (panes)
active_border_color      #5d5a40
inactive_border_color    #f2d8b4

# Tabs
active_tab_foreground    #f5e2c7
active_tab_background    #534e1b
inactive_tab_foreground  #534e1b
inactive_tab_background  #f2d8b4
