# extras/kitty/oasis_canyon_light_4.conf
## name: Oasis Canyon Light 4
## author: uhs-robert

# Palette
color0                   #333333
color8                   #39322d

color1                   #960f0f
color9                   #960f0f

color2                   #2e522c
color10                  #2c5326

color3                   #504b1b
color11                  #6e3f10

color4                   #104b85
color12                  #1c4f64

color5                   #631eb3
color13                  #621db5

color6                   #2a504c
color14                  #29514b

color7                   #3c330d
color15                  #39331e

# Core
foreground               #1a150e
background               #ebcbb1

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #814814
cursor_text_color        #ebcbb1

# Borders (panes)
active_border_color      #593616
inactive_border_color    #e5bb99

# Tabs
active_tab_foreground    #ebcbb1
active_tab_background    #683606
inactive_tab_foreground  #683606
inactive_tab_background  #e5bb99
