# extras/kitty/oasis_twilight_light_4.conf
## name: Oasis Twilight Light 4
## author: uhs-robert

# Palette
color0                   #434343
color8                   #4b423b

color1                   #a01010
color9                   #a00f0f

color2                   #32582f
color10                  #2f5929

color3                   #56501d
color11                  #754311

color4                   #11508f
color12                  #1e556b

color5                   #6a20c0
color13                  #691fc2

color6                   #2d5652
color14                  #2c5650

color7                   #4f4311
color15                  #4a4328

# Core
foreground               #161217
background               #f5d2c7

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #894c16
cursor_text_color        #f5d2c7

# Borders (panes)
active_border_color      #6d3221
inactive_border_color    #f3c8ba

# Tabs
active_tab_foreground    #f5d2c7
active_tab_background    #661d07
inactive_tab_foreground  #661d07
inactive_tab_background  #f3c8ba
