# extras/kitty/oasis_midnight_light_4.conf
## name: Oasis Midnight Light 4
## author: uhs-robert

# Palette
color0                   #373737
color8                   #3d3530

color1                   #9b1010
color9                   #9b0f0f

color2                   #30552d
color10                  #2d5628

color3                   #534e1c
color11                  #724111

color4                   #114e8a
color12                  #1d5368

color5                   #661fba
color13                  #661ebc

color6                   #2b544f
color14                  #2b544e

color7                   #40360e
color15                  #3c3620

# Core
foreground               #171412
background               #cfd6e2

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #635918
cursor_text_color        #cfd6e2

# Borders (panes)
active_border_color      #555132
inactive_border_color    #c1cad9

# Tabs
active_tab_foreground    #cfd6e2
active_tab_background    #534e1b
inactive_tab_foreground  #534e1b
inactive_tab_background  #c1cad9
