# extras/kitty/oasis_midnight_light_4.conf
## name: Oasis Midnight Light 4
## author: uhs-robert

# Palette
color0                   #404040
color8                   #473e38

color1                   #9a1010
color9                   #9a0f0f

color2                   #30542d
color10                  #2d5527

color3                   #524d1c
color11                  #714011

color4                   #114d89
color12                  #1d5267

color5                   #651eb8
color13                  #651eba

color6                   #2b534e
color14                  #2a534d

color7                   #4b3f10
color15                  #474026

# Core
foreground               #171412
background               #f4cbc2

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #625918
cursor_text_color        #f4cbc2

# Borders (panes)
active_border_color      #7a1e1e
inactive_border_color    #f2c0b5

# Tabs
active_tab_foreground    #f4cbc2
active_tab_background    #534e1b
inactive_tab_foreground  #534e1b
inactive_tab_background  #f2c0b5
