# extras/kitty/oasis_rose_light_4.conf
## name: Oasis Rose Light 4
## author: uhs-robert

# Palette
color0                   #363636
color8                   #3c352f

color1                   #9a1010
color9                   #9a0f0f

color2                   #30552d
color10                  #2d5527

color3                   #534d1c
color11                  #714111

color4                   #114d89
color12                  #1d5267

color5                   #661fb9
color13                  #651ebb

color6                   #2b534f
color14                  #2b534d

color7                   #3f350d
color15                  #3c3620

# Core
foreground               #1a0f12
background               #f0cae1

# Selection
selection_background     #dba3c6
selection_foreground     #481335

# Cursor
cursor                   #923a56
cursor_text_color        #f0cae1

# Borders (panes)
active_border_color      #6b4551
inactive_border_color    #ebb8d7

# Tabs
active_tab_foreground    #f0cae1
active_tab_background    #501d2f
inactive_tab_foreground  #501d2f
inactive_tab_background  #ebb8d7
