# extras/kitty/oasis_cactus_light_4.conf
## name: Oasis Cactus Light 4
## author: uhs-robert

# Palette
color0                   #404040
color8                   #473e38

color1                   #ac1111
color9                   #ac1111

color2                   #365f33
color10                  #33602c

color3                   #5d571f
color11                  #7f4813

color4                   #13579a
color12                  #215c74

color5                   #7222cf
color13                  #7122d1

color6                   #305d58
color14                  #305e57

color7                   #4b3f10
color15                  #464025

# Core
foreground               #121714
background               #d2eadb

# Selection
selection_background     #a4dac0
selection_foreground     #15472f

# Cursor
cursor                   #406c42
cursor_text_color        #d2eadb

# Borders (panes)
active_border_color      #3a4f3c
inactive_border_color    #bde0ca

# Tabs
active_tab_foreground    #d2eadb
active_tab_background    #264728
inactive_tab_foreground  #264728
inactive_tab_background  #bde0ca
