# extras/kitty/oasis_moonlight_light_4.conf
## name: Oasis Moonlight Light 4
## author: uhs-robert

# Palette
color0                   #3c3c3c
color8                   #433b35

color1                   #a61111
color9                   #a61010

color2                   #345c31
color10                  #315c2a

color3                   #5a541e
color11                  #7a4612

color4                   #125394
color12                  #20596f

color5                   #6e21c7
color13                  #6d20c9

color6                   #2e5a55
color14                  #2e5a53

color7                   #473c0f
color15                  #433c23

# Core
foreground               #171412
background               #e2dfce

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #695f1a
cursor_text_color        #e2dfce

# Borders (panes)
active_border_color      #36485a
inactive_border_color    #d7d2bb

# Tabs
active_tab_foreground    #e2dfce
active_tab_background    #21364d
inactive_tab_foreground  #21364d
inactive_tab_background  #d7d2bb
