# extras/wezterm/oasis_cactus_light_3.toml
## name: Oasis Cactus Light 3
## author: uhs-robert

[colors]
foreground = "#121714"
background= "#dcefe3"
cursor_bg = "#417144"
cursor_border = "#417144"
cursor_fg= "#dcefe3"
selection_bg= "#a4dac0"
selection_fg= "#15472f"
split= "#49634a"
compose_cursor= "#985c25"
scrollbar_thumb= "#b2dcc1"
visual_bell= "#cce8d6"

ansi = [
  '#434343',
  '#b31212',
  '#386334',
  '#615b20',
  '#145ba1',
  '#7723d8',
  '#32625c',
  '#4f4311',
]

brights = [
  '#4b423a',
  '#b31212',
  '#35642e',
  '#844c14',
  '#226078',
  '#7524d9',
  '#32625b',
  '#4b4328',
]

[colors.indexed]
16 = '#985c25'
17 = '#b31319'

[colors.tab_bar]
background = '#cce8d6'
inactive_tab_edge = '#d2eadb'

[colors.tab_bar.active_tab]
bg_color = '#2a4e2c'
fg_color = '#dcefe3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#b2dcc1'
fg_color = '#2a4e2c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#b2dcc1'
fg_color = '#360275'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#360275'
fg_color = '#dcefe3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#9b0303'
fg_color = '#dcefe3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 3'