# extras/wezterm/oasis_desert_light_3.toml
## name: Oasis Desert Light 3
## author: uhs-robert

[colors]
foreground = "#191510"
background= "#f3edcf"
cursor_bg = "#74671c"
cursor_border = "#74671c"
cursor_fg= "#f3edcf"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#942424"
compose_cursor= "#995d25"
scrollbar_thumb= "#eadfaa"
visual_bell= "#ede4b7"

ansi = [
  '#444444',
  '#b61212',
  '#396535',
  '#635c21',
  '#145ca2',
  '#7824db',
  '#32635d',
  '#514411',
]

brights = [
  '#4c433b',
  '#b61212',
  '#36652f',
  '#864d14',
  '#23617a',
  '#7725db',
  '#32635c',
  '#4c4429',
]

[colors.indexed]
16 = '#995d25'
17 = '#b51419'

[colors.tab_bar]
background = '#ede4b7'
inactive_tab_edge = '#f0e8c3'

[colors.tab_bar.active_tab]
bg_color = '#685f10'
fg_color = '#f3edcf'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eadfaa'
fg_color = '#685f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eadfaa'
fg_color = '#750202'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#750202'
fg_color = '#f3edcf'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#31732b'
fg_color = '#f3edcf'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 3'