# extras/wezterm/oasis_mirage_light_3.toml
## name: Oasis Mirage Light 3
## author: uhs-robert

[colors]
foreground = "#181811"
background= "#d8f2ef"
cursor_bg = "#367261"
cursor_border = "#367261"
cursor_fg= "#d8f2ef"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#44655d"
compose_cursor= "#995d25"
scrollbar_thumb= "#aae3dc"
visual_bell= "#c7ece8"

ansi = [
  '#454545',
  '#b61212',
  '#396535',
  '#635c21',
  '#145ca3',
  '#7824db',
  '#386357',
  '#464621',
]

brights = [
  '#4c433b',
  '#b61212',
  '#36652f',
  '#864d14',
  '#23617a',
  '#7725db',
  '#366356',
  '#47470f',
]

[colors.indexed]
16 = '#995d25'
17 = '#b51419'

[colors.tab_bar]
background = '#c7ece8'
inactive_tab_edge = '#cdeeea'

[colors.tab_bar.active_tab]
bg_color = '#235547'
fg_color = '#d8f2ef'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#aae3dc'
fg_color = '#235547'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#aae3dc'
fg_color = '#703c08'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#703c08'
fg_color = '#d8f2ef'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#48039b'
fg_color = '#d8f2ef'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 3'