# extras/wezterm/oasis_luna_light_3.toml
## name: Oasis Luna Light 3
## author: uhs-robert

[colors]
foreground = "#100e1b"
background= "#e2e0f8"
cursor_bg = "#6d611a"
cursor_border = "#6d611a"
cursor_fg= "#e2e0f8"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#4c4cae"
compose_cursor= "#915823"
scrollbar_thumb= "#b3aeed"
visual_bell= "#d0cdf4"

ansi = [
  '#3e3e3e',
  '#aa1111',
  '#355e31',
  '#5c561f',
  '#135698',
  '#7121cd',
  '#2f5c57',
  '#493e10',
]

brights = [
  '#463d36',
  '#aa1111',
  '#325f2c',
  '#7d4813',
  '#205b72',
  '#6f22ce',
  '#2f5c56',
  '#453e25',
]

[colors.indexed]
16 = '#915823'
17 = '#aa1218'

[colors.tab_bar]
background = '#d0cdf4'
inactive_tab_edge = '#d6d4f5'

[colors.tab_bar.active_tab]
bg_color = '#685f10'
fg_color = '#e2e0f8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#b3aeed'
fg_color = '#685f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#b3aeed'
fg_color = '#161661'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#161661'
fg_color = '#e2e0f8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#156e89'
fg_color = '#e2e0f8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 3'