# extras/wezterm/oasis_cactus_light_3.toml
## name: Oasis Cactus Light 3
## author: uhs-robert

[colors]
foreground = "#121714"
background= "#e0f0e7"
cursor_bg = "#427245"
cursor_border = "#427245"
cursor_fg= "#e0f0e7"
selection_bg= "#a4dac0"
selection_fg= "#15472f"
split= "#3e543f"
compose_cursor= "#995d25"
scrollbar_thumb= "#c1e1cf"
visual_bell= "#d6ebdf"

ansi = [
  '#4e4e4e',
  '#b51212',
  '#396535',
  '#625c21',
  '#145ba2',
  '#7824db',
  '#32635d',
  '#5c4e14',
]

brights = [
  '#584d44',
  '#b51212',
  '#36652f',
  '#864d14',
  '#23617a',
  '#7725db',
  '#32635c',
  '#574e2f',
]

[colors.indexed]
16 = '#995d25'
17 = '#b51419'

[colors.tab_bar]
background = '#d6ebdf'
inactive_tab_edge = '#cbe6d7'

[colors.tab_bar.active_tab]
bg_color = '#2a4e2c'
fg_color = '#e0f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c1e1cf'
fg_color = '#2a4e2c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c1e1cf'
fg_color = '#750202'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#750202'
fg_color = '#e0f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#48039b'
fg_color = '#e0f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 3'