# extras/wezterm/oasis_sol_light_3.toml
## name: Oasis Sol Light 3
## author: uhs-robert

[colors]
foreground = "#1d0f0c"
background= "#f6d0d0"
cursor_bg = "#ae262a"
cursor_border = "#ae262a"
cursor_fg= "#f6d0d0"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#7f1f1f"
compose_cursor= "#885321"
scrollbar_thumb= "#efa9a9"
visual_bell= "#f4c3c3"

ansi = [
  '#434343',
  '#9f1010',
  '#32582e',
  '#56501c',
  '#11508e',
  '#691fc0',
  '#2c5651',
  '#4f4211',
]

brights = [
  '#4b413a',
  '#9f1010',
  '#2f5829',
  '#754312',
  '#1e556a',
  '#6820c1',
  '#2c5650',
  '#4a4328',
]

[colors.indexed]
16 = '#885321'
17 = '#68490b'

[colors.tab_bar]
background = '#f4c3c3'
inactive_tab_edge = '#f1b6b6'

[colors.tab_bar.active_tab]
bg_color = '#750202'
fg_color = '#f6d0d0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#efa9a9'
fg_color = '#750202'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#efa9a9'
fg_color = '#703c08'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#703c08'
fg_color = '#f6d0d0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#31732b'
fg_color = '#f6d0d0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 3'