# extras/wezterm/oasis_moonlight_light_3.toml
## name: Oasis Moonlight Light 3
## author: uhs-robert

[colors]
foreground = "#161412"
background= "#e8e5d8"
cursor_bg = "#6f631b"
cursor_border = "#6f631b"
cursor_fg= "#e8e5d8"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#465c72"
compose_cursor= "#935924"
scrollbar_thumb= "#d1cbb2"
visual_bell= "#dfdbca"

ansi = [
  '#404040',
  '#ad1111',
  '#366032',
  '#5e571f',
  '#13579b',
  '#7322d1',
  '#305e59',
  '#4b3f10',
]

brights = [
  '#483f38',
  '#ad1111',
  '#33602c',
  '#7f4913',
  '#215d74',
  '#7122d2',
  '#305e57',
  '#474026',
]

[colors.indexed]
16 = '#935924'
17 = '#ac1318'

[colors.tab_bar]
background = '#dfdbca'
inactive_tab_edge = '#e2dfce'

[colors.tab_bar.active_tab]
bg_color = '#253b53'
fg_color = '#e8e5d8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#d1cbb2'
fg_color = '#253b53'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d1cbb2'
fg_color = '#685f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#685f10'
fg_color = '#e8e5d8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#9b0303'
fg_color = '#e8e5d8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Moonlight Light 3'