# extras/wezterm/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors]
foreground = "#0c131d"
background= "#d1e3f5"
cursor_bg = "#6c601a"
cursor_border = "#6c601a"
cursor_fg= "#d1e3f5"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#384a5c"
compose_cursor= "#8f5723"
scrollbar_thumb= "#abcced"
visual_bell= "#c4dbf3"

ansi = [
  '#224589',
  '#a81111',
  '#355d31',
  '#5b551e',
  '#125596',
  '#7021cb',
  '#2e5b56',
  '#544712',
]

brights = [
  '#3d4956',
  '#a81111',
  '#325e2b',
  '#7c4713',
  '#205a71',
  '#6e21cc',
  '#2e5b55',
  '#50482b',
]

[colors.indexed]
16 = '#8f5723'
17 = '#a81217'

[colors.tab_bar]
background = '#c4dbf3'
inactive_tab_edge = '#b7d4f0'

[colors.tab_bar.active_tab]
bg_color = '#253b53'
fg_color = '#d1e3f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#abcced'
fg_color = '#253b53'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#abcced'
fg_color = '#685f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#685f10'
fg_color = '#d1e3f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#9b0303'
fg_color = '#d1e3f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 3'