# extras/wezterm/oasis_luna_light_3.toml
## name: Oasis Luna Light 3
## author: uhs-robert

[colors]
foreground = "#3e3366"
background= "#cbc9ee"
cursor_bg = "#504713"
cursor_border = "#504713"
cursor_fg= "#cbc9ee"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#4e257c"
compose_cursor= "#553315"
scrollbar_thumb= "#a9a6e2"
visual_bell= "#bfbdea"

ansi = [
  '#3b3b3b',
  '#900f0f',
  '#2d4f2a',
  '#4d481a',
  '#104880',
  '#5f1cad',
  '#274e49',
  '#453a0f',
]

brights = [
  '#423a33',
  '#900f0f',
  '#2a5025',
  '#693c10',
  '#1b4c60',
  '#5e1daf',
  '#274e48',
  '#413b23',
]

[colors.indexed]
16 = '#553315'
17 = '#901014'

[colors.tab_bar]
background = '#bfbdea'
inactive_tab_edge = '#b4b2e6'

[colors.tab_bar.active_tab]
bg_color = '#817613'
fg_color = '#cbc9ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#a9a6e2'
fg_color = '#817613'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#a9a6e2'
fg_color = '#4a039b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#4a039b'
fg_color = '#cbc9ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#156e89'
fg_color = '#cbc9ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 3'