# extras/wezterm/oasis_scorpion_light_3.toml
## name: Oasis Scorpion Light 3
## author: uhs-robert

[colors]
foreground = "#191210"
background= "#f4cfc3"
cursor_bg = "#655a18"
cursor_border = "#655a18"
cursor_fg= "#f4cfc3"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#5b3a2e"
compose_cursor= "#865221"
scrollbar_thumb= "#edb09c"
visual_bell= "#efbaa9"

ansi = [
  '#373737',
  '#9d1010',
  '#31562d',
  '#554f1c',
  '#114f8b',
  '#681fbd',
  '#2b5550',
  '#41370e',
]

brights = [
  '#3e3630',
  '#9d1010',
  '#2e5728',
  '#734211',
  '#1e5469',
  '#661fbe',
  '#2b554f',
  '#3d3721',
]

[colors.indexed]
16 = '#865221'
17 = '#9c1116'

[colors.tab_bar]
background = '#efbaa9'
inactive_tab_edge = '#f2c5b6'

[colors.tab_bar.active_tab]
bg_color = '#685f10'
fg_color = '#f4cfc3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#edb09c'
fg_color = '#685f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#edb09c'
fg_color = '#6f2009'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#6f2009'
fg_color = '#f4cfc3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#31732b'
fg_color = '#f4cfc3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Scorpion Light 3'