# extras/wezterm/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors]
foreground = "#51402c"
background= "#c4dbf3"
cursor_bg = "#764212"
cursor_border = "#764212"
cursor_fg= "#c4dbf3"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#344455"
compose_cursor= "#5f3a17"
scrollbar_thumb= "#9ec4eb"
visual_bell= "#b7d4f0"

ansi = [
  '#5b3a32',
  '#9f1010',
  '#31572e',
  '#56501c',
  '#11508d',
  '#691fbf',
  '#2c5651',
  '#4e4211',
]

brights = [
  '#563d2f',
  '#9f1010',
  '#2f5829',
  '#744211',
  '#1e546a',
  '#681fc0',
  '#2c5650',
  '#4a4228',
]

[colors.indexed]
16 = '#5f3a17'
17 = '#9e1116'

[colors.tab_bar]
background = '#b7d4f0'
inactive_tab_edge = '#abcced'

[colors.tab_bar.active_tab]
bg_color = '#2d4967'
fg_color = '#c4dbf3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#9ec4eb'
fg_color = '#2d4967'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#9ec4eb'
fg_color = '#897e15'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#897e15'
fg_color = '#c4dbf3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#9b0303'
fg_color = '#c4dbf3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 3'