# extras/wezterm/oasis_twilight_light_3.toml
## name: Oasis Twilight Light 3
## author: uhs-robert

[colors]
foreground = "#4d3f51"
background= "#f5d3c7"
cursor_bg = "#774312"
cursor_border = "#774312"
cursor_fg= "#f5d3c7"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#6e3320"
compose_cursor= "#613b18"
scrollbar_thumb= "#edb4a0"
visual_bell= "#f2c9ba"

ansi = [
  '#444444',
  '#a11010',
  '#32582e',
  '#57511d',
  '#11518f',
  '#6a1fc1',
  '#2c5752',
  '#504311',
]

brights = [
  '#4b423b',
  '#a11010',
  '#2f5929',
  '#764312',
  '#1f566b',
  '#6920c3',
  '#2c5751',
  '#4b4328',
]

[colors.indexed]
16 = '#613b18'
17 = '#a01116'

[colors.tab_bar]
background = '#f2c9ba'
inactive_tab_edge = '#f0bead'

[colors.tab_bar.active_tab]
bg_color = '#89280b'
fg_color = '#f5d3c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#edb4a0'
fg_color = '#89280b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#edb4a0'
fg_color = '#48039b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#48039b'
fg_color = '#f5d3c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#897e15'
fg_color = '#f5d3c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight Light 3'