# extras/wezterm/oasis_rose_light_3.toml
## name: Oasis Rose Light 3
## author: uhs-robert

[colors]
foreground = "#1a0f12"
background= "#f4ddec"
cursor_bg = "#a1405e"
cursor_border = "#a1405e"
cursor_fg= "#f4ddec"
selection_bg= "#dba3c6"
selection_fg= "#481335"
split= "#633f4a"
compose_cursor= "#925823"
scrollbar_thumb= "#e9bad9"
visual_bell= "#f0d1e6"

ansi = [
  '#494949',
  '#ab1111',
  '#365f32',
  '#5d561f',
  '#135699',
  '#7121ce',
  '#2f5d58',
  '#564812',
]

brights = [
  '#52473f',
  '#ab1111',
  '#335f2c',
  '#7e4813',
  '#215c73',
  '#7022d0',
  '#2f5d56',
  '#51492c',
]

[colors.indexed]
16 = '#925823'
17 = '#ab1318'

[colors.tab_bar]
background = '#f0d1e6'
inactive_tab_edge = '#edc6df'

[colors.tab_bar.active_tab]
bg_color = '#572133'
fg_color = '#f4ddec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9bad9'
fg_color = '#572133'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9bad9'
fg_color = '#2a4e2b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2a4e2b'
fg_color = '#f4ddec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2f6f65'
fg_color = '#f4ddec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose Light 3'