# extras/wezterm/oasis_desert_light_3.toml
## name: Oasis Desert Light 3
## author: uhs-robert

[colors]
foreground = "#191510"
background= "#f4f1dd"
cursor_bg = "#776a1d"
cursor_border = "#776a1d"
cursor_fg= "#f4f1dd"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#992525"
compose_cursor= "#9d5f26"
scrollbar_thumb= "#e9e3ba"
visual_bell= "#f0ecd1"

ansi = [
  '#515151',
  '#ba1313',
  '#3b6736',
  '#655e21',
  '#145ea7',
  '#7b28dc',
  '#346560',
  '#5f5014',
]

brights = [
  '#5a4f46',
  '#ba1313',
  '#376830',
  '#894f15',
  '#24647d',
  '#7a2adc',
  '#34655e',
  '#5a5130',
]

[colors.indexed]
16 = '#9d5f26'
17 = '#b9141a'

[colors.tab_bar]
background = '#f0ecd1'
inactive_tab_edge = '#ede7c6'

[colors.tab_bar.active_tab]
bg_color = '#685f10'
fg_color = '#f4f1dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9e3ba'
fg_color = '#685f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9e3ba'
fg_color = '#750202'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#750202'
fg_color = '#f4f1dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#31732b'
fg_color = '#f4f1dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 3'