# extras/wezterm/oasis_midnight_light_2.toml
## name: Oasis Midnight Light 2
## author: uhs-robert

[colors]
foreground = "#534a44"
background= "#f2e6d4"
cursor_bg = "#625818"
cursor_border = "#625818"
cursor_fg= "#f2e6d4"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#902222"
compose_cursor= "#6c4219"
scrollbar_thumb= "#e8d1b0"
visual_bell= "#efdfc8"

ansi = [
  '#4c4c4c',
  '#b01212',
  '#376134',
  '#5f5920',
  '#13589e',
  '#7523d4',
  '#31605a',
  '#594b13',
]

brights = [
  '#554a42',
  '#b01212',
  '#34622d',
  '#814a13',
  '#225e76',
  '#7323d5',
  '#316059',
  '#544c2d',
]

[colors.indexed]
16 = '#6c4219'
17 = '#af1319'

[colors.tab_bar]
background = '#efdfc8'
inactive_tab_edge = '#ebd8bc'

[colors.tab_bar.active_tab]
bg_color = '#766f28'
fg_color = '#f2e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8d1b0'
fg_color = '#766f28'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8d1b0'
fg_color = '#a30505'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a30505'
fg_color = '#f2e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#357a2f'
fg_color = '#f2e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Light 2'