# extras/wezterm/oasis_dune_light_2.toml
## name: Oasis Dune Light 2
## author: uhs-robert

[colors]
foreground = "#171613"
background= "#f9f0e1"
cursor_bg = "#766a1d"
cursor_border = "#766a1d"
cursor_fg= "#f9f0e1"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#646244"
compose_cursor= "#9d6025"
scrollbar_thumb= "#efd7ae"
visual_bell= "#f5e6ce"

ansi = [
  '#474747',
  '#ba1313',
  '#3b6837',
  '#655f22',
  '#155ea8',
  '#7c29dc',
  '#346660',
  '#534611',
]

brights = [
  '#50453e',
  '#bb1313',
  '#376830',
  '#8a4f14',
  '#24647e',
  '#7b2bdc',
  '#34665e',
  '#4f472a',
]

[colors.indexed]
16 = '#9d6025'
17 = '#ba141b'

[colors.tab_bar]
background = '#f5e6ce'
inactive_tab_edge = '#f6ead4'

[colors.tab_bar.active_tab]
bg_color = '#615b21'
fg_color = '#f9f0e1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#efd7ae'
fg_color = '#615b21'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#efd7ae'
fg_color = '#275b53'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#275b53'
fg_color = '#f9f0e1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#4c05a3'
fg_color = '#f9f0e1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 2'