# extras/wezterm/oasis_twilight_light_2.toml
## name: Oasis Twilight Light 2
## author: uhs-robert

[colors]
foreground = "#534355"
background= "#f2ddd4"
cursor_bg = "#7e4614"
cursor_border = "#7e4614"
cursor_fg= "#f2ddd4"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#753523"
compose_cursor= "#673f18"
scrollbar_thumb= "#e8c0b0"
visual_bell= "#efd3c8"

ansi = [
  '#484848',
  '#a91111',
  '#355d32',
  '#5b551f',
  '#135598',
  '#7021cb',
  '#2f5b56',
  '#544712',
]

brights = [
  '#51463f',
  '#a91111',
  '#325e2c',
  '#7c4712',
  '#215a71',
  '#6f22cc',
  '#2f5c55',
  '#50482a',
]

[colors.indexed]
16 = '#673f18'
17 = '#a81218'

[colors.tab_bar]
background = '#efd3c8'
inactive_tab_edge = '#ebcabc'

[colors.tab_bar.active_tab]
bg_color = '#912c0d'
fg_color = '#f2ddd4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8c0b0'
fg_color = '#912c0d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8c0b0'
fg_color = '#4c05a3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#4c05a3'
fg_color = '#f2ddd4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#918517'
fg_color = '#f2ddd4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight Light 2'