# extras/wezterm/oasis_rose_light_2.toml
## name: Oasis Rose Light 2
## author: uhs-robert

[colors]
foreground = "#1d1115"
background= "#f9ecf4"
cursor_bg = "#ad4566"
cursor_border = "#ad4566"
cursor_fg= "#f9ecf4"
selection_bg= "#dba3c6"
selection_fg= "#481335"
split= "#6c4552"
compose_cursor= "#9c5f25"
scrollbar_thumb= "#eec9e0"
visual_bell= "#f5e0ed"

ansi = [
  '#505050',
  '#b91313',
  '#3a6636',
  '#645e22',
  '#145da7',
  '#7a28db',
  '#34655f',
  '#5e5014',
]

brights = [
  '#5a4e46',
  '#b91313',
  '#376730',
  '#894e14',
  '#24637d',
  '#7929dc',
  '#33655d',
  '#59502f',
]

[colors.indexed]
16 = '#9c5f25'
17 = '#b8141b'

[colors.tab_bar]
background = '#f5e0ed'
inactive_tab_edge = '#f2d5e7'

[colors.tab_bar.active_tab]
bg_color = '#5e2438'
fg_color = '#f9ecf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eec9e0'
fg_color = '#5e2438'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eec9e0'
fg_color = '#2e542f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2e542f'
fg_color = '#f9ecf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#33756b'
fg_color = '#f9ecf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose Light 2'