# extras/wezterm/oasis_rose_light_2.toml
## name: Oasis Rose Light 2
## author: uhs-robert

[colors]
foreground = "#6b3f4c"
background= "#d9edd9"
cursor_bg = "#b0131a"
cursor_border = "#b0131a"
cursor_fg= "#d9edd9"
selection_bg= "#dba3c6"
selection_fg= "#481335"
split= "#902222"
compose_cursor= "#6d4219"
scrollbar_thumb= "#badeba"
visual_bell= "#cee8ce"

ansi = [
  '#4c4c4c',
  '#b01212',
  '#376234',
  '#5f5920',
  '#14599f',
  '#7523d4',
  '#31605a',
  '#594b13',
]

brights = [
  '#554a42',
  '#b01212',
  '#34622e',
  '#814a13',
  '#225e77',
  '#7323d5',
  '#316059',
  '#544c2d',
]

[colors.indexed]
16 = '#6d4219'
17 = '#74510d'

[colors.tab_bar]
background = '#cee8ce'
inactive_tab_edge = '#c4e3c4'

[colors.tab_bar.active_tab]
bg_color = '#912c0d'
fg_color = '#d9edd9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#badeba'
fg_color = '#912c0d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#badeba'
fg_color = '#3b6d3d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#3b6d3d'
fg_color = '#d9edd9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#33756b'
fg_color = '#d9edd9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose Light 2'