# extras/wezterm/oasis_desert_light_2.toml
## name: Oasis Desert Light 2
## author: uhs-robert

[colors]
foreground = "#201a14"
background= "#f9f7ec"
cursor_bg = "#7a6e1e"
cursor_border = "#7a6e1e"
cursor_fg= "#f9f7ec"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#a02626"
compose_cursor= "#a26326"
scrollbar_thumb= "#eee8c9"
visual_bell= "#f5f2e0"

ansi = [
  '#545454',
  '#c11313',
  '#3d6b39',
  '#696223',
  '#1561ae',
  '#8030dd',
  '#366963',
  '#635315',
]

brights = [
  '#5f524a',
  '#c11313',
  '#396c32',
  '#8f5215',
  '#256882',
  '#7e31dd',
  '#366a62',
  '#5d5432',
]

[colors.indexed]
16 = '#a26326'
17 = '#c0151c'

[colors.tab_bar]
background = '#f5f2e0'
inactive_tab_edge = '#f2edd5'

[colors.tab_bar.active_tab]
bg_color = '#706712'
fg_color = '#f9f7ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eee8c9'
fg_color = '#706712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eee8c9'
fg_color = '#7e0404'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#7e0404'
fg_color = '#f9f7ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#357a2f'
fg_color = '#f9f7ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 2'