# extras/wezterm/oasis_luna_light_2.toml
## name: Oasis Luna Light 2
## author: uhs-robert

[colors]
foreground = "#524589"
background= "#eeecf9"
cursor_bg = "#635c29"
cursor_border = "#635c29"
cursor_fg= "#eeecf9"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#6731a5"
compose_cursor= "#71451b"
scrollbar_thumb= "#cfc9ee"
visual_bell= "#e4e0f5"

ansi = [
  '#4f4f4f',
  '#b71212',
  '#396536',
  '#635d21',
  '#145ca5',
  '#7925db',
  '#33635d',
  '#5d4e13',
]

brights = [
  '#594d45',
  '#b71212',
  '#36662f',
  '#874d14',
  '#23627b',
  '#7826db',
  '#33645c',
  '#574f2f',
]

[colors.indexed]
16 = '#71451b'
17 = '#b6141a'

[colors.tab_bar]
background = '#e4e0f5'
inactive_tab_edge = '#d9d5f2'

[colors.tab_bar.active_tab]
bg_color = '#887d16'
fg_color = '#eeecf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#cfc9ee'
fg_color = '#887d16'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#cfc9ee'
fg_color = '#4e05a3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#4e05a3'
fg_color = '#eeecf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#187590'
fg_color = '#eeecf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Luna Light 2'