# extras/wezterm/oasis_lagoon_light_2.toml
## name: Oasis Lagoon Light 2
## author: uhs-robert

[colors]
foreground = "#111620"
background= "#e9f2fc"
cursor_bg = "#166cb8"
cursor_border = "#166cb8"
cursor_fg= "#e9f2fc"
selection_bg= "#9fcae0"
selection_fg= "#0f384c"
split= "#276592"
compose_cursor= "#9d6025"
scrollbar_thumb= "#b3d2f5"
visual_bell= "#d5e6f9"

ansi = [
  '#474747',
  '#ba1313',
  '#3b6837',
  '#655f22',
  '#155ea8',
  '#7c29dc',
  '#346660',
  '#534611',
]

brights = [
  '#50453e',
  '#ba1313',
  '#376830',
  '#8a4f14',
  '#24647e',
  '#7a2adc',
  '#34665e',
  '#4f472a',
]

[colors.indexed]
16 = '#9d6025'
17 = '#ba141b'

[colors.tab_bar]
background = '#d5e6f9'
inactive_tab_edge = '#dceafa'

[colors.tab_bar.active_tab]
bg_color = '#054b7d'
fg_color = '#e9f2fc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#b3d2f5'
fg_color = '#054b7d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#b3d2f5'
fg_color = '#78410a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#78410a'
fg_color = '#e9f2fc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#a30505'
fg_color = '#e9f2fc'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Lagoon Light 2'