# extras/wezterm/oasis_abyss_light_2.toml
## name: Oasis Abyss Light 2
## author: uhs-robert

[colors]
foreground = "#534c44"
background= "#f2e9d4"
cursor_bg = "#635918"
cursor_border = "#635918"
cursor_fg= "#f2e9d4"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#922222"
compose_cursor= "#6e431a"
scrollbar_thumb= "#e7d6b1"
visual_bell= "#eee2c9"

ansi = [
  '#4d4d4d',
  '#b21212',
  '#386335',
  '#615a20',
  '#145aa1',
  '#7623d7',
  '#32615b',
  '#5a4c13',
]

brights = [
  '#564b43',
  '#b21212',
  '#35632e',
  '#834b13',
  '#236078',
  '#7524d8',
  '#31615a',
  '#554d2d',
]

[colors.indexed]
16 = '#6e431a'
17 = '#b2131a'

[colors.tab_bar]
background = '#eee2c9'
inactive_tab_edge = '#eadcbd'

[colors.tab_bar.active_tab]
bg_color = '#766f28'
fg_color = '#f2e9d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e7d6b1'
fg_color = '#766f28'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e7d6b1'
fg_color = '#a30505'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a30505'
fg_color = '#f2e9d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#357a2f'
fg_color = '#f2e9d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 2'