# extras/wezterm/oasis_starlight_light_2.toml
## name: Oasis Starlight Light 2
## author: uhs-robert

[colors]
foreground = "#1f1c16"
background= "#faf8f4"
cursor_bg = "#1770c0"
cursor_border = "#1770c0"
cursor_fg= "#faf8f4"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#296a98"
compose_cursor= "#a46426"
scrollbar_thumb= "#e7ddca"
visual_bell= "#f3eee4"

ansi = [
  '#4b4b4b',
  '#c21414',
  '#3d6c3a',
  '#6a6323',
  '#1662b0',
  '#8031dd',
  '#376a64',
  '#584a12',
]

brights = [
  '#544942',
  '#c21414',
  '#3a6d33',
  '#905215',
  '#266984',
  '#7f32dd',
  '#366a63',
  '#534b2c',
]

[colors.indexed]
16 = '#a46426'
17 = '#c2151c'

[colors.tab_bar]
background = '#f3eee4'
inactive_tab_edge = '#f5f1e9'

[colors.tab_bar.active_tab]
bg_color = '#054b7d'
fg_color = '#faf8f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e7ddca'
fg_color = '#054b7d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e7ddca'
fg_color = '#706712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#706712'
fg_color = '#faf8f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#a30505'
fg_color = '#faf8f4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 2'