# extras/wezterm/oasis_sol_light_2.toml
## name: Oasis Sol Light 2
## author: uhs-robert

[colors]
foreground = "#1d0f0c"
background= "#f2c8c8"
cursor_bg = "#a52428"
cursor_border = "#a52428"
cursor_fg= "#f2c8c8"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#781c1c"
compose_cursor= "#824f1e"
scrollbar_thumb= "#e9a3a3"
visual_bell= "#ecafaf"

ansi = [
  '#343434',
  '#970f0f',
  '#2f532c',
  '#514c1b',
  '#114b87',
  '#641eb5',
  '#2a514c',
  '#3d340d',
]

brights = [
  '#3b332d',
  '#970f0f',
  '#2c5427',
  '#6e3f10',
  '#1d5065',
  '#631eb7',
  '#29514b',
  '#3a341f',
]

[colors.indexed]
16 = '#824f1e'
17 = '#63450b'

[colors.tab_bar]
background = '#ecafaf'
inactive_tab_edge = '#efbcbc'

[colors.tab_bar.active_tab]
bg_color = '#7e0404'
fg_color = '#f2c8c8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9a3a3'
fg_color = '#7e0404'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9a3a3'
fg_color = '#78410a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#78410a'
fg_color = '#f2c8c8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#357a2f'
fg_color = '#f2c8c8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 2'