# extras/wezterm/oasis_abyss_light_2.toml
## name: Oasis Abyss Light 2
## author: uhs-robert

[colors]
foreground = "#161412"
background= "#e0e0e0"
cursor_bg = "#6b601a"
cursor_border = "#6b601a"
cursor_fg= "#e0e0e0"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#5c5836"
compose_cursor= "#8e5721"
scrollbar_thumb= "#c1c1c1"
visual_bell= "#d5d5d5"

ansi = [
  '#3d3d3d',
  '#a81111',
  '#345c31',
  '#5b551e',
  '#135497',
  '#6f21ca',
  '#2f5b55',
  '#483d0f',
]

brights = [
  '#453b35',
  '#a81111',
  '#315d2b',
  '#7b4712',
  '#205971',
  '#6e21cb',
  '#2e5b54',
  '#443d24',
]

[colors.indexed]
16 = '#8e5721'
17 = '#a71218'

[colors.tab_bar]
background = '#d5d5d5'
inactive_tab_edge = '#d8d8d8'

[colors.tab_bar.active_tab]
bg_color = '#615b21'
fg_color = '#e0e0e0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c1c1c1'
fg_color = '#615b21'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c1c1c1'
fg_color = '#7e0404'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#7e0404'
fg_color = '#e0e0e0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#357a2f'
fg_color = '#e0e0e0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 2'