# extras/wezterm/oasis_night_dark.toml
## name: Oasis Night Dark
## author: uhs-robert

[colors]
foreground = "#E8F1FF"
background= "#050F23"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#050F23"
selection_bg= "#666666"
selection_fg= "#E8F1FF"
split= "#7FA3C9"
compose_cursor= "#FF9633"
scrollbar_thumb= "#122444"
visual_bell= "#0B1832"

ansi = [
  '#050F23',
  '#FF7979',
  '#7FCF78',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#FFF7D7',
]

brights = [
  '#536B83',
  '#FFA0A0',
  '#A3E39A',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#F7F4E9',
]

[colors.indexed]
16 = '#FF9633'
17 = '#FF7979'

[colors.tab_bar]
background = '#0B1832'
inactive_tab_edge = '#020A19'

[colors.tab_bar.active_tab]
bg_color = '#7FA3C9'
fg_color = '#050F23'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#122444'
fg_color = '#7FA3C9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#122444'
fg_color = '#F0E68C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F0E68C'
fg_color = '#050F23'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#FFA0A0'
fg_color = '#050F23'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Dark'