# extras/kitty/oasis_night_light_3.conf
## name: Oasis Night Light 3
## author: uhs-robert

# Palette
color0                   #224589
color8                   #3d4956

color1                   #a81111
color9                   #a81111

color2                   #355d31
color10                  #325e2b

color3                   #5b551e
color11                  #7c4713

color4                   #125596
color12                  #205a71

color5                   #7021cb
color13                  #6e21cc

color6                   #2e5b56
color14                  #2e5b55

color7                   #544712
color15                  #50482b

# Core
foreground               #0c131d
background               #d1e3f5

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #6c601a
cursor_text_color        #d1e3f5

# Borders (panes)
active_border_color      #384a5c
inactive_border_color    #c4dbf3

# Tabs
active_tab_foreground    #d1e3f5
active_tab_background    #253b53
inactive_tab_foreground  #253b53
inactive_tab_background  #c4dbf3
