# extras/kitty/oasis_luna_light_3.conf
## name: Oasis Luna Light 3
## author: uhs-robert

# Palette
color0                   #474747
color8                   #4f453d

color1                   #a61111
color9                   #a61111

color2                   #345c30
color10                  #315c2b

color3                   #5a541e
color11                  #7a4612

color4                   #125494
color12                  #20596f

color5                   #6e21c8
color13                  #6d21ca

color6                   #2e5a55
color14                  #2e5a54

color7                   #534612
color15                  #4e472a

# Core
foreground               #100e1b
background               #deddf4

# Selection
selection_background     #c3a1dd
selection_foreground     #31124a

# Cursor
cursor                   #6b5f1a
cursor_text_color        #deddf4

# Borders (panes)
active_border_color      #3d3d8d
inactive_border_color    #d3d1f0

# Tabs
active_tab_foreground    #deddf4
active_tab_background    #685f10
inactive_tab_foreground  #685f10
inactive_tab_background  #d3d1f0
