# extras/kitty/oasis_scorpion_light_3.conf
## name: Oasis Scorpion Light 3
## author: uhs-robert

# Palette
color0                   #424242
color8                   #4a413a

color1                   #9e1010
color9                   #9e1010

color2                   #31572e
color10                  #2f5829

color3                   #56501c
color11                  #744211

color4                   #11508d
color12                  #1e546a

color5                   #691fbf
color13                  #671fc0

color6                   #2c5551
color14                  #2c5650

color7                   #4e4211
color15                  #4a4228

# Core
foreground               #543e35
background               #f4d1c3

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #594f15
cursor_text_color        #f4d1c3

# Borders (panes)
active_border_color      #5c3a2f
inactive_border_color    #f1c7b6

# Tabs
active_tab_foreground    #f4d1c3
active_tab_background    #817613
inactive_tab_foreground  #817613
inactive_tab_background  #f1c7b6
