# extras/kitty/oasis_midnight_light_3.conf
## name: Oasis Midnight Light 3
## author: uhs-robert

# Palette
color0                   #3c3c3c
color8                   #433a34

color1                   #a51111
color9                   #a51111

color2                   #345b30
color10                  #315c2a

color3                   #59531e
color11                  #794512

color4                   #125393
color12                  #1f586e

color5                   #6d20c7
color13                  #6c21c8

color6                   #2d5954
color14                  #2d5a53

color7                   #463b0f
color15                  #423c24

# Core
foreground               #161412
background               #d9dee8

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #6a5e1a
cursor_text_color        #d9dee8

# Borders (panes)
active_border_color      #852020
inactive_border_color    #c6cddc

# Tabs
active_tab_foreground    #d9dee8
active_tab_background    #5a551e
inactive_tab_foreground  #5a551e
inactive_tab_background  #c6cddc
