# extras/kitty/oasis_night_light_3.conf
## name: Oasis Night Light 3
## author: uhs-robert

# Palette
color0                   #5b3a32
color8                   #563d2f

color1                   #9f1010
color9                   #9f1010

color2                   #31572e
color10                  #2f5829

color3                   #56501c
color11                  #744211

color4                   #11508d
color12                  #1e546a

color5                   #691fbf
color13                  #681fc0

color6                   #2c5651
color14                  #2c5650

color7                   #4e4211
color15                  #4a4228

# Core
foreground               #51402c
background               #c4dbf3

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #764212
cursor_text_color        #c4dbf3

# Borders (panes)
active_border_color      #344455
inactive_border_color    #b7d4f0

# Tabs
active_tab_foreground    #c4dbf3
active_tab_background    #2d4967
inactive_tab_foreground  #2d4967
inactive_tab_background  #b7d4f0
