# extras/kitty/oasis_twilight_light_3.conf
## name: Oasis Twilight Light 3
## author: uhs-robert

# Palette
color0                   #444444
color8                   #4b423b

color1                   #a11010
color9                   #a11010

color2                   #32582e
color10                  #2f5929

color3                   #57511d
color11                  #764312

color4                   #11518f
color12                  #1f566b

color5                   #6a1fc1
color13                  #6920c3

color6                   #2c5752
color14                  #2c5751

color7                   #504311
color15                  #4b4328

# Core
foreground               #4d3f51
background               #f5d3c7

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #774312
cursor_text_color        #f5d3c7

# Borders (panes)
active_border_color      #6e3320
inactive_border_color    #f2c9ba

# Tabs
active_tab_foreground    #f5d3c7
active_tab_background    #89280b
inactive_tab_foreground  #89280b
inactive_tab_background  #f2c9ba
