# extras/kitty/oasis_sol_light_3.conf
## name: Oasis Sol Light 3
## author: uhs-robert

# Palette
color0                   #323232
color8                   #38312c

color1                   #930f0f
color9                   #930f0f

color2                   #2e512a
color10                  #2b5126

color3                   #4f4a1a
color11                  #6b3e10

color4                   #104a83
color12                  #1c4e62

color5                   #611db1
color13                  #601db2

color6                   #284f4b
color14                  #284f4a

color7                   #3b320d
color15                  #38321e

# Core
foreground               #1d0f0c
background               #f2c4c4

# Selection
selection_background     #e19d9d
selection_foreground     #4e0e0e

# Cursor
cursor                   #a22327
cursor_text_color        #f2c4c4

# Borders (panes)
active_border_color      #6a441e
inactive_border_color    #eeb1b1

# Tabs
active_tab_foreground    #f2c4c4
active_tab_background    #750202
inactive_tab_foreground  #750202
inactive_tab_background  #eeb1b1
