# extras/kitty/oasis_twilight_light_3.conf
## name: Oasis Twilight Light 3
## author: uhs-robert

# Palette
color0                   #3f3f3f
color8                   #463d37

color1                   #ab1111
color9                   #ab1111

color2                   #365f32
color10                  #335f2c

color3                   #5d561f
color11                  #7e4813

color4                   #135699
color12                  #215b73

color5                   #7121ce
color13                  #7022d0

color6                   #2f5d58
color14                  #2f5d56

color7                   #4a3e10
color15                  #463f26

# Core
foreground               #161217
background               #eadff4

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #925117
cursor_text_color        #eadff4

# Borders (panes)
active_border_color      #6e42a4
inactive_border_color    #dfceee

# Tabs
active_tab_foreground    #eadff4
active_tab_background    #6f2009
inactive_tab_foreground  #6f2009
inactive_tab_background  #dfceee
