# extras/kitty/oasis_mirage_light_3.conf
## name: Oasis Mirage Light 3
## author: uhs-robert

# Palette
color0                   #454545
color8                   #4c433b

color1                   #b61212
color9                   #b61212

color2                   #396535
color10                  #36652f

color3                   #635c21
color11                  #864d14

color4                   #145ca3
color12                  #23617a

color5                   #7824db
color13                  #7725db

color6                   #386357
color14                  #366356

color7                   #464621
color15                  #47470f

# Core
foreground               #181811
background               #d8f2ef

# Selection
selection_background     #aae3dc
selection_foreground     #404021

# Cursor
cursor                   #367261
cursor_text_color        #d8f2ef

# Borders (panes)
active_border_color      #44655d
inactive_border_color    #c7ece8

# Tabs
active_tab_foreground    #d8f2ef
active_tab_background    #235547
inactive_tab_foreground  #235547
inactive_tab_background  #c7ece8
