# extras/kitty/oasis_scorpion_light_3.conf
## name: Oasis Scorpion Light 3
## author: uhs-robert

# Palette
color0                   #373737
color8                   #3e3630

color1                   #9d1010
color9                   #9d1010

color2                   #31562d
color10                  #2e5728

color3                   #554f1c
color11                  #734211

color4                   #114f8b
color12                  #1e5469

color5                   #681fbd
color13                  #661fbe

color6                   #2b5550
color14                  #2b554f

color7                   #41370e
color15                  #3d3721

# Core
foreground               #191210
background               #f4cfc3

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #655a18
cursor_text_color        #f4cfc3

# Borders (panes)
active_border_color      #5b3a2e
inactive_border_color    #efbaa9

# Tabs
active_tab_foreground    #f4cfc3
active_tab_background    #685f10
inactive_tab_foreground  #685f10
inactive_tab_background  #efbaa9
