# extras/kitty/oasis_rose_light_3.conf
## name: Oasis Rose Light 3
## author: uhs-robert

# Palette
color0                   #3c3c3c
color8                   #433a34

color1                   #a51111
color9                   #a51111

color2                   #345b30
color10                  #315c2a

color3                   #59531e
color11                  #794512

color4                   #125393
color12                  #1f586f

color5                   #6d20c7
color13                  #6c21c8

color6                   #2e5954
color14                  #2d5a53

color7                   #473b0f
color15                  #423c24

# Core
foreground               #1a0f12
background               #f3d6e8

# Selection
selection_background     #dba3c6
selection_foreground     #481335

# Cursor
cursor                   #9c3e5b
cursor_text_color        #f3d6e8

# Borders (panes)
active_border_color      #734a56
inactive_border_color    #eec4de

# Tabs
active_tab_foreground    #f3d6e8
active_tab_background    #572133
inactive_tab_foreground  #572133
inactive_tab_background  #eec4de
