# extras/kitty/oasis_lagoon_light_3.conf
## name: Oasis Lagoon Light 3
## author: uhs-robert

# Palette
color0                   #4a4a4a
color8                   #524840

color1                   #ac1111
color9                   #ac1111

color2                   #365f32
color10                  #33602c

color3                   #5d571f
color11                  #7f4813

color4                   #13579a
color12                  #215c73

color5                   #7222cf
color13                  #7122d1

color6                   #2f5d58
color14                  #305e57

color7                   #564912
color15                  #52492c

# Core
foreground               #0e131b
background               #d9e5f7

# Selection
selection_background     #9fcae0
selection_foreground     #0f384c

# Cursor
cursor                   #1464aa
cursor_text_color        #d9e5f7

# Borders (panes)
active_border_color      #1e4e6f
inactive_border_color    #ccdcf4

# Tabs
active_tab_foreground    #d9e5f7
active_tab_background    #044574
inactive_tab_foreground  #044574
inactive_tab_background  #ccdcf4
