# extras/alacritty/themes/light/2/oasis_luna_light_2.toml
## name: Oasis Luna Light 2
## author: uhs-robert

[colors.primary]
background = '#eeecfb'
foreground = '#181811'

[colors.selection]
background = '#c1b9f0'
text = '#181811'

[colors.cursor]
cursor = '#72692e'
text = '#eeecfb'

[colors.vi_mode_cursor]
cursor = '#874d14'
text = '#eeecfb'

[colors.normal]
black   = '#454545'
red     = '#b71212'
green   = '#3a6536'
yellow  = '#635c21'
blue    = '#145ca5'
magenta = '#7925db'
cyan    = '#386357'
white   = '#474721'

[colors.bright]
black   = '#4e433c'
red     = '#b71212'
green   = '#36662f'
yellow  = '#874d14'
blue    = '#23627b'
magenta = '#7826db'
cyan    = '#366456'
white   = '#47470f'