# extras/alacritty/themes/light/2/oasis_luna_light_2.toml
## name: Oasis Luna Light 2
## author: uhs-robert

[colors.primary]
background = '#eeecf9'
foreground = '#524589'

[colors.selection]
background = '#cfc9ee'
text = '#524589'

[colors.cursor]
cursor = '#635c29'
text = '#eeecf9'

[colors.vi_mode_cursor]
cursor = '#874d14'
text = '#eeecf9'

[colors.normal]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#396536'
yellow  = '#635d21'
blue    = '#145ca5'
magenta = '#7925db'
cyan    = '#33635d'
white   = '#5d4e13'

[colors.bright]
black   = '#594d45'
red     = '#b71212'
green   = '#36662f'
yellow  = '#874d14'
blue    = '#23627b'
magenta = '#7826db'
cyan    = '#33645c'
white   = '#574f2f'