# extras/alacritty/themes/light/2/oasis_starlight_light_2.toml
## name: Oasis Starlight Light 2
## author: uhs-robert

[colors.primary]
background = '#f9f5ec'
foreground = '#1c1a14'

[colors.selection]
background = '#eee3c9'
text = '#1c1a14'

[colors.cursor]
cursor = '#166fbc'
text = '#f9f5ec'

[colors.vi_mode_cursor]
cursor = '#8d5115'
text = '#f9f5ec'

[colors.normal]
black   = '#545454'
red     = '#bf1313'
green   = '#3c6a38'
yellow  = '#686123'
blue    = '#1561ad'
magenta = '#7f2edd'
cyan    = '#366862'
white   = '#625315'

[colors.bright]
black   = '#5e5149'
red     = '#bf1313'
green   = '#396b32'
yellow  = '#8d5115'
blue    = '#256781'
magenta = '#7d2fdd'
cyan    = '#356961'
white   = '#5c5331'