# extras/alacritty/themes/light/2/oasis_lagoon_light_2.toml
## name: Oasis Lagoon Light 2
## author: uhs-robert

[colors.primary]
background = '#e9f2fc'
foreground = '#181811'

[colors.selection]
background = '#b3d2f5'
text = '#181811'

[colors.cursor]
cursor = '#1668cc'
text = '#e9f2fc'

[colors.vi_mode_cursor]
cursor = '#8a4f14'
text = '#e9f2fc'

[colors.normal]
black   = '#474747'
red     = '#ba1313'
green   = '#3b6837'
yellow  = '#655f22'
blue    = '#155ea8'
magenta = '#7c29dc'
cyan    = '#396559'
white   = '#494922'

[colors.bright]
black   = '#50453e'
red     = '#ba1313'
green   = '#376830'
yellow  = '#8a4f14'
blue    = '#24647e'
magenta = '#7a2adc'
cyan    = '#376658'
white   = '#4a4a0f'