# extras/alacritty/themes/light/2/oasis_midnight_light_2.toml
## name: Oasis Midnight Light 2
## author: uhs-robert

[colors.primary]
background = '#f2e6d4'
foreground = '#534a44'

[colors.selection]
background = '#e8d1b0'
text = '#534a44'

[colors.cursor]
cursor = '#625818'
text = '#f2e6d4'

[colors.vi_mode_cursor]
cursor = '#814a13'
text = '#f2e6d4'

[colors.normal]
black   = '#4c4c4c'
red     = '#b01212'
green   = '#376134'
yellow  = '#5f5920'
blue    = '#13589e'
magenta = '#7523d4'
cyan    = '#31605a'
white   = '#594b13'

[colors.bright]
black   = '#554a42'
red     = '#b01212'
green   = '#34622d'
yellow  = '#814a13'
blue    = '#225e76'
magenta = '#7323d5'
cyan    = '#316059'
white   = '#544c2d'