# extras/alacritty/themes/light/2/oasis_scorpion_light_2.toml
## name: Oasis Scorpion Light 2
## author: uhs-robert

[colors.primary]
background = '#f8eee7'
foreground = '#1a1311'

[colors.selection]
background = '#eed5c3'
text = '#1a1311'

[colors.cursor]
cursor = '#766a1c'
text = '#f8eee7'

[colors.vi_mode_cursor]
cursor = '#894e14'
text = '#f8eee7'

[colors.normal]
black   = '#505050'
red     = '#b91313'
green   = '#3a6737'
yellow  = '#645e22'
blue    = '#155da7'
magenta = '#7b28dc'
cyan    = '#34655f'
white   = '#5e5014'

[colors.bright]
black   = '#5a4e46'
red     = '#b91313'
green   = '#376830'
yellow  = '#894e14'
blue    = '#24637d'
magenta = '#7a29dc'
cyan    = '#33655e'
white   = '#59502f'