# extras/alacritty/themes/light/2/oasis_sol_light_2.toml
## name: Oasis Sol Light 2
## author: uhs-robert

[colors.primary]
background = '#f2c8c8'
foreground = '#1d0f0c'

[colors.selection]
background = '#e9a3a3'
text = '#1d0f0c'

[colors.cursor]
cursor = '#a52428'
text = '#f2c8c8'

[colors.vi_mode_cursor]
cursor = '#6e3f10'
text = '#f2c8c8'

[colors.normal]
black   = '#343434'
red     = '#970f0f'
green   = '#2f532c'
yellow  = '#514c1b'
blue    = '#114b87'
magenta = '#641eb5'
cyan    = '#2a514c'
white   = '#3d340d'

[colors.bright]
black   = '#3b332d'
red     = '#970f0f'
green   = '#2c5427'
yellow  = '#6e3f10'
blue    = '#1d5065'
magenta = '#631eb7'
cyan    = '#29514b'
white   = '#3a341f'