# extras/alacritty/themes/light/2/oasis_cactus_light_2.toml
## name: Oasis Cactus Light 2
## author: uhs-robert

[colors.primary]
background = '#e7f4eb'
foreground = '#181811'

[colors.selection]
background = '#bde1c8'
text = '#181811'

[colors.cursor]
cursor = '#447447'
text = '#e7f4eb'

[colors.vi_mode_cursor]
cursor = '#8a4f14'
text = '#e7f4eb'

[colors.normal]
black   = '#474747'
red     = '#ba1313'
green   = '#3b6737'
yellow  = '#655e22'
blue    = '#155ea8'
magenta = '#7b29dc'
cyan    = '#396559'
white   = '#494922'

[colors.bright]
black   = '#50453e'
red     = '#ba1313'
green   = '#376830'
yellow  = '#8a4f14'
blue    = '#24647e'
magenta = '#7a2adc'
cyan    = '#376658'
white   = '#4a4a0f'