# extras/wezterm/oasis_twilight_light_5.toml
## name: Oasis Twilight Light 5
## author: uhs-robert

[colors]
foreground = "#433646"
background= "#f2c1b5"
cursor_bg = "#693c11"
cursor_border = "#693c11"
cursor_fg= "#f2c1b5"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#5f2c1d"
compose_cursor= "#553314"
scrollbar_thumb= "#eba08e"
visual_bell= "#f0b6a8"

ansi = [
  '#3b3b3b',
  '#900e0e',
  '#2c4f29',
  '#4d4819',
  '#0f487f',
  '#5f1cad',
  '#284d49',
  '#453a0e',
]

brights = [
  '#413932',
  '#900e0e',
  '#2a4f25',
  '#693c0f',
  '#1c4c60',
  '#5e1cad',
  '#274d47',
  '#413a23',
]

[colors.indexed]
16 = '#553314'
17 = '#8f1015'

[colors.tab_bar]
background = '#f0b6a8'
inactive_tab_edge = '#eeab9b'

[colors.tab_bar.active_tab]
bg_color = '#782107'
fg_color = '#f2c1b5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eba08e'
fg_color = '#782107'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eba08e'
fg_color = '#3e008a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#3e008a'
fg_color = '#f2c1b5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#7a6f10'
fg_color = '#f2c1b5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight Light 5'