# extras/wezterm/oasis_cactus_light_5.toml
## name: Oasis Cactus Light 5
## author: uhs-robert

[colors]
foreground = "#121714"
background= "#cbebd7"
cursor_bg = "#3f6c41"
cursor_border = "#3f6c41"
cursor_fg= "#cbebd7"
selection_bg= "#a4dac0"
selection_fg= "#15472f"
split= "#3b4e3c"
compose_cursor= "#925823"
scrollbar_thumb= "#aadebe"
visual_bell= "#c0e7cf"

ansi = [
  '#494949',
  '#ab1111',
  '#365f32',
  '#5d571f',
  '#135699',
  '#7122ce',
  '#305d58',
  '#564812',
]

brights = [
  '#51483f',
  '#ab1111',
  '#325f2c',
  '#7e4812',
  '#215c73',
  '#7122cf',
  '#2f5d56',
  '#51492b',
]

[colors.indexed]
16 = '#925823'
17 = '#ab1319'

[colors.tab_bar]
background = '#c0e7cf'
inactive_tab_edge = '#b5e2c6'

[colors.tab_bar.active_tab]
bg_color = '#234124'
fg_color = '#cbebd7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#aadebe'
fg_color = '#234124'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#aadebe'
fg_color = '#630000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#630000'
fg_color = '#cbebd7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#cbebd7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 5'