# extras/wezterm/oasis_scorpion_light_5.toml
## name: Oasis Scorpion Light 5
## author: uhs-robert

[colors]
foreground = "#43322b"
background= "#f0b7a8"
cursor_bg = "#494212"
cursor_border = "#494212"
cursor_fg= "#f0b7a8"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#4a2f26"
compose_cursor= "#4d2e13"
scrollbar_thumb= "#e99781"
visual_bell= "#eeac9b"

ansi = [
  '#353535',
  '#860d0d',
  '#294926',
  '#474318',
  '#0e4376',
  '#581aa0',
  '#254743',
  '#3f350d',
]

brights = [
  '#3b342e',
  '#860d0d',
  '#274922',
  '#61380e',
  '#1a4759',
  '#571aa1',
  '#244842',
  '#3b3520',
]

[colors.indexed]
16 = '#4d2e13'
17 = '#850e13'

[colors.tab_bar]
background = '#eeac9b'
inactive_tab_edge = '#eba28e'

[colors.tab_bar.active_tab]
bg_color = '#71670f'
fg_color = '#f0b7a8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e99781'
fg_color = '#71670f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e99781'
fg_color = '#822408'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#822408'
fg_color = '#f0b7a8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#296624'
fg_color = '#f0b7a8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Scorpion Light 5'