# extras/wezterm/oasis_mirage_light_5.toml
## name: Oasis Mirage Light 5
## author: uhs-robert

[colors]
foreground = "#121717"
background= "#c1eae6"
cursor_bg = "#366a63"
cursor_border = "#366a63"
cursor_fg= "#c1eae6"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#3a5e5a"
compose_cursor= "#905723"
scrollbar_thumb= "#93dbd4"
visual_bell= "#b0e4df"

ansi = [
  '#3e3e3e',
  '#aa1010',
  '#355e31',
  '#5c561e',
  '#125598',
  '#7021cc',
  '#2f5c57',
  '#493e0f',
]

brights = [
  '#453d36',
  '#aa1111',
  '#325f2c',
  '#7d4712',
  '#215a72',
  '#6f22cd',
  '#2f5c55',
  '#453e25',
]

[colors.indexed]
16 = '#905723'
17 = '#a91218'

[colors.tab_bar]
background = '#b0e4df'
inactive_tab_edge = '#b6e6e1'

[colors.tab_bar.active_tab]
bg_color = '#1d4641'
fg_color = '#c1eae6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#93dbd4'
fg_color = '#1d4641'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#93dbd4'
fg_color = '#5f3105'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5f3105'
fg_color = '#c1eae6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#c1eae6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 5'