# extras/wezterm/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors]
foreground = "#0c131d"
background= "#b7d7f0"
cursor_bg = "#615818"
cursor_border = "#615818"
cursor_fg= "#b7d7f0"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#314151"
compose_cursor= "#834f20"
scrollbar_thumb= "#91c2e8"
visual_bell= "#aad0ee"

ansi = [
  '#1e3d78',
  '#980f0f',
  '#2f542c',
  '#514c1b',
  '#104c87',
  '#651eb7',
  '#2a524d',
  '#4a3e0f',
]

brights = [
  '#35404c',
  '#980f0f',
  '#2c5427',
  '#6f3f10',
  '#1d5166',
  '#641eb7',
  '#2a524c',
  '#463f25',
]

[colors.indexed]
16 = '#834f20'
17 = '#971016'

[colors.tab_bar]
background = '#aad0ee'
inactive_tab_edge = '#9ec9eb'

[colors.tab_bar.active_tab]
bg_color = '#1e3146'
fg_color = '#b7d7f0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#91c2e8'
fg_color = '#1e3146'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#91c2e8'
fg_color = '#58500b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#58500b'
fg_color = '#b7d7f0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#8a0000'
fg_color = '#b7d7f0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 5'