# extras/wezterm/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors]
foreground = "#46453d"
background= "#f3d8ba"
cursor_bg = "#5a5216"
cursor_border = "#5a5216"
cursor_fg= "#f3d8ba"
selection_bg= "#e1c99d"
selection_fg= "#4e370e"
split= "#484631"
compose_cursor= "#633c18"
scrollbar_thumb= "#ecc293"
visual_bell= "#f1d1ad"

ansi = [
  '#454545',
  '#a31010',
  '#335a2f',
  '#58521d',
  '#125292',
  '#6c20c4',
  '#2d5853',
  '#514411',
]

brights = [
  '#4d443b',
  '#a31010',
  '#305b2a',
  '#784412',
  '#1f576d',
  '#6b20c5',
  '#2d5952',
  '#4c4529',
]

[colors.indexed]
16 = '#633c18'
17 = '#a31218'

[colors.tab_bar]
background = '#f1d1ad'
inactive_tab_edge = '#eec9a0'

[colors.tab_bar.active_tab]
bg_color = '#615b1e'
fg_color = '#f3d8ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ecc293'
fg_color = '#615b1e'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ecc293'
fg_color = '#286259'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#286259'
fg_color = '#f3d8ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#f3d8ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 5'