# extras/wezterm/oasis_canyon_light_5.toml
## name: Oasis Canyon Light 5
## author: uhs-robert

[colors]
foreground = "#1a150e"
background= "#e8c3a5"
cursor_bg = "#794514"
cursor_border = "#794514"
cursor_fg= "#e8c3a5"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#523214"
compose_cursor= "#675324"
scrollbar_thumb= "#dfab80"
visual_bell= "#e2b38d"

ansi = [
  '#2e2e2e',
  '#8d0e0e',
  '#2c4d29',
  '#4b4619',
  '#0f467d',
  '#5d1ca9',
  '#274c47',
  '#372e0b',
]

brights = [
  '#342e28',
  '#8d0e0e',
  '#294e24',
  '#673b0f',
  '#1b4b5e',
  '#5c1caa',
  '#274c46',
  '#332e1b',
]

[colors.indexed]
16 = '#675324'
17 = '#8c0f14'

[colors.tab_bar]
background = '#e2b38d'
inactive_tab_edge = '#e5bb99'

[colors.tab_bar.active_tab]
bg_color = '#5f3105'
fg_color = '#e8c3a5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#dfab80'
fg_color = '#5f3105'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#dfab80'
fg_color = '#630000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#630000'
fg_color = '#e8c3a5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#145a76'
fg_color = '#e8c3a5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 5'