# extras/wezterm/oasis_cactus_light_5.toml
## name: Oasis Cactus Light 5
## author: uhs-robert

[colors]
foreground = "#121714"
background= "#c7e5d2"
cursor_bg = "#3d683f"
cursor_border = "#3d683f"
cursor_fg= "#c7e5d2"
selection_bg= "#a4dac0"
selection_fg= "#15472f"
split= "#384b39"
compose_cursor= "#8d5522"
scrollbar_thumb= "#a8d6b9"
visual_bell= "#b2dbc1"

ansi = [
  '#3c3c3c',
  '#a51010',
  '#335b30',
  '#59531d',
  '#125393',
  '#6d20c7',
  '#2e5954',
  '#463b0f',
]

brights = [
  '#423b33',
  '#a51010',
  '#305c2b',
  '#794512',
  '#20586f',
  '#6c21c7',
  '#2d5a53',
  '#423c23',
]

[colors.indexed]
16 = '#8d5522'
17 = '#a41218'

[colors.tab_bar]
background = '#b2dbc1'
inactive_tab_edge = '#bde0ca'

[colors.tab_bar.active_tab]
bg_color = '#234124'
fg_color = '#c7e5d2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#a8d6b9'
fg_color = '#234124'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#a8d6b9'
fg_color = '#630000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#630000'
fg_color = '#c7e5d2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#c7e5d2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 5'