# extras/wezterm/oasis_sol_light_5.toml
## name: Oasis Sol Light 5
## author: uhs-robert

[colors]
foreground = "#1d0f0c"
background= "#ecabab"
cursor_bg = "#891f21"
cursor_border = "#891f21"
cursor_fg= "#ecabab"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#583819"
compose_cursor= "#6d421a"
scrollbar_thumb= "#e17979"
visual_bell= "#e89898"

ansi = [
  '#232323',
  '#7b0c0c',
  '#254223',
  '#413c15',
  '#0d3d6c',
  '#511893',
  '#21413d',
  '#292309',
]

brights = [
  '#27221e',
  '#7b0c0c',
  '#23431f',
  '#59330d',
  '#174051',
  '#501893',
  '#21413c',
  '#272315',
]

[colors.indexed]
16 = '#6d421a'
17 = '#4f3709'

[colors.tab_bar]
background = '#e89898'
inactive_tab_edge = '#e99f9f'

[colors.tab_bar.active_tab]
bg_color = '#630000'
fg_color = '#ecabab'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e17979'
fg_color = '#630000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e17979'
fg_color = '#5f3105'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5f3105'
fg_color = '#ecabab'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#296624'
fg_color = '#ecabab'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 5'