# extras/wezterm/oasis_scorpion_light_5.toml
## name: Oasis Scorpion Light 5
## author: uhs-robert

[colors]
foreground = "#191210"
background= "#efbaa9"
cursor_bg = "#585015"
cursor_border = "#585015"
cursor_fg= "#efbaa9"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#4c3026"
compose_cursor= "#77481d"
scrollbar_thumb= "#e89b82"
visual_bell= "#eaa58f"

ansi = [
  '#2c2c2c',
  '#880d0d',
  '#2a4a27',
  '#484418',
  '#0f4478',
  '#5a1ba3',
  '#254945',
  '#332b0b',
]

brights = [
  '#302b25',
  '#880d0d',
  '#284b23',
  '#63390f',
  '#1a485b',
  '#591ba4',
  '#254943',
  '#302b1a',
]

[colors.indexed]
16 = '#77481d'
17 = '#880f14'

[colors.tab_bar]
background = '#eaa58f'
inactive_tab_edge = '#edb09c'

[colors.tab_bar.active_tab]
bg_color = '#58500b'
fg_color = '#efbaa9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e89b82'
fg_color = '#58500b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e89b82'
fg_color = '#5e1a06'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5e1a06'
fg_color = '#efbaa9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#296624'
fg_color = '#efbaa9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Scorpion Light 5'