# extras/wezterm/oasis_mirage_light_5.toml
## name: Oasis Mirage Light 5
## author: uhs-robert

[colors]
foreground = "#121717"
background= "#c0f2ee"
cursor_bg = "#386e66"
cursor_border = "#386e66"
cursor_fg= "#c0f2ee"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#32524f"
compose_cursor= "#965b24"
scrollbar_thumb= "#9aeae4"
visual_bell= "#b3efeb"

ansi = [
  '#4c4c4c',
  '#b11111',
  '#376234',
  '#5f5920',
  '#13599e',
  '#7523d5',
  '#31605b',
  '#594b13',
]

brights = [
  '#554a41',
  '#b11111',
  '#34632e',
  '#824a13',
  '#225f77',
  '#7423d6',
  '#316059',
  '#544c2d',
]

[colors.indexed]
16 = '#965b24'
17 = '#b0131a'

[colors.tab_bar]
background = '#b3efeb'
inactive_tab_edge = '#a7ede7'

[colors.tab_bar.active_tab]
bg_color = '#1d4641'
fg_color = '#c0f2ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#9aeae4'
fg_color = '#1d4641'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#9aeae4'
fg_color = '#5f3105'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5f3105'
fg_color = '#c0f2ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#c0f2ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 5'