# extras/wezterm/oasis_scorpion_light_5.toml
## name: Oasis Scorpion Light 5
## author: uhs-robert

[colors]
foreground = "#191210"
background= "#f3ceba"
cursor_bg = "#635918"
cursor_border = "#635918"
cursor_fg= "#f3ceba"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#5a392e"
compose_cursor= "#855120"
scrollbar_thumb= "#ecb293"
visual_bell= "#f1c5ad"

ansi = [
  '#414141',
  '#9b0f0f',
  '#30552d',
  '#534e1c',
  '#114e8a',
  '#671ebb',
  '#2b544f',
  '#4c4010',
]

brights = [
  '#483f38',
  '#9b0f0f',
  '#2d5628',
  '#724111',
  '#1e5268',
  '#661fbb',
  '#2a544d',
  '#484126',
]

[colors.indexed]
16 = '#855120'
17 = '#9b1116'

[colors.tab_bar]
background = '#f1c5ad'
inactive_tab_edge = '#eebba0'

[colors.tab_bar.active_tab]
bg_color = '#58500b'
fg_color = '#f3ceba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ecb293'
fg_color = '#58500b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ecb293'
fg_color = '#5e1a06'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5e1a06'
fg_color = '#f3ceba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#296624'
fg_color = '#f3ceba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Scorpion Light 5'