# extras/kitty/oasis_abyss_light_2.conf
## name: Oasis Abyss Light 2
## author: uhs-robert

# Palette
color0                   #515151
color8                   #5b4e46

color1                   #ba1313
color9                   #ba1313

color2                   #3a6737
color10                  #376830

color3                   #655e22
color11                  #894e14

color4                   #155ea7
color12                  #24637d

color5                   #7b28dc
color13                  #7a29dc

color6                   #34655f
color14                  #33655e

color7                   #5f5014
color15                  #595130

# Core
foreground               #171513
background               #f0f0f0

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #766a1d
cursor_text_color        #f0f0f0

# Borders (panes)
active_border_color      #992424
inactive_border_color    #e8e8e8

# Tabs
active_tab_foreground    #f0f0f0
active_tab_background    #615b21
inactive_tab_foreground  #615b21
inactive_tab_background  #e8e8e8
