# extras/kitty/oasis_scorpion_light_2.conf
## name: Oasis Scorpion Light 2
## author: uhs-robert

# Palette
color0                   #505050
color8                   #594d45

color1                   #b81212
color9                   #b81313

color2                   #3a6636
color10                  #366730

color3                   #645d21
color11                  #884e14

color4                   #145ca5
color12                  #24627c

color5                   #7a26db
color13                  #7928db

color6                   #33645e
color14                  #33645d

color7                   #5d4f14
color15                  #584f2f

# Core
foreground               #644a40
background               #f8ece7

# Selection
selection_background     #e19d9d
selection_foreground     #4e0e0e

# Cursor
cursor                   #645d29
cursor_text_color        #f8ece7

# Borders (panes)
active_border_color      #6e4638
inactive_border_color    #f5e3db

# Tabs
active_tab_foreground    #f8ece7
active_tab_background    #887d16
inactive_tab_foreground  #887d16
inactive_tab_background  #f5e3db
