# extras/kitty/oasis_dune_light_2.conf
## name: Oasis Dune Light 2
## author: uhs-robert

# Palette
color0                   #525252
color8                   #5c4f47

color1                   #bb1313
color9                   #bc1313

color2                   #3b6837
color10                  #386931

color3                   #665f22
color11                  #8b4f14

color4                   #155fa9
color12                  #24657f

color5                   #7c2adc
color13                  #7b2bdc

color6                   #356660
color14                  #34665f

color7                   #605114
color15                  #5a5230

# Core
foreground               #545249
background               #f8f1e7

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #695e19
cursor_text_color        #f8f1e7

# Borders (panes)
active_border_color      #55533a
inactive_border_color    #f5eadb

# Tabs
active_tab_foreground    #f8f1e7
active_tab_background    #766f28
inactive_tab_foreground  #766f28
inactive_tab_background  #f5eadb
