# extras/kitty/oasis_moonlight_light_2.conf
## name: Oasis Moonlight Light 2
## author: uhs-robert

# Palette
color0                   #39537a
color8                   #445361

color1                   #bc1313
color9                   #bc1313

color2                   #3b6837
color10                  #386931

color3                   #665f22
color11                  #8a4f14

color4                   #155fa9
color12                  #24657f

color5                   #7c2bdc
color13                  #7b2bdc

color6                   #356660
color14                  #34665f

color7                   #605114
color15                  #5a5230

# Core
foreground               #191615
background               #f6f2e4

# Selection
selection_background     #e1b69d
selection_foreground     #4e260e

# Cursor
cursor                   #776b1d
cursor_text_color        #f6f2e4

# Borders (panes)
active_border_color      #405469
inactive_border_color    #f3edd8

# Tabs
active_tab_foreground    #f6f2e4
active_tab_background    #28405a
inactive_tab_foreground  #28405a
inactive_tab_background  #f3edd8
