# extras/kitty/oasis_midnight_light_2.conf
## name: Oasis Midnight Light 2
## author: uhs-robert

# Palette
color0                   #4d4d4d
color8                   #574b43

color1                   #b31212
color9                   #b31212

color2                   #386335
color10                  #35642e

color3                   #615b21
color11                  #844c13

color4                   #145aa2
color12                  #236079

color5                   #7624d8
color13                  #7624d9

color6                   #32625c
color14                  #32625a

color7                   #5b4c13
color15                  #554d2e

# Core
foreground               #161412
background               #f7e7e3

# Selection
selection_background     #e1c99d
selection_foreground     #4e370e

# Cursor
cursor                   #72661c
cursor_text_color        #f7e7e3

# Borders (panes)
active_border_color      #932323
inactive_border_color    #f3dcd8

# Tabs
active_tab_foreground    #f7e7e3
active_tab_background    #615b21
inactive_tab_foreground  #615b21
inactive_tab_background  #f3dcd8
