# extras/kitty/oasis_rose_light_2.conf
## name: Oasis Rose Light 2
## author: uhs-robert

# Palette
color0                   #505050
color8                   #5a4e46

color1                   #b91313
color9                   #b91313

color2                   #3a6636
color10                  #376730

color3                   #645e22
color11                  #894e14

color4                   #145da7
color12                  #24637d

color5                   #7a28db
color13                  #7929dc

color6                   #34655f
color14                  #33655d

color7                   #5e5014
color15                  #59502f

# Core
foreground               #1d1115
background               #f9ecf4

# Selection
selection_background     #dba3c6
selection_foreground     #481335

# Cursor
cursor                   #ad4566
cursor_text_color        #f9ecf4

# Borders (panes)
active_border_color      #6c4552
inactive_border_color    #f5e0ed

# Tabs
active_tab_foreground    #f9ecf4
active_tab_background    #5e2438
inactive_tab_foreground  #5e2438
inactive_tab_background  #f5e0ed
