# extras/foot/oasis_sol_light_1.ini
# name: Oasis Sol Light 1
# author: uhs-robert

[colors]
cursor=f8dddd b9292c
foreground=1d0f0c
background=f8dddd

selection-foreground=1d0f0c
selection-background=eeaaaa

search-box-no-match=4e0e0e e19d9d
search-box-match=0d311f 7ad1a7

urls=2a5364
jump-labels=0d311f 7ad1a7

regular0=3f3f3f
regular1=ab1111
regular2=365f32
regular3=5c561f
regular4=13569a
regular5=7121cf
regular6=2f5d58
regular7=4a3e10

bright0=473d36
bright1=ab1111
bright2=325f2c
bright3=7e4813
bright4=215b74
bright5=7022d0
bright6=2f5d56
bright7=463f25
16=925822
17=704f0c