# extras/kitty/oasis_mirage_dark.conf
## name: Oasis Mirage Dark
## author: uhs-robert

# Palette
color0                   #111C22
color8                   #587270

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #69C3AA
color14                  #8AD3BE

color7                   #F5F5DC
color15                  #FFFFF0

# Core
foreground               #F5F5DC
background               #111C22

# Selection
selection_background     #21333B
selection_foreground     #FFFFF0

# Cursor
cursor                   #F0E68C
cursor_text_color        #111C22

# Borders (panes)
active_border_color      #55B69D
inactive_border_color    #0D161C

# Tabs
active_tab_foreground    #111C22
active_tab_background    #69C3AA
inactive_tab_foreground  #69C3AA
inactive_tab_background  #18252A
