# extras/kitty/oasis_night_dark.conf
## name: Oasis Night Dark
## author: uhs-robert

# Palette
color0                   #08111C
color8                   #536B83

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #69C3AA
color14                  #8AD3BE

color7                   #F5F5DC
color15                  #FFFFF0

# Core
foreground               #F5F5DC
background               #08111C

# Selection
selection_background     #24364D
selection_foreground     #FFFFF0

# Cursor
cursor                   #F0E68C
cursor_text_color        #08111C

# Borders (panes)
active_border_color      #7FA3C9
inactive_border_color    #060D16

# Tabs
active_tab_foreground    #08111C
active_tab_background    #7FA3C9
inactive_tab_foreground  #7FA3C9
inactive_tab_background  #101C2D
