# vim:set ft=tmux:
## name: Oasis Twilight Light 4
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#87391c"
set -ogq @thm_primary "#812509"
set -ogq @thm_light_primary "#6a2106"
set -ogq @thm_secondary "#430192"
set -ogq @thm_prefix "#827712"
set -ogq @thm_fg "#493b4b"

# Surfaces and overlays
set -ogq @thm_core "#f3cbbe"
set -ogq @thm_mantle "#f1c0b1"
set -ogq @thm_surface "#ecac97"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#991010"
set -ogq @thm_orange "#704011"
set -ogq @thm_yellow "#524d1c"
set -ogq @thm_green "#8c1518"
set -ogq @thm_teal "#2a534d"
set -ogq @thm_blue "#114d88"
set -ogq @thm_indigo "#651eb8"
