# vim:set ft=tmux:
## name: Oasis Dune Light 4
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#706c33"
set -ogq @thm_primary "#686222"
set -ogq @thm_light_primary "#64590d"
set -ogq @thm_secondary "#2c685f"
set -ogq @thm_prefix "#430192"
set -ogq @thm_fg "#4c4941"

# Surfaces and overlays
set -ogq @thm_core "#f5e1c7"
set -ogq @thm_mantle "#f3daba"
set -ogq @thm_surface "#eecca0"
set -ogq @thm_visual "#e1c99d"

# General
set -ogq @thm_red "#ac1111"
set -ogq @thm_orange "#7f4813"
set -ogq @thm_yellow "#5d571f"
set -ogq @thm_green "#9f171b"
set -ogq @thm_teal "#305d56"
set -ogq @thm_blue "#13579a"
set -ogq @thm_indigo "#7222cf"
