#!/usr/bin/env lua
-- assets/socials/generate_social_preview.lua
-- Generates the social preview HTML using an Oasis palette (default: lagoon dark)

package.path = package.path .. ";./lua/?.lua;./lua/?/init.lua"
local utils = require("oasis.utils")

local DEFAULT_PALETTE = "lagoon"
local DEFAULT_MODE = "dark"
local OUTPUT_PATH = "assets/socials/index.html"

local function normalize(color, fallback)
	if type(color) ~= "string" or color == "" or color == "none" then
		color = fallback
	end

	if not color then
		return "#FFFFFF"
	end

	if color:sub(1, 1) == "#" then
		return "#" .. color:sub(2):upper()
	end

	return color
end

local function build_colors(palette)
	local syntax = palette.syntax or {}
	local fg = palette.fg or {}
	local bg = palette.bg or {}
	local accent = (palette.theme and palette.theme.primary) or syntax.builtinVar or "#61AEFF"

	local function syn(key, fallback)
		return normalize(syntax[key], fallback)
	end

	return {
		bg = normalize(bg.core, "#0A0A0A"),
		body_bg = normalize(bg.shadow or bg.mantle, "#0B0F1A"),
		tile = normalize(bg.surface or bg.mantle or bg.core, "#111827"),
		fg = normalize(fg.core, "#EDE1C3"),
		accent = normalize(accent, "#61AEFF"),

		builtin_var = syn("builtinVar", "#61AEFF"),
		const = syn("constant", "#F8944D"),
		punct = syn("punctuation", "#E58383"),
		prop = syn("identifier", "#FFD393"),
		exception = syn("exception", "#D06666"),
		string = syn("string", "#53D390"),
		parameter = syn("parameter", "#C28EFF"),
		delimiter = syn("delimiter", "#D06666"),
		type = syn("type", "#81C0B6"),
		regex = syn("regex", "#96EA7F"),
		builtin_const = syn("builtinConst", "#3B9184"),
		constant = syn("constant", "#F8944D"),
		func = syn("func", "#F8B471"),
		builtin_func = syn("builtinFunc", "#E67451"),
		statement = syn("statement", "#F0E68C"),
		keyword = syn("keyword", syn("conditional", "#BDB76B")),
		special = syn("special", "#FFA247"),
		operator = syn("operator", "#FFA0A0"),
		preproc = syn("preproc", "#47E0FF"),
		bracket = syn("bracket", "#A39B8E"),
		comment = syn("comment", normalize(fg.muted or fg.dim, "#5E7B88")),
	}
end

local function render_template(ctx)
	local template = [[
<!-- assets/socials/index.html (generated by assets/socials/generate_social_preview.lua) -->
<!doctype html>
<meta charset="utf-8" />
<title>Oasis.nvim — Asymmetric Layout Preview</title>
<style>
  :root {
    --safe: 40px;
    --bg: ${bg};
    --fg: ${fg};
    --tile: ${tile};
    --accent: ${accent};
  }
  /* Full-viewport stage */
  html,
  body {
    height: 100%;
    margin: 0;
  }
  body {
    display: grid;
    place-items: center;
    background: ${body_bg};
    color: var(--fg);
  }
  /* 1200×560 canvas + 40px padding = 1280×640 total screenshot */
  .canvas {
    width: 1200px;
    height: 560px;
    background: var(--bg);
    color: var(--fg);
    font-family: Maple Mono NF;
    display: grid;
    grid-template-columns: 3fr 2.5fr;
    padding: var(--safe);
    gap: 0px;
    border-radius: 16px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.45);
    outline: 1px solid rgba(255, 255, 255, 0.06);
  }

  .left-side {
    display: flex;
  }
  .left-side .tile {
    flex: 1;
    margin: 0;
    margin-right: 15px;
  }

  .right-side {
    display: grid;
    grid-template-rows: auto 1fr;
    gap: 0px;
  }

  .right-header {
    text-align: center;
  }
  .title {
    font-weight: 800;
    font-size: 72px;
    letter-spacing: -0.5px;
    margin-bottom: 8px;
  }
  .subtitle {
    font-weight: 600;
    font-size: 28px;
    opacity: 0.9;
    margin-bottom: 8px;
  }

  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    gap: 0px;
    height: 100%;
  }

  .tile {
    position: relative;
    border-radius: 20px;
    overflow: hidden;
    background: var(--tile);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.35);
    margin: 15px;
  }
  .img {
    position: absolute;
    inset: 0;
    background-size: cover;
    filter: saturate(1.05) contrast(1.05);
  }
  .badge {
    position: absolute;
    right: 8px;
    bottom: 8px;
    padding: 8px 14px;
    border-radius: 10px;
    background: rgba(0, 0, 0, 0.6);
    -webkit-backdrop-filter: blur(8px);
    backdrop-filter: blur(8px);
    font-weight: 800;
    font-size: 18px;
    line-height: 1;
  }
  .left-side .badge {
    font-size: 32px;
    padding: 12px 22px;
    border-radius: 14px;
    right: 8px;
    bottom: 8px;
  }

	.const {
		color: ${const};
	}
	.builtinVar {
		color: ${builtin_var};
	}
  .punct {
    color: ${punct};
  }
  .prop {
    color: ${prop};
  }
  .exception {
    color: ${exception};
    font-style: italic;
  }
  .string {
    color: ${string};
  }

  .parameter {
    color: ${parameter};
  }
  .delimiter {
    color: ${delimiter};
  }
  .type {
    color: ${type};
  }
  .regex {
    color: ${regex};
  }
  .builtin-const {
    color: ${builtin_const};
  }
  .constant {
    color: ${constant};
  }
  .func {
    color: ${func};
  }
  .builtin-func {
    color: ${builtin_func};
  }
  .statement {
    color: ${statement};
  }
  .keyword {
    color: ${keyword};
    font-style: italic;
  }
  .special {
    color: ${special};
  }
  .operator {
    color: ${operator};
  }
  .preproc {
    color: ${preproc};
  }
  .bracket {
    color: ${bracket};
  }
  .comment {
    color: ${comment};
    font-style: italic;
  }

  .color-reference {
    margin-top: 40px;
    padding: 20px;
    background: var(--tile);
    border-radius: 8px;
    max-width: 1280px;
    font-family: monospace;
    font-size: 14px;
  }
  .color-reference h3 {
    color: var(--fg);
    margin: 0 0 16px 0;
    font-size: 16px;
    font-weight: 600;
  }
  .color-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
  }
  .color-item {
    display: flex;
    align-items: center;
    gap: 12px;
  }
  .color-swatch {
    width: 32px;
    height: 32px;
    border-radius: 4px;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }
  .color-info {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .color-name {
    color: #888;
    font-size: 11px;
  }
  .color-value {
    font-size: 20px;
  }

  .toggle-controls {
    display: flex;
    justify-content: center;
    gap: 16px;
    margin: 32px 0;
  }
  .toggle-btn {
    padding: 12px 24px;
    font-family:
      Maple Mono NF,
      monospace;
    font-size: 14px;
    font-weight: 600;
    color: var(--fg);
    background: #1a1a1a;
    border: 1px solid rgba(255, 255, 255, 0.2);
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  .toggle-btn:hover {
    background: #252525;
    border-color: rgba(255, 255, 255, 0.3);
  }
  .toggle-btn:active {
    transform: translateY(1px);
  }
  .toggle-btn.active {
    background: #2a2a2a;
    border-color: var(--accent);
    color: var(--accent);
  }
</style>

<main class="canvas">
  <div class="left-side">
    <figure class="tile">
      <div
        class="img"
        style="background-image: url('${hero_image}')"
      ></div>
      <figcaption class="badge">${palette_label}</figcaption>
    </figure>
  </div>

  <div class="right-side">
    <header class="right-header">
      <div class="title">
        <span class="statement">Oasis</span><span class="punct">.</span
        ><span class="prop">nvim</span>
      </div>
      <div class="subtitle">
        <span class="exception">return</span>
        <span class="string">"${theme_count} themes"</span>
      </div>
    </header>

    <section class="grid">
      <figure class="tile">
        <div
          class="img"
          style="background-image: url('./images/desert-dark-dashboard.png')"
        ></div>
        <figcaption class="badge">Desert</figcaption>
      </figure>
      <figure class="tile">
        <div
          class="img"
          style="background-image: url('./images/sol-dark-dashboard.png')"
        ></div>
        <figcaption class="badge">Sol</figcaption>
      </figure>

      <figure class="tile">
        <div
          class="img"
          style="background-image: url('./images/night-dark-dashboard.png')"
        ></div>
        <figcaption class="badge">Night</figcaption>
      </figure>
      <figure class="tile">
        <div
          class="img"
          style="background-image: url('./images/canyon-dark-dashboard.png')"
        ></div>
        <figcaption class="badge">Canyon</figcaption>
      </figure>

      <figure class="tile">
        <div
          class="img"
          style="background-image: url('./images/night-light-3-dashboard.png')"
        ></div>
        <figcaption class="badge">Light</figcaption>
      </figure>
      <figure class="tile">
        <div
          class="img"
          style="background-image: url('./images/mirage-dark-dashboard.png')"
        ></div>
        <figcaption class="badge">Mirage</figcaption>
      </figure>
    </section>
  </div>
</main>

<div class="toggle-controls">
  <button
    class="toggle-btn active"
    id="toggleCanvas"
    onclick="toggleElement('canvas')"
  >
    Toggle Canvas
  </button>
  <button
    class="toggle-btn"
    id="toggleFooter"
    onclick="toggleElement('footer')"
  >
    Toggle Footer
  </button>
</div>

<div class="color-reference" style="display: none" id="footer">
  <h3>Syntax Highlighting Colors (Oasis ${palette_label} Palette)</h3>
  <div class="color-grid">
    <div class="color-item">
      <div class="color-swatch" style="background-color: ${parameter}"></div>
      <div class="color-info">
        <div class="color-name">parameter</div>
        <div class="color-value">
          <span class="parameter">param</span> - ${parameter}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${prop}"></div>
      <div class="color-info">
        <div class="color-name">identifier</div>
        <div class="color-value">
          <span class="prop">property</span> - ${prop}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${delimiter}"></div>
      <div class="color-info">
        <div class="color-name">delimiter</div>
        <div class="color-value">
          <span class="delimiter">, ; :</span> - ${delimiter}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${type}"></div>
      <div class="color-info">
        <div class="color-name">type</div>
        <div class="color-value"><span class="type">Type</span> - ${type}</div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${builtin_var}"></div>
      <div class="color-info">
        <div class="color-name">builtinVar</div>
        <div class="color-value"><span class="builtinVar">this</span> - ${builtin_var}</div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${string}"></div>
      <div class="color-info">
        <div class="color-name">string</div>
        <div class="color-value">
          <span class="string">"string"</span> - ${string}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${regex}"></div>
      <div class="color-info">
        <div class="color-name">regex</div>
        <div class="color-value">
          <span class="regex">/regex/</span> - ${regex}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${builtin_const}"></div>
      <div class="color-info">
        <div class="color-name">builtinConst</div>
        <div class="color-value">
          <span class="builtin-const">null</span> - ${builtin_const}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${constant}"></div>
      <div class="color-info">
        <div class="color-name">constant</div>
        <div class="color-value">
          <span class="constant">123</span> - ${constant}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${func}"></div>
      <div class="color-info">
        <div class="color-name">func</div>
        <div class="color-value">
          <span class="func">myFunc</span> - ${func}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${builtin_func}"></div>
      <div class="color-info">
        <div class="color-name">builtinFunc</div>
        <div class="color-value">
          <span class="builtin-func">Array</span> - ${builtin_func}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${statement}"></div>
      <div class="color-info">
        <div class="color-name">statement</div>
        <div class="color-value">
          <span class="statement">if</span> - ${statement}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${exception}"></div>
      <div class="color-info">
        <div class="color-name">exception</div>
        <div class="color-value">
          <span class="exception">return</span> - ${exception}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${keyword}"></div>
      <div class="color-info">
        <div class="color-name">keyword</div>
        <div class="color-value">
          <span class="keyword">const</span> - ${keyword}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${special}"></div>
      <div class="color-info">
        <div class="color-name">special</div>
        <div class="color-value">
          <span class="special">@decorator</span> - ${special}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${operator}"></div>
      <div class="color-info">
        <div class="color-name">operator</div>
        <div class="color-value">
          <span class="operator">+ = -</span> - ${operator}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${punct}"></div>
      <div class="color-info">
        <div class="color-name">punctuation</div>
        <div class="color-value">
          <span class="punct">. ( )</span> - ${punct}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${preproc}"></div>
      <div class="color-info">
        <div class="color-name">preproc</div>
        <div class="color-value">
          <span class="preproc">import</span> - ${preproc}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${bracket}"></div>
      <div class="color-info">
        <div class="color-name">bracket</div>
        <div class="color-value">
          <span class="bracket">[ ] { }</span> - ${bracket}
        </div>
      </div>
    </div>

    <div class="color-item">
      <div class="color-swatch" style="background-color: ${comment}"></div>
      <div class="color-info">
        <div class="color-name">comment</div>
        <div class="color-value">
          <span class="comment">// comment</span> - ${comment}
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function toggleElement(elementId) {
    const element = document.getElementById(elementId);
    const button = document.getElementById(
      "toggle" + elementId.charAt(0).toUpperCase() + elementId.slice(1),
    );

    if (elementId === "canvas") {
      const canvas = document.querySelector(".canvas");
      if (canvas.style.display === "none") {
        canvas.style.display = "grid";
        button.classList.add("active");
      } else {
        canvas.style.display = "none";
        button.classList.remove("active");
      }
    } else {
      if (element.style.display === "none") {
        element.style.display = "block";
        button.classList.add("active");
      } else {
        element.style.display = "none";
        button.classList.remove("active");
      }
    }
  }
</script>
]]

	return (
		template:gsub("%${([%w_]+)}", function(key)
			local value = ctx[key]
			assert(value, "missing template variable: " .. key)
			return value
		end)
	)
end

local function main()
	print("\n=== Oasis Social Preview Generator ===\n")

	local palette_name = arg[1] or DEFAULT_PALETTE
	local mode = arg[2] or DEFAULT_MODE

	local palette, err = utils.load_palette(palette_name, mode)
	if not palette then
		print("Error: " .. (err or "could not load palette"))
		os.exit(1)
	end

	local colors = build_colors(palette)
	local base_name = palette_name:gsub("^oasis_", "")
	local palette_label = utils.capitalize(base_name)

	local context = {
		hero_image = string.format("./images/%s-dark-code.png", base_name),
		palette_label = palette_label,
		theme_count = tostring(#utils.get_palette_names()),
	}

	for k, v in pairs(colors) do
		context[k] = v
	end

	local html = render_template(context)
	utils.write_file(OUTPUT_PATH, html)

	print(string.format("✓ Wrote %s using %s (%s)", OUTPUT_PATH, palette_name, mode))
end

main()
