# extras/termux/oasis_mirage_light_2.properties
# name: Oasis Mirage Light 2
# author: uhs-robert

background: #e3f6f4
foreground: #121818

# Normal colors
color0:  #484848
color1:  #bc1313
color2:  #3b6837
color3:  #665f22
color4:  #155fa9
color5:  #7c2bdc
color6:  #356660
color7:  #544712

# Bright colors
color8: #50463e
color9: #bc1313
color10: #386931
color11: #8a4f14
color12: #24657f
color13: #7b2cdc
color14: #34675f
color15: #4f482a

# Extended colors
color16: #9e6025
color17: #bb141b