# extras/termux/oasis_scorpion_light_2.properties
# name: Oasis Scorpion Light 2
# author: uhs-robert

background: #f6d9d0
foreground: #191210

# Normal colors
color0:  #3d3d3d
color1:  #a61111
color2:  #345c31
color3:  #5a541e
color4:  #125496
color5:  #6e21c8
color6:  #2e5a55
color7:  #473c0f

# Bright colors
color8: #443b35
color9: #a61111
color10: #315d2b
color11: #7a4612
color12: #205970
color13: #6d21c9
color14: #2e5a54
color15: #433c24

# Extended colors
color16: #8e5621
color17: #a61218