# extras/termux/oasis_desert_light_2.properties
# name: Oasis Desert Light 2
# author: uhs-robert

background: #f9f7ec
foreground: #63523d

# Normal colors
color0:  #545454
color1:  #c11313
color2:  #3d6b39
color3:  #696223
color4:  #1561ae
color5:  #7f30dd
color6:  #366963
color7:  #635315

# Bright colors
color8: #5f524a
color9: #c11313
color10: #396c32
color11: #8f5215
color12: #256782
color13: #7e31dd
color14: #366962
color15: #5d5432

# Extended colors
color16: #79491c
color17: #c0151c