# extras/termux/oasis_midnight_light_2.properties
# name: Oasis Midnight Light 2
# author: uhs-robert

background: #f2e6d4
foreground: #534a44

# Normal colors
color0:  #4c4c4c
color1:  #b01212
color2:  #376134
color3:  #5f5920
color4:  #13589e
color5:  #7523d4
color6:  #31605a
color7:  #594b13

# Bright colors
color8: #554a42
color9: #b01212
color10: #34622d
color11: #814a13
color12: #225e76
color13: #7323d5
color14: #316059
color15: #544c2d

# Extended colors
color16: #6c4219
color17: #af1319