# extras/termux/oasis_lagoon_light_2.properties
# name: Oasis Lagoon Light 2
# author: uhs-robert

background: #e9f2fc
foreground: #111620

# Normal colors
color0:  #474747
color1:  #ba1313
color2:  #3b6837
color3:  #655f22
color4:  #155ea8
color5:  #7c29dc
color6:  #346660
color7:  #534611

# Bright colors
color8: #50453e
color9: #ba1313
color10: #376830
color11: #8a4f14
color12: #24647e
color13: #7a2adc
color14: #34665e
color15: #4f472a

# Extended colors
color16: #9d6025
color17: #ba141b