# extras/termux/oasis_night_light_2.properties
# name: Oasis Night Light 2
# author: uhs-robert

background: #e4edf7
foreground: #0c131d

# Normal colors
color0:  #254c95
color1:  #b51212
color2:  #396435
color3:  #625c21
color4:  #145ba3
color5:  #7824da
color6:  #33625d
color7:  #5c4d13

# Bright colors
color8: #41505d
color9: #b51212
color10: #35652f
color11: #854d14
color12: #23617a
color13: #7725db
color14: #32635b
color15: #574e2e

# Extended colors
color16: #995d24
color17: #b4141a