# extras/termux/oasis_moonlight_light_2.properties
# name: Oasis Moonlight Light 2
# author: uhs-robert

background: #f6f2e4
foreground: #191615

# Normal colors
color0:  #39537a
color1:  #bc1313
color2:  #3b6837
color3:  #665f22
color4:  #155fa9
color5:  #7c2bdc
color6:  #356660
color7:  #605114

# Bright colors
color8: #445361
color9: #bc1313
color10: #386931
color11: #8a4f14
color12: #24657f
color13: #7b2bdc
color14: #34665f
color15: #5a5230

# Extended colors
color16: #9e6025
color17: #bb141b