# extras/termux/oasis_abyss_light_2.properties
# name: Oasis Abyss Light 2
# author: uhs-robert

background: #e0e0e0
foreground: #161412

# Normal colors
color0:  #3d3d3d
color1:  #a81111
color2:  #345c31
color3:  #5b551e
color4:  #135497
color5:  #6f21ca
color6:  #2f5b55
color7:  #483d0f

# Bright colors
color8: #453b35
color9: #a81111
color10: #315d2b
color11: #7b4712
color12: #205971
color13: #6e21cb
color14: #2e5b54
color15: #443d24

# Extended colors
color16: #8e5721
color17: #a71218