# extras/termux/oasis_rose_light_2.properties
# name: Oasis Rose Light 2
# author: uhs-robert

background: #d9edd9
foreground: #6b3f4c

# Normal colors
color0:  #4c4c4c
color1:  #b01212
color2:  #376234
color3:  #5f5920
color4:  #14599f
color5:  #7523d4
color6:  #31605a
color7:  #594b13

# Bright colors
color8: #554a42
color9: #b01212
color10: #34622e
color11: #814a13
color12: #225e77
color13: #7323d5
color14: #316059
color15: #544c2d

# Extended colors
color16: #6d4219
color17: #74510d