# Oasis Starlight Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_starlight_light_4"

[palettes.oasis_starlight_light_4]
# Accent
primary       = '#035087'
strong_primary = '#035fa0'

# ANSI colors (0-7)
black         = '#4b4b4b'
red           = '#af1212'
green         = '#376134'
blue          = '#13589d'
purple        = '#7423d3'
cyan          = '#315f5a'
white         = '#584a13'

# Bright ANSI colors (8-15)
bright_black  = '#544942'
bright_red    = '#af1111'
bright_green  = '#34622d'
bright_yellow = '#814a13'
bright_blue   = '#215e76'
bright_purple = '#7322d5'
bright_cyan   = '#315f58'
bright_white  = '#534b2c'
