# Oasis Abyss Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_abyss_light_4"

[palettes.oasis_abyss_light_4]
# Accent
primary       = '#534e1b'
strong_primary = '#797437'

# ANSI colors (0-7)
black         = '#333333'
red           = '#950f0f'
green         = '#2e522b'
blue          = '#104a84'
purple        = '#621db2'
cyan          = '#29504c'
white         = '#3c320d'

# Bright ANSI colors (8-15)
bright_black  = '#39322c'
bright_red    = '#950e0e'
bright_green  = '#2b5226'
bright_yellow = '#6d3e10'
bright_blue   = '#1c4f63'
bright_purple = '#611db4'
bright_cyan   = '#29504a'
bright_white  = '#38331e'
