# Oasis Dune Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_dune_light_4"

[palettes.oasis_dune_light_4]
# Accent
primary       = '#534e1b'
strong_primary = '#796b37'

# ANSI colors (0-7)
black         = '#4a4a4a'
red           = '#ad1212'
green         = '#366033'
blue          = '#13579a'
purple        = '#7222d0'
cyan          = '#305e59'
white         = '#574912'

# Bright ANSI colors (8-15)
bright_black  = '#534841'
bright_red    = '#ad1111'
bright_green  = '#33602c'
bright_yellow = '#7f4913'
bright_blue   = '#215c74'
bright_purple = '#7122d2'
bright_cyan   = '#305e57'
bright_white  = '#524a2c'
