# Oasis Lagoon Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_lagoon_light_4"

[palettes.oasis_lagoon_light_4]
# Accent
primary       = '#023f6b'
strong_primary = '#15659b'

# ANSI colors (0-7)
black         = '#3d3d3d'
red           = '#a81111'
green         = '#345c31'
blue          = '#125496'
purple        = '#6f21c9'
cyan          = '#2f5b56'
white         = '#483c0f'

# Bright ANSI colors (8-15)
bright_black  = '#443c35'
bright_red    = '#a71010'
bright_green  = '#315d2b'
bright_yellow = '#7b4612'
bright_blue   = '#205970'
bright_purple = '#6e21cb'
bright_cyan   = '#2e5b54'
bright_white  = '#443d24'
