# Oasis Abyss Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_abyss_light_4"

[palettes.oasis_abyss_light_4]
# Accent
primary       = '#534e1b'
strong_primary = '#797437'

# ANSI colors (0-7)
black         = '#464646'
red           = '#a51111'
green         = '#345b31'
blue          = '#125394'
purple        = '#6d21c7'
cyan          = '#2e5955'
white         = '#534511'

# Bright ANSI colors (8-15)
bright_black  = '#4e443d'
bright_red    = '#a51010'
bright_green  = '#305c2a'
bright_yellow = '#794512'
bright_blue   = '#1f586f'
bright_purple = '#6c20c8'
bright_cyan   = '#2e5a53'
bright_white  = '#4e4629'
