# Oasis Sol Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_sol_light_4"

[palettes.oasis_sol_light_4]
# Accent
primary       = '#812509'
strong_primary = '#7c3e27'

# ANSI colors (0-7)
black         = '#3f3f3f'
red           = '#970f0f'
green         = '#2f532c'
blue          = '#104c86'
purple        = '#641eb5'
cyan          = '#2a514d'
white         = '#4a3e10'

# Bright ANSI colors (8-15)
bright_black  = '#463d37'
bright_red    = '#970f0f'
bright_green  = '#2c5426'
bright_yellow = '#6f3f10'
bright_blue   = '#1d5065'
bright_purple = '#631db7'
bright_cyan   = '#2a514b'
bright_white  = '#453e25'
