# Oasis Midnight Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_4"

[palettes.oasis_midnight_light_4]
# Accent
primary       = '#534e1b'
strong_primary = '#797437'

# ANSI colors (0-7)
black         = '#404040'
red           = '#9a1010'
green         = '#30542d'
blue          = '#114d89'
purple        = '#651eb8'
cyan          = '#2b534e'
white         = '#4b3f10'

# Bright ANSI colors (8-15)
bright_black  = '#473e38'
bright_red    = '#9a0f0f'
bright_green  = '#2d5527'
bright_yellow = '#714011'
bright_blue   = '#1d5267'
bright_purple = '#651eba'
bright_cyan   = '#2a534d'
bright_white  = '#474026'
