# Oasis Luna Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_luna_light_4"

[palettes.oasis_luna_light_4]
# Accent
primary       = '#60580d'
strong_primary = '#382c84'

# ANSI colors (0-7)
black         = '#3e3e3e'
red           = '#960f0f'
green         = '#2f532c'
blue          = '#104b86'
purple        = '#631eb4'
cyan          = '#2a514d'
white         = '#493d0f'

# Bright ANSI colors (8-15)
bright_black  = '#463d36'
bright_red    = '#970f0f'
bright_green  = '#2c5326'
bright_yellow = '#6e3f10'
bright_blue   = '#1c5064'
bright_purple = '#631db6'
bright_cyan   = '#2a514b'
bright_white  = '#453e25'
