# Oasis Desert Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_desert_light_4"

[palettes.oasis_desert_light_4]
# Accent
primary       = '#920101'
strong_primary = '#706c33'

# ANSI colors (0-7)
black         = '#4e4e4e'
red           = '#b41212'
green         = '#386435'
blue          = '#145ba1'
purple        = '#7724d9'
cyan          = '#33625d'
white         = '#5b4d13'

# Bright ANSI colors (8-15)
bright_black  = '#574c44'
bright_red    = '#b41111'
bright_green  = '#35652e'
bright_yellow = '#854c14'
bright_blue   = '#226179'
bright_purple = '#7623db'
bright_cyan   = '#32625b'
bright_white  = '#564e2e'
