# Oasis Midnight Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_midnight_light_4"

[palettes.oasis_midnight_light_4]
# Accent
primary       = '#534e1b'
strong_primary = '#797437'

# ANSI colors (0-7)
black         = '#373737'
red           = '#9b1010'
green         = '#30552d'
blue          = '#114e8a'
purple        = '#661fba'
cyan          = '#2b544f'
white         = '#40360e'

# Bright ANSI colors (8-15)
bright_black  = '#3d3530'
bright_red    = '#9b0f0f'
bright_green  = '#2d5628'
bright_yellow = '#724111'
bright_blue   = '#1d5368'
bright_purple = '#661ebc'
bright_cyan   = '#2b544e'
bright_white  = '#3c3620'
