# Oasis Sol Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_sol_light_4"

[palettes.oasis_sol_light_4]
# Accent
primary       = '#6d0101'
strong_primary = '#862a2a'

# ANSI colors (0-7)
black         = '#3c3c3c'
red           = '#920f0f'
green         = '#2d502b'
blue          = '#104982'
purple        = '#601daf'
cyan          = '#294f4a'
white         = '#473b0f'

# Bright ANSI colors (8-15)
bright_black  = '#433b35'
bright_red    = '#920e0e'
bright_green  = '#2b5125'
bright_yellow = '#6b3d10'
bright_blue   = '#1c4d61'
bright_purple = '#601db1'
bright_cyan   = '#284f49'
bright_white  = '#423c23'
