# Oasis Luna Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_luna_light_4"

[palettes.oasis_luna_light_4]
# Accent
primary       = '#796e11'
strong_primary = '#706c33'

# ANSI colors (0-7)
black         = '#3f3f3f'
red           = '#970f0f'
green         = '#2f532c'
blue          = '#104c87'
purple        = '#641eb6'
cyan          = '#2a524d'
white         = '#4a3e10'

# Bright ANSI colors (8-15)
bright_black  = '#463d37'
bright_red    = '#980f0f'
bright_green  = '#2c5427'
bright_yellow = '#6f3f10'
bright_blue   = '#1d5165'
bright_purple = '#631eb8'
bright_cyan   = '#2a524c'
bright_white  = '#463f25'
