# Oasis Night Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_night_light_4"

[palettes.oasis_night_light_4]
# Accent
primary       = '#294460'
strong_primary = '#315172'

# ANSI colors (0-7)
black         = '#55362e'
red           = '#950f0f'
green         = '#2e522c'
blue          = '#104b85'
purple        = '#631eb4'
cyan          = '#2a504c'
white         = '#493d0f'

# Bright ANSI colors (8-15)
bright_black  = '#51382c'
bright_red    = '#960f0f'
bright_green  = '#2b5326'
bright_yellow = '#6d3e10'
bright_blue   = '#1c4f64'
bright_purple = '#621db5'
bright_cyan   = '#29514b'
bright_white  = '#443e24'
