# Oasis Rose Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_rose_light_4"

[palettes.oasis_rose_light_4]
# Accent
primary       = '#501d2f'
strong_primary = '#7d334b'

# ANSI colors (0-7)
black         = '#363636'
red           = '#9a1010'
green         = '#30552d'
blue          = '#114d89'
purple        = '#661fb9'
cyan          = '#2b534f'
white         = '#3f350d'

# Bright ANSI colors (8-15)
bright_black  = '#3c352f'
bright_red    = '#9a0f0f'
bright_green  = '#2d5527'
bright_yellow = '#714111'
bright_blue   = '#1d5267'
bright_purple = '#651ebb'
bright_cyan   = '#2b534d'
bright_white  = '#3c3620'
