# Oasis Scorpion Light 4 – Starship palette
# https://github.com/uhs-robert/oasis.nvim

palette = "oasis_scorpion_light_4"

[palettes.oasis_scorpion_light_4]
# Accent
primary       = '#60580d'
strong_primary = '#817a2f'

# ANSI colors (0-7)
black         = '#474747'
red           = '#a61111'
green         = '#345c31'
blue          = '#125494'
purple        = '#6e21c8'
cyan          = '#2e5a55'
white         = '#534611'

# Bright ANSI colors (8-15)
bright_black  = '#4f453e'
bright_red    = '#a61010'
bright_green  = '#315c2b'
bright_yellow = '#7a4612'
bright_blue   = '#205970'
bright_purple = '#6d21ca'
bright_cyan   = '#2e5a54'
bright_white  = '#4e462a'
