# extras/termux/oasis_scorpion_light_3.properties
# name: Oasis Scorpion Light 3
# author: uhs-robert

background: #f7e3d4
foreground: #191210

# Normal colors
color0:  #4b4b4b
color1:  #af1212
color2:  #376133
color3:  #5f581f
color4:  #13589c
color5:  #7422d3
color6:  #305f5a
color7:  #584a13

# Bright colors
color8: #544941
color9: #af1212
color10: #34612d
color11: #814a13
color12: #215e75
color13: #7223d4
color14: #305f58
color15: #534b2d

# Extended colors
color16: #945a24
color17: #ae1318