# extras/termux/oasis_desert_light_3.properties
# name: Oasis Desert Light 3
# author: uhs-robert

background: #f4f1dd
foreground: #5f4e3a

# Normal colors
color0:  #515151
color1:  #ba1313
color2:  #3b6736
color3:  #655e21
color4:  #145ea6
color5:  #7b28dc
color6:  #346560
color7:  #5f5014

# Bright colors
color8: #5a4f46
color9: #ba1313
color10: #376830
color11: #894f15
color12: #24647d
color13: #7a29dc
color14: #33655e
color15: #595030

# Extended colors
color16: #74461c
color17: #b9141a