# extras/termux/oasis_sol_light_3.properties
# name: Oasis Sol Light 3
# author: uhs-robert

background: #efbcbc
foreground: #1d0f0c

# Normal colors
color0:  #2d2d2d
color1:  #8b0e0e
color2:  #2b4c28
color3:  #4a4519
color4:  #0f457b
color5:  #5c1ba7
color6:  #264b47
color7:  #362d0b

# Bright colors
color8: #332c28
color9: #8b0e0e
color10: #294d23
color11: #653a0f
color12: #1a4a5c
color13: #5b1ca8
color14: #264b45
color15: #322d1b

# Extended colors
color16: #79491d
color17: #5b400a