# extras/termux/oasis_desert_light_3.properties
# name: Oasis Desert Light 3
# author: uhs-robert

background: #f4f1dd
foreground: #191510

# Normal colors
color0:  #515151
color1:  #ba1313
color2:  #3b6736
color3:  #655e21
color4:  #145ea7
color5:  #7b28dc
color6:  #346560
color7:  #5f5014

# Bright colors
color8: #5a4f46
color9: #ba1313
color10: #376830
color11: #894f15
color12: #24647d
color13: #7a2adc
color14: #34655e
color15: #5a5130

# Extended colors
color16: #9d5f26
color17: #b9141a