# extras/termux/oasis_luna_light_3.properties
# name: Oasis Luna Light 3
# author: uhs-robert

background: #cbc9ee
foreground: #3e3366

# Normal colors
color0:  #3b3b3b
color1:  #900f0f
color2:  #2d4f2a
color3:  #4d481a
color4:  #104880
color5:  #5f1cad
color6:  #274e49
color7:  #453a0f

# Bright colors
color8: #423a33
color9: #900f0f
color10: #2a5025
color11: #693c10
color12: #1b4c60
color13: #5e1daf
color14: #274e48
color15: #413b23

# Extended colors
color16: #553315
color17: #901014