# extras/termux/oasis_scorpion_light_3.properties
# name: Oasis Scorpion Light 3
# author: uhs-robert

background: #f4cfc3
foreground: #191210

# Normal colors
color0:  #373737
color1:  #9d1010
color2:  #31562d
color3:  #554f1c
color4:  #114f8b
color5:  #681fbd
color6:  #2b5550
color7:  #41370e

# Bright colors
color8: #3e3630
color9: #9d1010
color10: #2e5728
color11: #734211
color12: #1e5469
color13: #661fbe
color14: #2b554f
color15: #3d3721

# Extended colors
color16: #865221
color17: #9c1116