# extras/termux/oasis_night_light_3.properties
# name: Oasis Night Light 3
# author: uhs-robert

background: #c4dbf3
foreground: #51402c

# Normal colors
color0:  #5b3a32
color1:  #9f1010
color2:  #31572e
color3:  #56501c
color4:  #11508d
color5:  #691fbf
color6:  #2c5651
color7:  #4e4211

# Bright colors
color8: #563d2f
color9: #9f1010
color10: #2f5829
color11: #744211
color12: #1e546a
color13: #681fc0
color14: #2c5650
color15: #4a4228

# Extended colors
color16: #5f3a17
color17: #9e1116