# extras/termux/oasis_sol_light_3.properties
# name: Oasis Sol Light 3
# author: uhs-robert

background: #f2c4c4
foreground: #1d0f0c

# Normal colors
color0:  #323232
color1:  #930f0f
color2:  #2e512a
color3:  #4f4a1a
color4:  #104a83
color5:  #611db1
color6:  #284f4b
color7:  #3b320d

# Bright colors
color8: #38312c
color9: #930f0f
color10: #2b5126
color11: #6b3e10
color12: #1c4e62
color13: #601db2
color14: #284f4a
color15: #38321e

# Extended colors
color16: #7f4d1f
color17: #60440a