# extras/termux/oasis_midnight_light_3.properties
# name: Oasis Midnight Light 3
# author: uhs-robert

background: #d9dee8
foreground: #161412

# Normal colors
color0:  #3c3c3c
color1:  #a51111
color2:  #345b30
color3:  #59531e
color4:  #125393
color5:  #6d20c7
color6:  #2d5954
color7:  #463b0f

# Bright colors
color8: #433a34
color9: #a51111
color10: #315c2a
color11: #794512
color12: #1f586e
color13: #6c21c8
color14: #2d5a53
color15: #423c24

# Extended colors
color16: #8d5522
color17: #a41217