# extras/termux/oasis_sol_light_3.properties
# name: Oasis Sol Light 3
# author: uhs-robert

background: #f7d4d4
foreground: #6a372d

# Normal colors
color0:  #454545
color1:  #a31010
color2:  #335a2f
color3:  #58521d
color4:  #125291
color5:  #6c20c4
color6:  #2d5853
color7:  #514411

# Bright colors
color8: #4d433c
color9: #a31010
color10: #305b2a
color11: #784412
color12: #1f576d
color13: #6b20c6
color14: #2d5852
color15: #4c4529

# Extended colors
color16: #633c18
color17: #6b4b0c