# vim:set ft=tmux:
## name: Oasis Twilight Light 5
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#7f351a"
set -ogq @thm_primary "#782107"
set -ogq @thm_light_primary "#611e05"
set -ogq @thm_secondary "#3e008a"
set -ogq @thm_prefix "#7a6f10"
set -ogq @thm_fg "#433646"

# Surfaces and overlays
set -ogq @thm_core "#f2c1b5"
set -ogq @thm_mantle "#f0b6a8"
set -ogq @thm_surface "#eba08e"
set -ogq @thm_visual "#e1b69d"

# General
set -ogq @thm_red "#900e0e"
set -ogq @thm_orange "#693c0f"
set -ogq @thm_yellow "#4d4819"
set -ogq @thm_green "#831216"
set -ogq @thm_teal "#274d47"
set -ogq @thm_blue "#0f487f"
set -ogq @thm_indigo "#5f1cad"
