# vim:set ft=tmux:
## name: Oasis Mirage Light 5
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#31756d"
set -ogq @thm_primary "#1d4641"
set -ogq @thm_light_primary "#1a3f3a"
set -ogq @thm_secondary "#5f3105"
set -ogq @thm_prefix "#3e008a"
set -ogq @thm_fg "#121717"

# Surfaces and overlays
set -ogq @thm_core "#c0f2ee"
set -ogq @thm_mantle "#b3efeb"
set -ogq @thm_surface "#9aeae4"
set -ogq @thm_visual "#9fe0d7"

# General
set -ogq @thm_red "#b11111"
set -ogq @thm_orange "#824a13"
set -ogq @thm_yellow "#5f5920"
set -ogq @thm_green "#991116"
set -ogq @thm_teal "#316059"
set -ogq @thm_blue "#13599e"
set -ogq @thm_indigo "#7523d5"
