# vim:set ft=tmux:
## name: Oasis Sol Light 5
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#7f2727"
set -ogq @thm_primary "#630000"
set -ogq @thm_light_primary "#590000"
set -ogq @thm_secondary "#5f3105"
set -ogq @thm_prefix "#296624"
set -ogq @thm_fg "#1d0f0c"

# Surfaces and overlays
set -ogq @thm_core "#f2b5b8"
set -ogq @thm_mantle "#f0a8ac"
set -ogq @thm_surface "#eb8e93"
set -ogq @thm_visual "#e19d9d"

# General
set -ogq @thm_red "#860d0d"
set -ogq @thm_orange "#62380e"
set -ogq @thm_yellow "#474318"
set -ogq @thm_green "#512c0d"
set -ogq @thm_teal "#244842"
set -ogq @thm_blue "#0e4376"
set -ogq @thm_indigo "#591aa1"
