# vim:set ft=tmux:
## name: Oasis Luna Light 5
## author: uhs-robert

# Main
set -ogq @thm_strong_primary "#34297d"
set -ogq @thm_primary "#58500b"
set -ogq @thm_light_primary "#4f480a"
set -ogq @thm_secondary "#111152"
set -ogq @thm_prefix "#116179"
set -ogq @thm_fg "#100e1b"

# Surfaces and overlays
set -ogq @thm_core "#c3c2f0"
set -ogq @thm_mantle "#b7b6ed"
set -ogq @thm_surface "#9f9de7"
set -ogq @thm_visual "#c3a1dd"

# General
set -ogq @thm_red "#880d0d"
set -ogq @thm_orange "#63390f"
set -ogq @thm_yellow "#484418"
set -ogq @thm_green "#700c10"
set -ogq @thm_teal "#254944"
set -ogq @thm_blue "#0f4479"
set -ogq @thm_indigo "#5a1ba3"
