# extras/termux/oasis_sol_light_4.properties
# name: Oasis Sol Light 4
# author: uhs-robert

background: #efb7b7
foreground: #1d0f0c

# Normal colors
color0:  #2b2b2b
color1:  #870e0e
color2:  #2a4a27
color3:  #484318
color4:  #0f4377
color5:  #591ba1
color6:  #254844
color7:  #322a0b

# Bright colors
color8: #302a25
color9: #870d0d
color10: #274a22
color11: #62380f
color12: #19475a
color13: #581aa3
color14: #254843
color15: #2f2b19

# Extended colors
color16: #76471d
color17: #583d0a