# extras/termux/oasis_night_light_4.properties
# name: Oasis Night Light 4
# author: uhs-robert

background: #c4dcf2
foreground: #0c131c

# Normal colors
color0:  #1f4180
color1:  #9f1010
color2:  #32582f
color3:  #56501d
color4:  #11508e
color5:  #6920c0
color6:  #2d5652
color7:  #4f4211

# Bright colors
color8: #394450
color9: #9f0f0f
color10: #2f5929
color11: #754311
color12: #1e556b
color13: #681fc1
color14: #2c5650
color15: #4a4327

# Extended colors
color16: #895321
color17: #9f1116