# extras/termux/oasis_twilight_light_4.properties
# name: Oasis Twilight Light 4
# author: uhs-robert

background: #f3cbbe
foreground: #493b4b

# Normal colors
color0:  #404040
color1:  #991010
color2:  #2f542d
color3:  #524d1c
color4:  #114d88
color5:  #651eb8
color6:  #2b524e
color7:  #4b3f10

# Bright colors
color8: #473e38
color9: #990f0f
color10: #2d5527
color11: #704011
color12: #1d5166
color13: #641eb9
color14: #2a534d
color15: #463f25

# Extended colors
color16: #5b3716
color17: #981116