# extras/termux/oasis_midnight_light_4.properties
# name: Oasis Midnight Light 4
# author: uhs-robert

background: #cfd6e2
foreground: #171412

# Normal colors
color0:  #373737
color1:  #9b1010
color2:  #30552d
color3:  #534e1c
color4:  #114e8a
color5:  #661fba
color6:  #2b544f
color7:  #40360e

# Bright colors
color8: #3d3530
color9: #9b0f0f
color10: #2d5628
color11: #724111
color12: #1d5368
color13: #661ebc
color14: #2b544e
color15: #3c3620

# Extended colors
color16: #855120
color17: #9b1116