# extras/termux/oasis_night_light_4.properties
# name: Oasis Night Light 4
# author: uhs-robert

background: #b8d4ef
foreground: #4a3b28

# Normal colors
color0:  #55362e
color1:  #950f0f
color2:  #2e522c
color3:  #504b1b
color4:  #104b85
color5:  #631eb4
color6:  #2a504c
color7:  #493d0f

# Bright colors
color8: #51382c
color9: #960f0f
color10: #2b5326
color11: #6d3e10
color12: #1c4f64
color13: #621db5
color14: #29514b
color15: #443e24

# Extended colors
color16: #593615
color17: #951015