# extras/termux/oasis_moonlight_light_4.properties
# name: Oasis Moonlight Light 4
# author: uhs-robert

background: #e3d7aa
foreground: #4f3f2b

# Normal colors
color0:  #5a3a31
color1:  #9d1010
color2:  #31562e
color3:  #544f1c
color4:  #114f8c
color5:  #681fbd
color6:  #2c5550
color7:  #4d4110

# Bright colors
color8: #563c2f
color9: #9d0f0f
color10: #2e5728
color11: #734211
color12: #1e5369
color13: #671fbe
color14: #2b554e
color15: #494227

# Extended colors
color16: #5e3917
color17: #9c1116