# extras/termux/oasis_night_light_4.properties
# name: Oasis Night Light 4
# author: uhs-robert

background: #c1daf6
foreground: #0c131c

# Normal colors
color0:  #383838
color1:  #9d1010
color2:  #31572e
color3:  #554f1c
color4:  #114f8c
color5:  #681fbd
color6:  #2c5550
color7:  #42370e

# Bright colors
color8: #3e3631
color9: #9d0f0f
color10: #2e5728
color11: #734211
color12: #1e5469
color13: #671fbf
color14: #2b554f
color15: #3e3821

# Extended colors
color16: #875221
color17: #9d1116