# extras/termux/oasis_canyon_light_4.properties
# name: Oasis Canyon Light 4
# author: uhs-robert

background: #ebcbb1
foreground: #181811

# Normal colors
color0:  #333333
color1:  #960f0f
color2:  #2e522c
color3:  #504b1b
color4:  #104b85
color5:  #631eb3
color6:  #2d5146
color7:  #353519

# Bright colors
color8: #39322d
color9: #960f0f
color10: #2c5326
color11: #6e3f10
color12: #1c4f64
color13: #621db5
color14: #2c5146
color15: #35350b

# Extended colors
color16: #6d5725
color17: #951015