# extras/termux/oasis_moonlight_light_4.properties
# name: Oasis Moonlight Light 4
# author: uhs-robert

background: #ede5c9
foreground: #171412

# Normal colors
color0:  #334b6e
color1:  #ad1212
color2:  #366033
color3:  #5e571f
color4:  #13579b
color5:  #7322d0
color6:  #315e59
color7:  #574912

# Bright colors
color8: #3f4c57
color9: #ad1111
color10: #33612c
color11: #804913
color12: #215d75
color13: #7222d2
color14: #305e57
color15: #524a2c

# Extended colors
color16: #935924
color17: #ac1318