# extras/termux/oasis_mirage_light_5.properties
# name: Oasis Mirage Light 5
# author: uhs-robert

background: #c1eae6
foreground: #121717

# Normal colors
color0:  #3e3e3e
color1:  #aa1010
color2:  #355e31
color3:  #5c561e
color4:  #125598
color5:  #7021cc
color6:  #2f5c57
color7:  #493e0f

# Bright colors
color8: #453d36
color9: #aa1111
color10: #325f2c
color11: #7d4712
color12: #215a72
color13: #6f22cd
color14: #2f5c55
color15: #453e25

# Extended colors
color16: #905723
color17: #a91218