# extras/termux/oasis_luna_light_5.properties
# name: Oasis Luna Light 5
# author: uhs-robert

background: #aeadeb
foreground: #2a2346

# Normal colors
color0:  #282828
color1:  #6e0b0b
color2:  #223b1f
color3:  #3a3613
color4:  #0c3660
color5:  #481584
color6:  #1e3a37
color7:  #2f280a

# Bright colors
color8: #2c2722
color9: #6e0b0b
color10: #203c1c
color11: #4f2d0c
color12: #153948
color13: #481684
color14: #1e3a36
color15: #2c2818

# Extended colors
color16: #3a230e
color17: #6e0c10