# extras/termux/oasis_abyss_light_5.properties
# name: Oasis Abyss Light 5
# author: uhs-robert

background: #f0d7a8
foreground: #49423b

# Normal colors
color0:  #434343
color1:  #a00f0f
color2:  #32582f
color3:  #56511d
color4:  #11518f
color5:  #6a1fc1
color6:  #2c5752
color7:  #4f4311

# Bright colors
color8: #4b423a
color9: #a11010
color10: #2f5929
color11: #764311
color12: #1f556c
color13: #6920c2
color14: #2c5750
color15: #4b4328

# Extended colors
color16: #613b17
color17: #a01117