# extras/termux/oasis_cactus_light_5.properties
# name: Oasis Cactus Light 5
# author: uhs-robert

background: #c7e5d2
foreground: #121714

# Normal colors
color0:  #3c3c3c
color1:  #a51010
color2:  #335b30
color3:  #59531d
color4:  #125393
color5:  #6d20c7
color6:  #2e5954
color7:  #463b0f

# Bright colors
color8: #423b33
color9: #a51010
color10: #305c2b
color11: #794512
color12: #20586f
color13: #6c21c7
color14: #2d5a53
color15: #423c23

# Extended colors
color16: #8d5522
color17: #a41218