# extras/termux/oasis_abyss_light_5.properties
# name: Oasis Abyss Light 5
# author: uhs-robert

background: #d6d6d6
foreground: #171412

# Normal colors
color0:  #414141
color1:  #9c0f0f
color2:  #31562d
color3:  #544e1c
color4:  #114e8b
color5:  #671ebb
color6:  #2b544f
color7:  #4c4010

# Bright colors
color8: #484038
color9: #9c0f0f
color10: #2e5628
color11: #724111
color12: #1e5369
color13: #661fbc
color14: #2b544e
color15: #484127

# Extended colors
color16: #865120
color17: #9b1116