# extras/termux/oasis_night_light_5.properties
# name: Oasis Night Light 5
# author: uhs-robert

background: #b7d7f0
foreground: #0c131d

# Normal colors
color0:  #1e3d78
color1:  #980f0f
color2:  #2f542c
color3:  #514c1b
color4:  #104c87
color5:  #651eb7
color6:  #2a524d
color7:  #4a3e0f

# Bright colors
color8: #35404c
color9: #980f0f
color10: #2c5427
color11: #6f3f10
color12: #1d5166
color13: #641eb7
color14: #2a524c
color15: #463f25

# Extended colors
color16: #834f20
color17: #971016