# extras/termux/oasis_twilight_light_5.properties
# name: Oasis Twilight Light 5
# author: uhs-robert

background: #f2c1b5
foreground: #433646

# Normal colors
color0:  #3b3b3b
color1:  #900e0e
color2:  #2c4f29
color3:  #4d4819
color4:  #0f487f
color5:  #5f1cad
color6:  #284d49
color7:  #453a0e

# Bright colors
color8: #413932
color9: #900e0e
color10: #2a4f25
color11: #693c0f
color12: #1c4c60
color13: #5e1cad
color14: #274d47
color15: #413a23

# Extended colors
color16: #553314
color17: #8f1015