# extras/termux/oasis_midnight_light_5.properties
# name: Oasis Midnight Light 5
# author: uhs-robert

background: #f0cea8
foreground: #463e3a

# Normal colors
color0:  #404040
color1:  #990f0f
color2:  #30542c
color3:  #524d1b
color4:  #104d88
color5:  #651eb8
color6:  #2a524e
color7:  #4b3f10

# Bright colors
color8: #463e37
color9: #990f0f
color10: #2d5527
color11: #704010
color12: #1d5167
color13: #641eb9
color14: #2a534c
color15: #463f26

# Extended colors
color16: #5b3716
color17: #981116