# extras/termux/oasis_sol_light_5.properties
# name: Oasis Sol Light 5
# author: uhs-robert

background: #f3bfba
foreground: #5b2e26

# Normal colors
color0:  #3a3a3a
color1:  #8f0e0e
color2:  #2c4e29
color3:  #4c4719
color4:  #0f477f
color5:  #5e1cab
color6:  #274d48
color7:  #443a0e

# Bright colors
color8: #413932
color9: #8f0e0e
color10: #2a4f25
color11: #683b0f
color12: #1b4b5f
color13: #5d1cac
color14: #274d47
color15: #413a22

# Extended colors
color16: #543314
color17: #5d410a