# extras/termux/oasis_abyss_light_5.properties
# name: Oasis Abyss Light 5
# author: uhs-robert

background: #c9c9c9
foreground: #171412

# Normal colors
color0:  #2e2e2e
color1:  #8c0e0e
color2:  #2b4d28
color3:  #4b4619
color4:  #0f467c
color5:  #5d1ba8
color6:  #264b47
color7:  #362e0b

# Bright colors
color8: #332d28
color9: #8c0e0e
color10: #294d24
color11: #663a0f
color12: #1b4a5d
color13: #5c1ca9
color14: #264b46
color15: #332e1b

# Extended colors
color16: #7a4a1d
color17: #8c0f14