# extras/termux/oasis_dune_light_5.properties
# name: Oasis Dune Light 5
# author: uhs-robert

background: #f2dcba
foreground: #161513

# Normal colors
color0:  #3d3d3d
color1:  #a61010
color2:  #345c30
color3:  #5a541e
color4:  #125495
color5:  #6e21c8
color6:  #2e5a55
color7:  #473c0f

# Bright colors
color8: #433b34
color9: #a61010
color10: #315c2b
color11: #7a4612
color12: #205970
color13: #6d21c9
color14: #2e5a53
color15: #433c24

# Extended colors
color16: #8e5622
color17: #a61218