# extras/termux/oasis_midnight_light_5.properties
# name: Oasis Midnight Light 5
# author: uhs-robert

background: #f2bdb5
foreground: #161412

# Normal colors
color0:  #393939
color1:  #8d0e0e
color2:  #2b4d29
color3:  #4b4619
color4:  #0f467d
color5:  #5d1ba9
color6:  #274b47
color7:  #43380e

# Bright colors
color8: #3f3831
color9: #8d0e0e
color10: #294e24
color11: #663a0f
color12: #1b4a5e
color13: #5c1ca9
color14: #264c46
color15: #3f3922

# Extended colors
color16: #7a4a1e
color17: #8c0f14