# extras/termux/oasis_scorpion_light_5.properties
# name: Oasis Scorpion Light 5
# author: uhs-robert

background: #efbaa9
foreground: #191210

# Normal colors
color0:  #2c2c2c
color1:  #880d0d
color2:  #2a4a27
color3:  #484418
color4:  #0f4478
color5:  #5a1ba3
color6:  #254945
color7:  #332b0b

# Bright colors
color8: #302b25
color9: #880d0d
color10: #284b23
color11: #63390f
color12: #1a485b
color13: #591ba4
color14: #254943
color15: #302b1a

# Extended colors
color16: #77481d
color17: #880f14