# extras/alacritty/themes/light/5/oasis_scorpion_light_5.toml
## name: Oasis Scorpion Light 5
## author: uhs-robert

[colors.primary]
background = '#efbaa9'
foreground = '#191210'

[colors.selection]
background = '#e89b82'
text = '#191210'

[colors.cursor]
cursor = '#585015'
text = '#efbaa9'

[colors.vi_mode_cursor]
cursor = '#63390f'
text = '#efbaa9'

[colors.normal]
black   = '#2c2c2c'
red     = '#880d0d'
green   = '#2a4a27'
yellow  = '#484418'
blue    = '#0f4478'
magenta = '#5a1ba3'
cyan    = '#254945'
white   = '#332b0b'

[colors.bright]
black   = '#302b25'
red     = '#880d0d'
green   = '#284b23'
yellow  = '#63390f'
blue    = '#1a485b'
magenta = '#591ba4'
cyan    = '#254943'
white   = '#302b1a'