# extras/alacritty/themes/light/5/oasis_luna_light_5.toml
## name: Oasis Luna Light 5
## author: uhs-robert

[colors.primary]
background = '#aeadeb'
foreground = '#2a2346'

[colors.selection]
background = '#8a88e2'
text = '#2a2346'

[colors.cursor]
cursor = '#3b360e'
text = '#aeadeb'

[colors.vi_mode_cursor]
cursor = '#4f2d0c'
text = '#aeadeb'

[colors.normal]
black   = '#282828'
red     = '#6e0b0b'
green   = '#223b1f'
yellow  = '#3a3613'
blue    = '#0c3660'
magenta = '#481584'
cyan    = '#1e3a37'
white   = '#2f280a'

[colors.bright]
black   = '#2c2722'
red     = '#6e0b0b'
green   = '#203c1c'
yellow  = '#4f2d0c'
blue    = '#153948'
magenta = '#481684'
cyan    = '#1e3a36'
white   = '#2c2818'