# extras/alacritty/themes/light/5/oasis_moonlight_light_5.toml
## name: Oasis Moonlight Light 5
## author: uhs-robert

[colors.primary]
background = '#ddd8c5'
foreground = '#161412'

[colors.selection]
background = '#c6be9e'
text = '#161412'

[colors.cursor]
cursor = '#655b18'
text = '#ddd8c5'

[colors.vi_mode_cursor]
cursor = '#744211'
text = '#ddd8c5'

[colors.normal]
black   = '#383838'
red     = '#9e0f0f'
green   = '#31572e'
yellow  = '#55501c'
blue    = '#114f8d'
magenta = '#691fbe'
cyan    = '#2c5550'
white   = '#42370e'

[colors.bright]
black   = '#3e3730'
red     = '#9e0f0f'
green   = '#2e5829'
yellow  = '#744211'
blue    = '#1e546a'
magenta = '#681fbf'
cyan    = '#2b564f'
white   = '#3e3821'