# extras/alacritty/themes/light/5/oasis_starlight_light_5.toml
## name: Oasis Starlight Light 5
## author: uhs-robert

[colors.primary]
background = '#ebe5d5'
foreground = '#181611'

[colors.selection]
background = '#d7cbac'
text = '#181611'

[colors.cursor]
cursor = '#1565ac'
text = '#ebe5d5'

[colors.vi_mode_cursor]
cursor = '#804913'
text = '#ebe5d5'

[colors.normal]
black   = '#404040'
red     = '#ae1111'
green   = '#366033'
yellow  = '#5e581f'
blue    = '#13579b'
magenta = '#7322d1'
cyan    = '#305e59'
white   = '#4b4010'

[colors.bright]
black   = '#473f37'
red     = '#ae1111'
green   = '#33612d'
yellow  = '#804913'
blue    = '#225d75'
magenta = '#7222d2'
cyan    = '#305f57'
white   = '#474026'