# extras/alacritty/themes/light/5/oasis_desert_light_5.toml
## name: Oasis Desert Light 5
## author: uhs-robert

[colors.primary]
background = '#ece6c6'
foreground = '#191510'

[colors.selection]
background = '#e1d7a4'
text = '#191510'

[colors.cursor]
cursor = '#6e631b'
text = '#ece6c6'

[colors.vi_mode_cursor]
cursor = '#804913'
text = '#ece6c6'

[colors.normal]
black   = '#4a4a4a'
red     = '#ae1111'
green   = '#366033'
yellow  = '#5e581f'
blue    = '#13579b'
magenta = '#7322d1'
cyan    = '#305e59'
white   = '#574a12'

[colors.bright]
black   = '#534940'
red     = '#ae1111'
green   = '#33612d'
yellow  = '#804913'
blue    = '#225d75'
magenta = '#7222d2'
cyan    = '#305f57'
white   = '#524a2c'