# extras/alacritty/themes/light/5/oasis_twilight_light_5.toml
## name: Oasis Twilight Light 5
## author: uhs-robert

[colors.primary]
background = '#f2c1b5'
foreground = '#433646'

[colors.selection]
background = '#eba08e'
text = '#433646'

[colors.cursor]
cursor = '#693c11'
text = '#f2c1b5'

[colors.vi_mode_cursor]
cursor = '#693c0f'
text = '#f2c1b5'

[colors.normal]
black   = '#3b3b3b'
red     = '#900e0e'
green   = '#2c4f29'
yellow  = '#4d4819'
blue    = '#0f487f'
magenta = '#5f1cad'
cyan    = '#284d49'
white   = '#453a0e'

[colors.bright]
black   = '#413932'
red     = '#900e0e'
green   = '#2a4f25'
yellow  = '#693c0f'
blue    = '#1c4c60'
magenta = '#5e1cad'
cyan    = '#274d47'
white   = '#413a23'