# extras/foot/oasis_sol_light_4.ini
# name: Oasis Sol Light 4
# author: uhs-robert

[colors]
cursor=f4c2c2 a12326
foreground=1d0f0c
background=f4c2c2

selection-foreground=1d0f0c
selection-background=ed9b9b

search-box-no-match=4e0e0e e19d9d
search-box-match=0d311f 7ad1a7

urls=172e38
jump-labels=0d311f 7ad1a7

regular0=3c3c3c
regular1=920f0f
regular2=2d502b
regular3=4e491a
regular4=104982
regular5=601daf
regular6=294f4a
regular7=473b0f

bright0=433b35
bright1=920e0e
bright2=2b5125
bright3=6b3d10
bright4=1c4d61
bright5=601db1
bright6=284f49
bright7=423c23
16=7e4d1f
17=60430a