# extras/alacritty/themes/light/3/oasis_scorpion_light_3.toml
## name: Oasis Scorpion Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e3d4'
foreground = '#191210'

[colors.selection]
background = '#f0caad'
text = '#191210'

[colors.cursor]
cursor = '#70641b'
text = '#f7e3d4'

[colors.vi_mode_cursor]
cursor = '#814a13'
text = '#f7e3d4'

[colors.normal]
black   = '#4b4b4b'
red     = '#af1212'
green   = '#376133'
yellow  = '#5f581f'
blue    = '#13589c'
magenta = '#7422d3'
cyan    = '#305f5a'
white   = '#584a13'

[colors.bright]
black   = '#544941'
red     = '#af1212'
green   = '#34612d'
yellow  = '#814a13'
blue    = '#215e75'
magenta = '#7223d4'
cyan    = '#305f58'
white   = '#534b2d'