# extras/alacritty/themes/light/3/oasis_lagoon_light_3.toml
## name: Oasis Lagoon Light 3
## author: uhs-robert

[colors.primary]
background = '#dceafa'
foreground = '#0e131b'

[colors.selection]
background = '#a6caf2'
text = '#0e131b'

[colors.cursor]
cursor = '#1567ae'
text = '#dceafa'

[colors.vi_mode_cursor]
cursor = '#824b14'
text = '#dceafa'

[colors.normal]
black   = '#424242'
red     = '#b11212'
green   = '#386233'
yellow  = '#605920'
blue    = '#13599f'
magenta = '#7523d5'
cyan    = '#31605b'
white   = '#4e4111'

[colors.bright]
black   = '#4a4139'
red     = '#b11212'
green   = '#34632e'
yellow  = '#824b14'
blue    = '#225f77'
magenta = '#7423d7'
cyan    = '#316059'
white   = '#494227'