# extras/alacritty/themes/light/3/oasis_rose_light_3.toml
## name: Oasis Rose Light 3
## author: uhs-robert

[colors.primary]
background = '#d2e9d4'
foreground = '#663d49'

[colors.selection]
background = '#b3dab6'
text = '#663d49'

[colors.cursor]
cursor = '#aa1318'
text = '#d2e9d4'

[colors.vi_mode_cursor]
cursor = '#7e4813'
text = '#d2e9d4'

[colors.normal]
black   = '#494949'
red     = '#ab1111'
green   = '#365e32'
yellow  = '#5d561f'
blue    = '#135699'
magenta = '#7121ce'
cyan    = '#2f5d58'
white   = '#564812'

[colors.bright]
black   = '#52473f'
red     = '#ab1111'
green   = '#335f2c'
yellow  = '#7e4813'
blue    = '#215b72'
magenta = '#7022cf'
cyan    = '#2f5d56'
white   = '#51492c'