# extras/alacritty/themes/light/3/oasis_luna_light_3.toml
## name: Oasis Luna Light 3
## author: uhs-robert

[colors.primary]
background = '#e2e0f8'
foreground = '#181811'

[colors.selection]
background = '#b3aeed'
text = '#181811'

[colors.cursor]
cursor = '#6a622a'
text = '#e2e0f8'

[colors.vi_mode_cursor]
cursor = '#7d4813'
text = '#e2e0f8'

[colors.normal]
black   = '#3e3e3e'
red     = '#aa1111'
green   = '#355e31'
yellow  = '#5c561f'
blue    = '#135698'
magenta = '#7121cd'
cyan    = '#355c52'
white   = '#40401e'

[colors.bright]
black   = '#463d36'
red     = '#aa1111'
green   = '#325f2c'
yellow  = '#7d4813'
blue    = '#205b72'
magenta = '#6f22ce'
cyan    = '#335c50'
white   = '#41410e'