# extras/alacritty/themes/light/3/oasis_midnight_light_3.toml
## name: Oasis Midnight Light 3
## author: uhs-robert

[colors.primary]
background = '#f6d6d0'
foreground = '#161412'

[colors.selection]
background = '#efb5a9'
text = '#161412'

[colors.cursor]
cursor = '#6a5e1a'
text = '#f6d6d0'

[colors.vi_mode_cursor]
cursor = '#784512'
text = '#f6d6d0'

[colors.normal]
black   = '#454545'
red     = '#a41111'
green   = '#335b30'
yellow  = '#59521d'
blue    = '#125292'
magenta = '#6d20c6'
cyan    = '#2d5954'
white   = '#524511'

[colors.bright]
black   = '#4d443c'
red     = '#a41111'
green   = '#305b2a'
yellow  = '#784512'
blue    = '#1f586e'
magenta = '#6b20c7'
cyan    = '#2d5953'
white   = '#4d4529'