# extras/alacritty/themes/light/3/oasis_rose_light_3.toml
## name: Oasis Rose Light 3
## author: uhs-robert

[colors.primary]
background = '#f3d6e8'
foreground = '#181811'

[colors.selection]
background = '#e5a7cd'
text = '#181811'

[colors.cursor]
cursor = '#9f3a62'
text = '#f3d6e8'

[colors.vi_mode_cursor]
cursor = '#794512'
text = '#f3d6e8'

[colors.normal]
black   = '#3c3c3c'
red     = '#a51111'
green   = '#345b30'
yellow  = '#59531e'
blue    = '#125393'
magenta = '#6d20c7'
cyan    = '#33594f'
white   = '#3e3e1d'

[colors.bright]
black   = '#433a34'
red     = '#a51111'
green   = '#315c2a'
yellow  = '#794512'
blue    = '#1f586f'
magenta = '#6c21c8'
cyan    = '#31594e'
white   = '#3e3e0d'