# extras/alacritty/themes/light/3/oasis_moonlight_light_3.toml
## name: Oasis Moonlight Light 3
## author: uhs-robert

[colors.primary]
background = '#f1ebd5'
foreground = '#161412'

[colors.selection]
background = '#e6dbb2'
text = '#161412'

[colors.cursor]
cursor = '#73661c'
text = '#f1ebd5'

[colors.vi_mode_cursor]
cursor = '#854c14'
text = '#f1ebd5'

[colors.normal]
black   = '#364f74'
red     = '#b41212'
green   = '#396434'
yellow  = '#625b20'
blue    = '#145ba1'
magenta = '#7723d9'
cyan    = '#32625c'
white   = '#5b4d13'

[colors.bright]
black   = '#414f5b'
red     = '#b41212'
green   = '#35642e'
yellow  = '#854c14'
blue    = '#226079'
magenta = '#7624da'
cyan    = '#32625b'
white   = '#564e2e'