# extras/alacritty/themes/light/3/oasis_canyon_light_3.toml
## name: Oasis Canyon Light 3
## author: uhs-robert

[colors.primary]
background = '#eed3bd'
foreground = '#1a150e'

[colors.selection]
background = '#e5bb99'
text = '#1a150e'

[colors.cursor]
cursor = '#874b15'
text = '#eed3bd'

[colors.vi_mode_cursor]
cursor = '#744211'
text = '#eed3bd'

[colors.normal]
black   = '#383838'
red     = '#9e1010'
green   = '#31572e'
yellow  = '#554f1c'
blue    = '#114f8d'
magenta = '#681fbe'
cyan    = '#2b5551'
white   = '#42370e'

[colors.bright]
black   = '#3e3731'
red     = '#9e1010'
green   = '#2f5828'
yellow  = '#744211'
blue    = '#1e5469'
magenta = '#671fbf'
cyan    = '#2b554f'
white   = '#3e3821'