# extras/alacritty/themes/light/3/oasis_moonlight_light_3.toml
## name: Oasis Moonlight Light 3
## author: uhs-robert

[colors.primary]
background = '#e8e5d8'
foreground = '#161412'

[colors.selection]
background = '#d1cbb2'
text = '#161412'

[colors.cursor]
cursor = '#6f631b'
text = '#e8e5d8'

[colors.vi_mode_cursor]
cursor = '#7f4913'
text = '#e8e5d8'

[colors.normal]
black   = '#404040'
red     = '#ad1111'
green   = '#366032'
yellow  = '#5e571f'
blue    = '#13579b'
magenta = '#7322d1'
cyan    = '#305e59'
white   = '#4b3f10'

[colors.bright]
black   = '#483f38'
red     = '#ad1111'
green   = '#33602c'
yellow  = '#7f4913'
blue    = '#215d74'
magenta = '#7122d2'
cyan    = '#305e57'
white   = '#474026'