# extras/alacritty/themes/light/3/oasis_cactus_light_3.toml
## name: Oasis Cactus Light 3
## author: uhs-robert

[colors.primary]
background = '#e0f0e7'
foreground = '#121714'

[colors.selection]
background = '#c1e1cf'
text = '#121714'

[colors.cursor]
cursor = '#427245'
text = '#e0f0e7'

[colors.vi_mode_cursor]
cursor = '#864d14'
text = '#e0f0e7'

[colors.normal]
black   = '#4e4e4e'
red     = '#b51212'
green   = '#396535'
yellow  = '#625c21'
blue    = '#145ba2'
magenta = '#7824db'
cyan    = '#32635d'
white   = '#5c4e14'

[colors.bright]
black   = '#584d44'
red     = '#b51212'
green   = '#36652f'
yellow  = '#864d14'
blue    = '#23617a'
magenta = '#7725db'
cyan    = '#32635c'
white   = '#574e2f'