# extras/alacritty/themes/light/3/oasis_scorpion_light_3.toml
## name: Oasis Scorpion Light 3
## author: uhs-robert

[colors.primary]
background = '#f4cfc3'
foreground = '#191210'

[colors.selection]
background = '#eba68f'
text = '#191210'

[colors.cursor]
cursor = '#655a18'
text = '#f4cfc3'

[colors.vi_mode_cursor]
cursor = '#734211'
text = '#f4cfc3'

[colors.normal]
black   = '#373737'
red     = '#9d1010'
green   = '#31562d'
yellow  = '#554f1c'
blue    = '#114f8b'
magenta = '#681fbd'
cyan    = '#2b5550'
white   = '#41370e'

[colors.bright]
black   = '#3e3630'
red     = '#9d1010'
green   = '#2e5728'
yellow  = '#734211'
blue    = '#1e5469'
magenta = '#661fbe'
cyan    = '#2b554f'
white   = '#3d3721'