# extras/alacritty/themes/light/3/oasis_sol_light_3.toml
## name: Oasis Sol Light 3
## author: uhs-robert

[colors.primary]
background = '#f7d4d4'
foreground = '#6a372d'

[colors.selection]
background = '#f0adad'
text = '#6a372d'

[colors.cursor]
cursor = '#9b2225'
text = '#f7d4d4'

[colors.vi_mode_cursor]
cursor = '#784412'
text = '#f7d4d4'

[colors.normal]
black   = '#454545'
red     = '#a31010'
green   = '#335a2f'
yellow  = '#58521d'
blue    = '#125291'
magenta = '#6c20c4'
cyan    = '#2d5853'
white   = '#514411'

[colors.bright]
black   = '#4d433c'
red     = '#a31010'
green   = '#305b2a'
yellow  = '#784412'
blue    = '#1f576d'
magenta = '#6b20c6'
cyan    = '#2d5852'
white   = '#4c4529'