# extras/alacritty/themes/light/3/oasis_scorpion_light_3.toml
## name: Oasis Scorpion Light 3
## author: uhs-robert

[colors.primary]
background = '#f4d1c3'
foreground = '#543e35'

[colors.selection]
background = '#edb39c'
text = '#543e35'

[colors.cursor]
cursor = '#594f15'
text = '#f4d1c3'

[colors.vi_mode_cursor]
cursor = '#744211'
text = '#f4d1c3'

[colors.normal]
black   = '#424242'
red     = '#9e1010'
green   = '#31572e'
yellow  = '#56501c'
blue    = '#11508d'
magenta = '#691fbf'
cyan    = '#2c5551'
white   = '#4e4211'

[colors.bright]
black   = '#4a413a'
red     = '#9e1010'
green   = '#2f5829'
yellow  = '#744211'
blue    = '#1e546a'
magenta = '#671fc0'
cyan    = '#2c5650'
white   = '#4a4228'