# extras/alacritty/themes/light/3/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors.primary]
background = '#d1e3f5'
foreground = '#0c131d'

[colors.selection]
background = '#abcced'
text = '#0c131d'

[colors.cursor]
cursor = '#6c601a'
text = '#d1e3f5'

[colors.vi_mode_cursor]
cursor = '#7c4713'
text = '#d1e3f5'

[colors.normal]
black   = '#224589'
red     = '#a81111'
green   = '#355d31'
yellow  = '#5b551e'
blue    = '#125596'
magenta = '#7021cb'
cyan    = '#2e5b56'
white   = '#544712'

[colors.bright]
black   = '#3d4956'
red     = '#a81111'
green   = '#325e2b'
yellow  = '#7c4713'
blue    = '#205a71'
magenta = '#6e21cc'
cyan    = '#2e5b55'
white   = '#50482b'